import {test} from 'node:test';
import assert from 'node:assert/strict';
import {statoAutomazione,testiAutomazione,filtraAutomazioni,riepilogoAutomazioni} from '../../src/components/automazioni.js';
import {AUTOMAZIONI,ADESSO} from '../../lab/fixtures/automazioni.js';
test('AUT-STATO: booleani veri, stato ignoto non abilita',()=>{assert.deepEqual(statoAutomazione(true),{testo:'Attiva',tono:'success',prossimo:false});assert.deepEqual(statoAutomazione(false),{testo:'In pausa',tono:'',prossimo:true});assert.equal(statoAutomazione('false').prossimo,null);});
test('AUT-CONTEGGIO-UTC: giornata precedente azzera la lettura, limite raggiunto non promette avvio',()=>{assert.equal(testiAutomazione(AUTOMAZIONI[0],ADESSO).conteggio,'2 di 3');assert.equal(testiAutomazione({...AUTOMAZIONI[0],giornoContatore:'2026-09-04'},ADESSO).conteggio,'0 di 3');assert.equal(testiAutomazione(AUTOMAZIONI[2],ADESSO).prossima,'Limite giornaliero raggiunto');assert.equal(testiAutomazione({...AUTOMAZIONI[2],giornoContatore:'2026-09-06'},ADESSO).conteggio,'0 di 1');});
test('AUT-DATE: avvio registrato non è successo, dati assenti restano espliciti',()=>{const t=testiAutomazione(AUTOMAZIONI[1],ADESSO);assert.equal(t.ultima,'Nessun avvio registrato');assert.equal(t.prossima,'In pausa');assert.equal(t.nome,AUTOMAZIONI[1].nome);assert.equal(testiAutomazione({...AUTOMAZIONI[0],prossimaEsecuzione:'errore'},ADESSO).prossima,'Data non registrata');});
test('AUT-FILTRO: nome completo e task, stato senza perdere query',()=>{assert.equal(filtraAutomazioni(AUTOMAZIONI,{query:'promemoria',stato:'pausa'}).length,1);assert.equal(filtraAutomazioni(AUTOMAZIONI,{query:'promemoria',stato:'attive'}).length,0);assert.equal(filtraAutomazioni(AUTOMAZIONI,{query:'verifica-catalogo'}).length,1);});
test('AUT-RIEPILOGO: nessun numero di esiti inventato',()=>{assert.equal(riepilogoAutomazioni(AUTOMAZIONI),'3 automazioni · 2 attive');assert.equal(riepilogoAutomazioni([]),'0 automazioni · 0 attive');});
