package ai.talos.voice

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The P0 correctness gate from blueprint §9.3: `0 disallineamenti / corpus
 * intero`. The golden corpus (`androidTest/assets/voice/tokenizer-golden-corpus.json`)
 * was generated by the real upstream `sentencepiece` Python package against
 * the exact `tokenizer.model` this device carries — see
 * `.claude/RITORNO-0.1.18.md` for how, and its `tokenizer_model_sha256` field
 * pins which model file it was generated against.
 *
 * ⛔ Reads the real `tokenizer.model` from the same manually-pushed path
 * Phase 0 already uses (`externalFilesDir/moss/…`) — no model ships in the
 * APK, none is downloaded by this test. Absent means skipped, named, per the
 * same `assumeTrue` convention as `TalosMossPhase0SmokeTest`.
 */
@RunWith(AndroidJUnit4::class)
class TalosVoiceTokenizerInstrumentedTest {

    private fun tokenizerModelFile(): File {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        return File(
            context.getExternalFilesDir(null),
            "moss/MOSS-TTS-Nano-100M-ONNX/tokenizer.model",
        )
    }

    private fun loadGoldenCorpus(): JSONObject {
        // Test-APK assets, not the app-under-test's assets: the fixture ships
        // with the test code, not with the app.
        val testContext = InstrumentationRegistry.getInstrumentation().context
        testContext.assets.open("voice/tokenizer-golden-corpus.json").use { stream ->
            return JSONObject(stream.bufferedReader(Charsets.UTF_8).readText())
        }
    }

    private fun sha256Hex(bytes: ByteArray): String {
        val digest = java.security.MessageDigest.getInstance("SHA-256").digest(bytes)
        return digest.joinToString("") { "%02x".format(it) }
    }

    @Test
    fun everyGoldenCaseMatchesTheRealTokenizerModelExactly() {
        val modelFile = tokenizerModelFile()
        assumeTrue(
            "modello MOSS assente: spingilo in ${modelFile.absolutePath}",
            modelFile.isFile,
        )
        val modelBytes = modelFile.readBytes()
        val golden = loadGoldenCorpus()

        // The corpus is pinned to a specific tokenizer.model by hash. If the
        // model on device is a different one, a pass here would prove
        // nothing — fail loudly and by name instead of silently comparing
        // against the wrong reference.
        val expectedSha256 = golden.getString("tokenizer_model_sha256")
        val actualSha256 = sha256Hex(modelBytes)
        assertEquals(
            "tokenizer.model on device does not match the one the golden corpus was generated from",
            expectedSha256,
            actualSha256,
        )

        val model = TalosSentencePieceModel.parse(modelBytes)
        val tokenizer = TalosVoiceBpeTokenizer(model)

        val cases = golden.getJSONArray("cases")
        var mismatches = 0
        val firstFailures = StringBuilder()
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val text = case.getString("text")
            val expectedIdsJson = case.getJSONArray("ids")
            val expected = IntArray(expectedIdsJson.length()) { expectedIdsJson.getInt(it) }
            val actual = tokenizer.encode(text)
            if (!expected.contentEquals(actual)) {
                mismatches++
                if (mismatches <= 5) {
                    firstFailures.append("\n  text=\"$text\" expected=${expected.toList()} actual=${actual.toList()}")
                }
            }
        }
        assertEquals(
            "$mismatches/${cases.length()} tokenizer parity mismatches:$firstFailures",
            0,
            mismatches,
        )
    }

    /**
     * The contrary case (rule: every function is also proven backwards): a
     * parity test that always passes proves nothing by itself unless it can
     * also fail. Two clearly different sentences must not collapse to the
     * same ids, and `count()` must agree with `encode().size` — both would
     * pass trivially against a broken tokenizer that returns a constant.
     */
    @Test
    fun differentTextProducesDifferentIdsAndCountAgreesWithEncode() {
        val modelFile = tokenizerModelFile()
        assumeTrue(
            "modello MOSS assente: spingilo in ${modelFile.absolutePath}",
            modelFile.isFile,
        )
        val model = TalosSentencePieceModel.parse(modelFile.readBytes())
        val tokenizer = TalosVoiceBpeTokenizer(model)

        val a = tokenizer.encode("Ciao, come stai?")
        val b = tokenizer.encode("Il gatto dorme sul divano.")
        assertNotEquals(
            "two different sentences produced identical token ids",
            a.toList(),
            b.toList(),
        )

        val text = "L'appuntamento è alle diciotto e quarantacinque."
        assertEquals(tokenizer.encode(text).size, tokenizer.count(text))

        // And the empty string is a real, empty answer - not a crash.
        assertArrayEquals(IntArray(0), tokenizer.encode(""))
    }
}
