<?php

declare(strict_types=1);

use App\Http\Controllers\BenchmarkComparisonController;
use App\Http\Controllers\FaultExplainerController;
use App\Http\Controllers\FileIngestionController;
use App\Http\Controllers\TalosAdminAuditEventController;
use App\Http\Controllers\TalosAdminBackupController;
use App\Http\Controllers\TalosAdminDoctorController;
use App\Http\Controllers\TalosAdminPolicyController;
use App\Http\Controllers\TalosArtifactController;
use App\Http\Controllers\TalosBenchmarkGroupController;
use App\Http\Controllers\TalosCalendarDraftController;
use App\Http\Controllers\TalosChatController;
use App\Http\Controllers\TalosConnectorController;
use App\Http\Controllers\TalosContextSetController;
use App\Http\Controllers\TalosCookbookController;
use App\Http\Controllers\TalosDocumentController;
use App\Http\Controllers\TalosEmailController;
use App\Http\Controllers\TalosFileController;
use App\Http\Controllers\TalosGoogleCalendarController;
use App\Http\Controllers\TalosGoogleDriveController;
use App\Http\Controllers\TalosGoogleOAuthController;
use App\Http\Controllers\TalosMemoryController;
use App\Http\Controllers\TalosMessageController;
use App\Http\Controllers\TalosModelProfileController;
use App\Http\Controllers\TalosModelComparisonController;
use App\Http\Controllers\TalosNoteController;
use App\Http\Controllers\TalosPromptEnhancementController;
use App\Http\Controllers\TalosRecoveryController;
use App\Http\Controllers\TalosResearchJobController;
use App\Http\Controllers\TalosResearchReportController;
use App\Http\Controllers\TalosRunBenchmarkController;
use App\Http\Controllers\TalosRunController;
use App\Http\Controllers\TalosSessionController;
use App\Http\Controllers\TalosSessionExportController;
use App\Http\Controllers\TalosSettingsController;
use App\Http\Controllers\TalosSkillController;
use App\Http\Controllers\TalosTaskController;
use App\Http\Controllers\TalosToolController;
use App\Http\Controllers\TraceReplayController;
use App\Http\Middleware\EnsureTalosApiAuthenticated;
use Illuminate\Support\Facades\Route;

Route::middleware(['web', EnsureTalosApiAuthenticated::class])->group(function (): void {
    Route::post('/talos/chat', TalosChatController::class);
    Route::prefix('/talos')->group(function (): void {
        Route::get('/model-profiles', [TalosModelProfileController::class, 'index']);
        Route::post('/model-profiles', [TalosModelProfileController::class, 'store']);
        Route::post('/model-profiles/probe-draft', [TalosModelProfileController::class, 'probeDraft']);
        Route::get('/model-profiles/{profile}', [TalosModelProfileController::class, 'show']);
        Route::patch('/model-profiles/{profile}', [TalosModelProfileController::class, 'update']);
        Route::delete('/model-profiles/{profile}', [TalosModelProfileController::class, 'destroy']);
        Route::post('/model-profiles/{profile}/probe', [TalosModelProfileController::class, 'probe']);
        Route::post('/model-comparisons', [TalosModelComparisonController::class, 'store']);
        Route::get('/model-comparisons/{comparison}', [TalosModelComparisonController::class, 'show']);
        Route::post('/model-comparisons/{comparison}/vote', [TalosModelComparisonController::class, 'vote']);
        Route::post('/model-comparisons/{comparison}/benchmark', [TalosModelComparisonController::class, 'benchmark']);
        Route::get('/settings', [TalosSettingsController::class, 'show']);
        Route::patch('/settings', [TalosSettingsController::class, 'update']);
        Route::get('/cookbook/overview', [TalosCookbookController::class, 'overview']);
        Route::post('/cookbook/hardware-scan', [TalosCookbookController::class, 'scan']);
        Route::get('/cookbook/models', [TalosCookbookController::class, 'models']);
        Route::post('/cookbook/models', [TalosCookbookController::class, 'storeModel']);
        Route::post('/cookbook/download-preview', [TalosCookbookController::class, 'downloadPreview']);
        Route::post('/cookbook/serve-preview', [TalosCookbookController::class, 'servePreview']);
        Route::get('/cookbook/planning-context', [TalosCookbookController::class, 'planningContext']);
        Route::get('/google/accounts', [TalosGoogleOAuthController::class, 'accounts']);
        Route::post('/google/disconnect', [TalosGoogleOAuthController::class, 'disconnect']);
        Route::get('/google/drive/files', [TalosGoogleDriveController::class, 'files']);
        Route::post('/google/drive/import', [TalosGoogleDriveController::class, 'import']);
        Route::get('/google/calendar/calendars', [TalosGoogleCalendarController::class, 'calendars']);
        Route::post('/google/calendar/sync', [TalosGoogleCalendarController::class, 'sync']);
        Route::post('/google/calendar/drafts/{calendarDraft}/publish', [TalosGoogleCalendarController::class, 'publish']);
        Route::post('/prompts/enhance', [TalosPromptEnhancementController::class, 'store']);
        Route::get('/sessions', [TalosSessionController::class, 'index']);
        Route::post('/sessions', [TalosSessionController::class, 'store']);
        Route::get('/sessions/{session}', [TalosSessionController::class, 'show']);
        Route::get('/sessions/{session}/export', TalosSessionExportController::class);
        Route::patch('/sessions/{session}', [TalosSessionController::class, 'update']);
        Route::delete('/sessions/{session}', [TalosSessionController::class, 'destroy']);
        Route::get('/sessions/{session}/messages', [TalosMessageController::class, 'index']);
        Route::post('/sessions/{session}/messages', [TalosMessageController::class, 'store']);
        Route::get('/files', [TalosFileController::class, 'index']);
        Route::get('/files/{file}', [TalosFileController::class, 'show']);
        Route::get('/context-sets', [TalosContextSetController::class, 'index']);
        Route::post('/context-sets', [TalosContextSetController::class, 'store']);
        Route::get('/context-sets/{contextSet}', [TalosContextSetController::class, 'show']);
        Route::get('/runs', [TalosRunController::class, 'index']);
        Route::post('/runs', [TalosRunController::class, 'store']);
        Route::get('/runs/{run}', [TalosRunController::class, 'show']);
        Route::patch('/runs/{run}', [TalosRunController::class, 'update']);
        Route::get('/runs/{run}/events', [TalosRunController::class, 'events']);
        Route::post('/runs/{run}/events', [TalosRunController::class, 'storeEvents']);
        Route::get('/runs/{run}/artifacts', [TalosRunController::class, 'artifacts']);
        Route::post('/runs/{run}/artifacts', [TalosRunController::class, 'storeArtifact']);
        Route::post('/runs/{run}/recover', TalosRecoveryController::class);
        Route::get('/runs/{run}/replay', [TalosRunController::class, 'replay']);
        Route::post('/runs/{run}/benchmark', TalosRunBenchmarkController::class);
        Route::get('/benchmark-groups', [TalosBenchmarkGroupController::class, 'index']);
        Route::get('/benchmark-groups/{benchmarkGroup}/export', [TalosBenchmarkGroupController::class, 'export']);
        Route::get('/benchmark-groups/{benchmarkGroup}', [TalosBenchmarkGroupController::class, 'show']);
        Route::get('/connectors', [TalosConnectorController::class, 'index']);
        Route::post('/connectors', [TalosConnectorController::class, 'store']);
        Route::get('/connectors/{connector}', [TalosConnectorController::class, 'show']);
        Route::patch('/connectors/{connector}', [TalosConnectorController::class, 'update']);
        Route::delete('/connectors/{connector}', [TalosConnectorController::class, 'destroy']);
        Route::get('/tools', [TalosToolController::class, 'index']);
        Route::post('/tools', [TalosToolController::class, 'store']);
        Route::get('/tools/planning-context', [TalosToolController::class, 'planningContext']);
        Route::get('/tools/{tool}', [TalosToolController::class, 'show']);
        Route::patch('/tools/{tool}', [TalosToolController::class, 'update']);
        Route::delete('/tools/{tool}', [TalosToolController::class, 'destroy']);
        Route::get('/memories', [TalosMemoryController::class, 'index']);
        Route::post('/memories', [TalosMemoryController::class, 'store']);
        Route::get('/memories/retrieval-context', [TalosMemoryController::class, 'retrievalContext']);
        Route::get('/memories/{memory}', [TalosMemoryController::class, 'show']);
        Route::patch('/memories/{memory}', [TalosMemoryController::class, 'update']);
        Route::delete('/memories/{memory}', [TalosMemoryController::class, 'destroy']);
        Route::get('/skills', [TalosSkillController::class, 'index']);
        Route::post('/skills', [TalosSkillController::class, 'store']);
        Route::get('/skills/planning-context', [TalosSkillController::class, 'planningContext']);
        Route::get('/skills/{skill}', [TalosSkillController::class, 'show']);
        Route::patch('/skills/{skill}', [TalosSkillController::class, 'update']);
        Route::delete('/skills/{skill}', [TalosSkillController::class, 'destroy']);
        Route::post('/skills/{skill}/evaluation', [TalosSkillController::class, 'evaluation']);
        Route::get('/research-reports', [TalosResearchReportController::class, 'index']);
        Route::post('/research-reports', [TalosResearchReportController::class, 'store']);
        Route::get('/research-reports/{researchReport}/export', [TalosResearchReportController::class, 'export']);
        Route::post('/research-reports/{researchReport}/follow-up-session', [TalosResearchReportController::class, 'followUpSession']);
        Route::get('/research-reports/{researchReport}', [TalosResearchReportController::class, 'show']);
        Route::post('/research-jobs', [TalosResearchJobController::class, 'store']);
        Route::get('/research-jobs/{job}', [TalosResearchJobController::class, 'show']);
        Route::post('/research-jobs/{job}/cancel', [TalosResearchJobController::class, 'cancel']);
        Route::post('/research-jobs/{job}/fixtures', [TalosResearchJobController::class, 'fixtures']);
        Route::get('/documents', [TalosDocumentController::class, 'index']);
        Route::post('/documents', [TalosDocumentController::class, 'store']);
        Route::get('/documents/{document}/export', [TalosDocumentController::class, 'export']);
        Route::get('/documents/{document}', [TalosDocumentController::class, 'show']);
        Route::get('/artifacts', [TalosArtifactController::class, 'index']);
        Route::get('/artifacts/{artifact}/preview', [TalosArtifactController::class, 'preview']);
        Route::get('/artifacts/{artifact}', [TalosArtifactController::class, 'show']);
        Route::get('/notes', [TalosNoteController::class, 'index']);
        Route::post('/notes', [TalosNoteController::class, 'store']);
        Route::get('/notes/retrieval-context', [TalosNoteController::class, 'retrievalContext']);
        Route::get('/notes/{note}', [TalosNoteController::class, 'show']);
        Route::get('/tasks', [TalosTaskController::class, 'index']);
        Route::post('/tasks', [TalosTaskController::class, 'store']);
        Route::get('/calendar-drafts', [TalosCalendarDraftController::class, 'index']);
        Route::post('/calendar-drafts', [TalosCalendarDraftController::class, 'store']);
        Route::post('/calendar-drafts/{calendarDraft}/confirm', [TalosCalendarDraftController::class, 'confirm']);
        Route::get('/email/connector-status', [TalosEmailController::class, 'connectorStatus']);
        Route::get('/email/messages', [TalosEmailController::class, 'messages']);
        Route::post('/email/messages', [TalosEmailController::class, 'storeMessage']);
        Route::get('/email/messages/context', [TalosEmailController::class, 'messageContext']);
        Route::get('/email/drafts', [TalosEmailController::class, 'drafts']);
        Route::post('/email/drafts', [TalosEmailController::class, 'storeDraft']);
        Route::post('/email/drafts/{emailDraft}/send', [TalosEmailController::class, 'send']);
        Route::get('/admin/doctor', TalosAdminDoctorController::class);
        Route::get('/admin/policy', TalosAdminPolicyController::class);
        Route::get('/admin/audit-events', [TalosAdminAuditEventController::class, 'index']);
        Route::get('/admin/backup/manifest', [TalosAdminBackupController::class, 'manifest']);
        Route::post('/admin/backup/validate-restore', [TalosAdminBackupController::class, 'validateRestore']);
    });
    Route::post('/files/ingest', FileIngestionController::class);
    Route::post('/benchmarks/compare', BenchmarkComparisonController::class);
    Route::post('/faults/explain', FaultExplainerController::class);
    Route::post('/traces/replay', TraceReplayController::class);
});
