import {createHash} from 'node:crypto';import {cp,mkdir,readFile,readdir,rm,writeFile} from 'node:fs/promises';import {basename,dirname,join,resolve} from 'node:path';import {validateArchiveEntries,validateExtensionManifest,type ExtensionManifest} from './package-schema.ts';import {readZipEntries} from '../archive/zip.ts';import {CLI_VERSION} from '../version.ts';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
async function json(file:string,fallback:any){try{return JSON.parse(await readFile(file,'utf8'));}catch(e:any){if(e?.code==='ENOENT')return fallback;throw e;}}
async function atomicJson(file:string,value:any){await mkdir(dirname(file),{recursive:true});const t=`${file}.tmp-${process.pid}`;await writeFile(t,`${JSON.stringify(value,null,2)}\n`,'utf8');await rm(file,{force:true});await import('node:fs/promises').then(m=>m.rename(t,file));}
function safeId(id:string){if(!/^[a-z0-9][a-z0-9._-]{1,79}$/u.test(id))throw new Error('EXTENSION_ID_INVALID');return id;}
export type InstalledExtension={id:string;name:string;version:string;source:string;components:{mcp?:Array<{id:string;hash:string}>;hooks?:Array<{id:string;hash:string}>;plugin?:{id:string;hash:string};commands?:string[]}};
async function readExtensionManifest(sourceDir:string){for(const name of ['extension.json','talos-extension.json']){try{return JSON.parse(await readFile(join(sourceDir,name),'utf8'));}catch(error:any){if(error?.code!=='ENOENT')throw error;}}throw Object.assign(new Error('EXTENSION_MANIFEST_MISSING'),{code:'EXTENSION_MANIFEST_MISSING'});}
export async function installExtensionDirectory({sourceDir,projectRoot,currentVersion=CLI_VERSION}:{sourceDir:string;projectRoot:string;currentVersion?:string}){const manifest=validateExtensionManifest(await readExtensionManifest(sourceDir),currentVersion);safeId(manifest.id);const stateDir=join(projectRoot,'.talos-cli','extensions',manifest.id);const installedFile=join(stateDir,'installed.json');try{await readFile(installedFile,'utf8');throw new Error('EXTENSION_ALREADY_INSTALLED');}catch(e:any){if(e?.message==='EXTENSION_ALREADY_INSTALLED')throw e;if(e?.code!=='ENOENT')throw e;}const record:InstalledExtension={id:manifest.id,name:manifest.name,version:manifest.version,source:resolve(sourceDir),components:{}};await mkdir(stateDir,{recursive:true});await cp(sourceDir,join(stateDir,'package'),{recursive:true});
 if(manifest.components.plugin){const src=join(sourceDir,manifest.components.plugin);const text=await readFile(src,'utf8');const parsed=JSON.parse(text);const dest=join(projectRoot,'.harness-ui-plugins',manifest.id,'plugin.json');await mkdir(dirname(dest),{recursive:true});await writeFile(dest,text,'utf8');record.components.plugin={id:manifest.id,hash:hash(parsed)};}
 if(manifest.components.mcp){const src=JSON.parse(await readFile(join(sourceDir,manifest.components.mcp),'utf8'));if(!Array.isArray(src?.server))throw new Error('EXTENSION_MCP_INVALID');const file=join(projectRoot,'.harness-ui-mcp.json');const cur=await json(file,{server:[]});if(!Array.isArray(cur.server))throw new Error('MCP_CONFIG_MALFORMED');const ids=new Set(cur.server.map((x:any)=>x.id));for(const row of src.server){if(!row?.id||ids.has(row.id))throw new Error('EXTENSION_COMPONENT_COLLISION');ids.add(row.id);}cur.server.push(...src.server);await atomicJson(file,cur);record.components.mcp=src.server.map((x:any)=>({id:x.id,hash:hash(x)}));}
 if(manifest.components.hooks){const src=JSON.parse(await readFile(join(sourceDir,manifest.components.hooks),'utf8'));if(!Array.isArray(src?.hooks))throw new Error('EXTENSION_HOOKS_INVALID');const file=join(projectRoot,'.harness-ui-hooks.json');const cur=await json(file,{hooks:[]});if(!Array.isArray(cur.hooks))throw new Error('HOOK_CONFIG_MALFORMED');const ids=new Set(cur.hooks.map((x:any)=>x.id));for(const row of src.hooks){if(!row?.id||ids.has(row.id))throw new Error('EXTENSION_COMPONENT_COLLISION');ids.add(row.id);}cur.hooks.push(...src.hooks);await atomicJson(file,cur);record.components.hooks=src.hooks.map((x:any)=>({id:x.id,hash:hash(x)}));}
 if(manifest.components.commands){const src=join(sourceDir,manifest.components.commands);const dest=join(projectRoot,'.talos-cli','commands',manifest.id);await cp(src,dest,{recursive:true});const files=(await readdir(dest,{recursive:true} as any)).filter((x:any)=>String(x).endsWith('.md')).map(String);record.components.commands=files;}
 await atomicJson(installedFile,record);return record;}
export async function listInstalledExtensions(projectRoot:string){const root=join(projectRoot,'.talos-cli','extensions');let ids:string[];try{ids=await readdir(root);}catch{return [];}const rows=[];for(const id of ids){try{rows.push(JSON.parse(await readFile(join(root,id,'installed.json'),'utf8')));}catch{}}return rows.sort((a:any,b:any)=>a.id.localeCompare(b.id));}
export async function removeInstalledExtension({projectRoot,id}:{projectRoot:string;id:string}){safeId(id);const stateDir=join(projectRoot,'.talos-cli','extensions',id);const record=JSON.parse(await readFile(join(stateDir,'installed.json'),'utf8')) as InstalledExtension;
 if(record.components.mcp){const file=join(projectRoot,'.harness-ui-mcp.json');const cur=await json(file,{server:[]});for(const owned of record.components.mcp){const row=cur.server.find((x:any)=>x.id===owned.id);if(row&&hash(row)!==owned.hash)throw new Error(`EXTENSION_COMPONENT_MODIFIED:mcp:${owned.id}`);}cur.server=cur.server.filter((x:any)=>!record.components.mcp!.some(o=>o.id===x.id));await atomicJson(file,cur);}
 if(record.components.hooks){const file=join(projectRoot,'.harness-ui-hooks.json');const cur=await json(file,{hooks:[]});for(const owned of record.components.hooks){const row=cur.hooks.find((x:any)=>x.id===owned.id);if(row&&hash(row)!==owned.hash)throw new Error(`EXTENSION_COMPONENT_MODIFIED:hook:${owned.id}`);}cur.hooks=cur.hooks.filter((x:any)=>!record.components.hooks!.some(o=>o.id===x.id));await atomicJson(file,cur);}
 if(record.components.plugin){const file=join(projectRoot,'.harness-ui-plugins',id,'plugin.json');try{const current=JSON.parse(await readFile(file,'utf8'));if(hash(current)!==record.components.plugin.hash)throw new Error(`EXTENSION_COMPONENT_MODIFIED:plugin:${id}`);}catch(e:any){if(e?.code!=='ENOENT')throw e;}await rm(join(projectRoot,'.harness-ui-plugins',id),{recursive:true,force:true});}
 if(record.components.commands)await rm(join(projectRoot,'.talos-cli','commands',id),{recursive:true,force:true});await rm(stateDir,{recursive:true,force:true});return{ok:true,id};}
export async function installExtension({source,projectRoot,currentVersion=CLI_VERSION}:{source:string;projectRoot:string;currentVersion?:string}){if(source.toLowerCase().endsWith('.zip')){const entries=readZipEntries(await readFile(source));const names=[...entries.keys()];validateArchiveEntries(names,process.platform==='win32');const os=await import('node:os');const fs=await import('node:fs/promises');const temp=await fs.mkdtemp(join(os.tmpdir(),'talos-ext-'));try{for(const [name,data] of entries){if(name.endsWith('/')){await mkdir(join(temp,name),{recursive:true});continue;}const dest=join(temp,name);await mkdir(dirname(dest),{recursive:true});await writeFile(dest,data);}return await installExtensionDirectory({sourceDir:temp,projectRoot,currentVersion});}finally{await rm(temp,{recursive:true,force:true});}}return installExtensionDirectory({sourceDir:source,projectRoot,currentVersion});}
