import { describe, expect, it, vi } from 'vitest'
import { createTalosImageTools } from '@/lib/images/imageTools'
import { executeTalosTool } from '@/lib/tools/executor'

function imageTool() {
    const generate = vi.fn(async () => ({
        images: [{ base64: 'AA==', mediaType: 'image/png' }],
        error: null,
        permanent: false,
    }))
    const save = vi.fn(async () => ({
        id: 'generated-1',
        name: 'generated.png',
        sha256: 'a'.repeat(64),
        attachment: {
            id: 'generated-binding-1',
            vault_file_id: 'generated-1',
            grant_id: 'generated-grant-1',
        },
    }))
    const [tool] = createTalosImageTools({
        provider: () => 'OpenRouter',
        generate,
        save,
    })
    return { tool, generate, save }
}

describe('generate_image capability boundary', () => {
    it('P0-CAP-IMG-01 declares outbound plus write', () => {
        const { tool } = imageTool()

        expect(tool.action).toBe('write')
        expect(tool.requiredActions).toEqual(['outbound', 'write'])
    })

    it('blocks before provider or persistence when outbound is denied', async () => {
        const { tool, generate, save } = imageTool()

        const result = await executeTalosTool(tool, { prompt: 'a red fox' }, {
            permissions: { read: 'allow', write: 'allow', outbound: 'deny' },
            isToolEnabled: () => true,
            requestConsent: vi.fn(async () => true),
            audit: vi.fn(async () => {}),
            context: { sessionId: 'session-1' },
        })

        expect(result).toMatchObject({
            ok: false,
            code: 'TALOS_TOOL_DENIED_BY_POLICY',
        })
        expect(generate).not.toHaveBeenCalled()
        expect(save).not.toHaveBeenCalled()
    })

    it('IMAGE-DUR-FAIL-01 fails closed when generated bytes cannot be persisted', async () => {
        const { tool, generate, save } = imageTool()
        save.mockRejectedValueOnce(new Error('private path and raw storage detail'))

        const result = await executeTalosTool(tool, { prompt: 'a red fox' }, {
            permissions: { read: 'allow', write: 'allow', outbound: 'allow' },
            isToolEnabled: () => true,
            requestConsent: vi.fn(async () => true),
            audit: vi.fn(async () => {}),
            context: { sessionId: 'session-1' },
        })

        expect(result).toMatchObject({
            ok: false,
            code: 'TALOS_IMAGE_PERSIST_FAILED',
        })
        expect(result.content).toContain('TALOS_IMAGE_PERSIST_FAILED')
        expect(result.content).toMatch(/not available in (?:the )?chat or Library/i)
        expect(result.content).toMatch(/do not (?:retry|regenerate)/i)
        expect(result.content).not.toContain('private path')
        expect(result.images).toBeUndefined()
        expect(result.messageAttachments).toBeUndefined()
        expect(generate).toHaveBeenCalledTimes(1)
        expect(save).toHaveBeenCalledTimes(1)
    })
})
