export type HighlightKind='plain'|'key'|'string'|'number'|'literal'|'keyword'|'comment'|'operator';
export type HighlightToken={text:string;kind:HighlightKind};
const JS_LANGS=new Set(['js','jsx','javascript','ts','tsx','typescript']);
const SH_LANGS=new Set(['sh','bash','shell','powershell','ps1']);
const JS_KEYWORDS=new Set(['const','let','var','function','return','if','else','for','while','class','new','import','from','export','async','await','try','catch','throw','interface','type','extends','implements','public','private','protected','readonly']);
function tokenize(line:string,re:RegExp,classify:(text:string,index:number)=>HighlightKind):HighlightToken[]{const out:HighlightToken[]=[];let pos=0;for(const m of line.matchAll(re)){const i=m.index??0;if(i>pos)out.push({text:line.slice(pos,i),kind:'plain'});out.push({text:m[0],kind:classify(m[0],i)});pos=i+m[0].length;}if(pos<line.length)out.push({text:line.slice(pos),kind:'plain'});return out.length?out:[{text:line,kind:'plain'}];}
function json(line:string):HighlightToken[]{return tokenize(line,/"(?:\\.|[^"\\])*"(?=\s*:)|"(?:\\.|[^"\\])*"|-?\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b|\b(?:true|false|null)\b/gu,(t)=>{if(/^"/u.test(t))return /"\s*$/u.test(t)&&new RegExp(`${t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*:`).test(line)?'key':'string';if(/^(?:true|false|null)$/u.test(t))return'literal';return'number';});}
function js(line:string):HighlightToken[]{const comment=line.search(/\/\/|\/\*/u);const head=comment>=0?line.slice(0,comment):line;const body=tokenize(head,/'(?:\\.|[^'\\])*'|"(?:\\.|[^"\\])*"|`(?:\\.|[^`\\])*`|\b[A-Za-z_$][A-Za-z0-9_$]*\b|\b\d+(?:\.\d+)?\b|=>|===|!==|==|!=|<=|>=|&&|\|\||[+\-*/%=<>!?]/gu,(t)=>{if(/^['"`]/u.test(t))return'string';if(/^\d/u.test(t))return'number';if(JS_KEYWORDS.has(t))return'keyword';if(/^(?:true|false|null|undefined)$/u.test(t))return'literal';if(/^[+\-*/%=<>!?&|]/u.test(t))return'operator';return'plain';});if(comment>=0)body.push({text:line.slice(comment),kind:'comment'});return body;}
function sh(line:string):HighlightToken[]{const comment=line.indexOf('#');const head=comment>=0?line.slice(0,comment):line;const body=tokenize(head,/'(?:[^']*)'|"(?:\\.|[^"\\])*"|\$[A-Za-z_][A-Za-z0-9_]*|\b(?:if|then|else|fi|for|in|do|done|case|esac|function|param|foreach|throw|exit)\b|\b\d+\b/gu,(t)=>{if(/^['"]/u.test(t))return'string';if(/^\$/u.test(t))return'literal';if(/^\d/u.test(t))return'number';return'keyword';});if(comment>=0)body.push({text:line.slice(comment),kind:'comment'});return body;}
export function highlightCodeLine(line:string,language=''):HighlightToken[]{const lang=language.toLowerCase().trim();if(lang==='json'||lang==='jsonc')return json(line);if(JS_LANGS.has(lang))return js(line);if(SH_LANGS.has(lang))return sh(line);return[{text:line,kind:'plain'}] as HighlightToken[];}
