#!/usr/bin/env python3
"""Generate the 14 per-theme Android adaptive launcher icons for TALOS mobile.

Owner (2026-07-24): the launcher icon follows the active theme preset. Each of
the 14 presets gets its own adaptive icon = preset BACKGROUND colour behind the
canonical TALOS mark (shield + DAG) stroked in the preset ACCENT colour — a 1:1
mirror of the in-app themed logo (desktop parity).

minSdk is 26, so ONLY mipmap-anydpi-v26 adaptive icons are needed (no legacy
raster fallback). Source of truth for the mark = public/talos/brand/logo-short.svg
(viewBox 0 0 500 500). Circles are expressed as stroked ring paths and the two
diagonal branches as rotated VectorDrawable groups (SVG translate()->rotate()).

Regenerate after any preset table / mark change:
    python tools/android-assets/gen_theme_icons.py
"""
import os

# (id, background, accent) — kept in TALOS_THEME_IDS order (src/lib/talosThemes.ts).
PRESETS = [
    ("forge",     "#080b11", "#c98b32"),
    ("paper",     "#f8fafc", "#a96617"),
    ("terminal",  "#020403", "#63f08e"),
    ("aurora",    "#071113", "#42e7c7"),
    ("glacier",   "#f4f9fb", "#2367d1"),
    ("ember",     "#10090a", "#ff5c62"),
    ("atlas",     "#07101f", "#d49a52"),
    ("noir",      "#050505", "#f2f2f2"),
    ("signal",    "#091011", "#ff6f61"),
    ("violet",    "#0d0a19", "#b794f6"),
    ("claudius",  "#faf9f5", "#d97757"),
    ("basicus",   "#fafafa", "#1976d2"),
    ("telemetry", "#0b0f11", "#6ad4d4"),
    ("calm",      "#1e1f22", "#c08b3c"),
]
DEFAULT_ID = "calm"  # TALOS_DEFAULT_THEME — the alias shipped enabled in the manifest.

RES = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", "android", "app", "src", "main", "res"))


def ring(cx: float, cy: float, r: float) -> str:
    """A stroked circle expressed as a VectorDrawable ring path (no <circle> in AVD)."""
    return f"M{cx - r},{cy} a{r},{r} 0 1,0 {2 * r},0 a{r},{r} 0 1,0 {-2 * r},0"


def stroke_path(data: str, color: str, width: float) -> str:
    return (
        f'    <path android:strokeColor="{color}" android:strokeWidth="{width}"\n'
        f'        android:strokeLineCap="round" android:strokeLineJoin="round"\n'
        f'        android:fillColor="#00000000" android:pathData="{data}" />'
    )


def foreground_vector(accent: str) -> str:
    shield = ("M218,123.5 L121.9,179 A21,21 0 0 0 111.5,197 L111.5,333 "
              "A21,21 0 0 0 121.9,351 L239.6,419 A21,21 0 0 0 260.4,419 "
              "L378.1,351 A21,21 0 0 0 388.5,333 L388.5,197 A21,21 0 0 0 378.1,179 L282,123.5")
    body = "\n".join([
        stroke_path(shield, accent, 12),
        stroke_path(ring(250, 105, 22), accent, 9),
        stroke_path(ring(250, 225, 18), accent, 9),
        stroke_path(ring(250, 338, 14), accent, 9),
        stroke_path("M250,140 L250,195", accent, 9),
        stroke_path("M250,255 L250,315", accent, 9),
    ])
    branch = (
        f'    <group android:translateX="250" android:translateY="225" android:rotation="{{deg}}">\n'
        f'      <path android:strokeColor="{accent}" android:strokeWidth="9"\n'
        f'          android:strokeLineCap="round" android:strokeLineJoin="round"\n'
        f'          android:fillColor="#00000000" android:pathData="M0,32 L0,95" />\n'
        f'      <path android:strokeColor="{accent}" android:strokeWidth="9"\n'
        f'          android:strokeLineCap="round" android:strokeLineJoin="round"\n'
        f'          android:fillColor="#00000000" android:pathData="{ring(0, 118, 14)}" />\n'
        f'    </group>'
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- GENERATED by tools/android-assets/gen_theme_icons.py — do not edit by hand. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="500" android:viewportHeight="500">\n'
        '  <group android:scaleX="0.86" android:scaleY="0.86" android:pivotX="250" android:pivotY="251">\n'
        f'{body}\n'
        f'{branch.format(deg=45)}\n'
        f'{branch.format(deg=-45)}\n'
        '  </group>\n'
        '</vector>\n'
    )


def adaptive_icon(pid: str) -> str:
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- GENERATED by tools/android-assets/gen_theme_icons.py — do not edit by hand. -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        f'    <background android:drawable="@color/ic_talos_bg_{pid}" />\n'
        f'    <foreground android:drawable="@drawable/ic_talos_fg_{pid}" />\n'
        '</adaptive-icon>\n'
    )


def main() -> None:
    drawable = os.path.join(RES, "drawable")
    anydpi = os.path.join(RES, "mipmap-anydpi-v26")
    os.makedirs(drawable, exist_ok=True)
    os.makedirs(anydpi, exist_ok=True)

    for pid, _bg, accent in PRESETS:
        with open(os.path.join(drawable, f"ic_talos_fg_{pid}.xml"), "w", encoding="utf-8") as f:
            f.write(foreground_vector(accent))
        for suffix in ("", "_round"):
            with open(os.path.join(anydpi, f"ic_launcher_{pid}{suffix}.xml"), "w", encoding="utf-8") as f:
                f.write(adaptive_icon(pid))

    # The base app icon (used by recents/settings and as the pre-alias default) is
    # the TALOS default-theme mark, replacing the Capacitor placeholder icon.
    for suffix in ("", "_round"):
        with open(os.path.join(anydpi, f"ic_launcher{suffix}.xml"), "w", encoding="utf-8") as f:
            f.write(adaptive_icon(DEFAULT_ID))

    # Per-preset background colours.
    colors = ['<?xml version="1.0" encoding="utf-8"?>',
              "<!-- GENERATED (theme icon backgrounds) by gen_theme_icons.py — do not edit by hand. -->",
              "<resources>"]
    for pid, bg, _accent in PRESETS:
        colors.append(f'    <color name="ic_talos_bg_{pid}">{bg}</color>')
    colors.append("</resources>\n")
    with open(os.path.join(RES, "values", "ic_talos_colors.xml"), "w", encoding="utf-8") as f:
        f.write("\n".join(colors))

    # The manifest alias list + the default, emitted as snippets for review/paste.
    aliases = []
    for pid, _bg, _accent in PRESETS:
        enabled = "true" if pid == DEFAULT_ID else "false"
        aliases.append(
            f'        <activity-alias\n'
            f'            android:name=".MainActivityIcon_{pid}"\n'
            f'            android:enabled="{enabled}"\n'
            f'            android:exported="true"\n'
            f'            android:icon="@mipmap/ic_launcher_{pid}"\n'
            f'            android:roundIcon="@mipmap/ic_launcher_{pid}_round"\n'
            f'            android:label="@string/app_name"\n'
            f'            android:targetActivity=".MainActivity">\n'
            f'            <intent-filter>\n'
            f'                <action android:name="android.intent.action.MAIN" />\n'
            f'                <category android:name="android.intent.category.LAUNCHER" />\n'
            f'            </intent-filter>\n'
            f'        </activity-alias>'
        )
    with open(os.path.join(os.path.dirname(__file__), "aliases.generated.xml"), "w", encoding="utf-8") as f:
        f.write("\n".join(aliases) + "\n")

    print(f"OK: {len(PRESETS)} presets -> foregrounds+adaptive+round, ic_talos_colors.xml, aliases.generated.xml")
    print(f"    default enabled alias: MainActivityIcon_{DEFAULT_ID}")


if __name__ == "__main__":
    main()
