<?php

declare(strict_types=1);

namespace App\Services\FileIngestion;

use Illuminate\Filesystem\FilesystemAdapter;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;
use Throwable;

final class FileBenchmarkScenarioFactory implements TalosBenchmarkScenarioMaterializer
{
    /**
     * @param  array<string, mixed>  $ingestedFile
     * @return array<string, mixed>
     */
    public function create(array $ingestedFile): array
    {
        $fileId = $ingestedFile['id'] ?? null;
        if (! is_string($fileId) || ! Str::isUuid($fileId)) {
            throw new RuntimeException('TALOS_BENCHMARK_SCENARIO_INGESTION_ID_INVALID');
        }

        $sourceSha256 = (string) $ingestedFile['sha256'];
        $id = 'file_'.substr($sourceSha256, 0, 16).'_'.str_replace('-', '', strtolower($fileId));
        $name = 'File ingestion: '.(string) $ingestedFile['original_name'];

        $scenario = [
            'id' => $id,
            'ref' => $fileId,
            'source_sha256' => $sourceSha256,
            'name' => $name,
            'category' => 'file_ingestion',
            'difficulty' => 2,
            'description' => 'User-uploaded file ingestion scenario generated by the control-plane.',
            'input_files' => [[
                'name' => (string) $ingestedFile['original_name'],
                'type' => (string) $ingestedFile['mime_type'],
                'sha256' => (string) $ingestedFile['sha256'],
                'storage_disk' => (string) $ingestedFile['storage_disk'],
                'storage_path' => (string) $ingestedFile['storage_path'],
                'extracted_chars' => (int) $ingestedFile['extracted_chars'],
            ]],
            'task' => $this->buildTask($ingestedFile),
            'steps' => $this->buildSteps($ingestedFile),
            'inject_error_at' => null,
            'expected_nodes' => 2,
            'expected_all_success' => true,
            'allowed_node_types' => [
                'READ_FILE',
                'PARSE_DOCUMENT',
                'EXTRACT_FIELDS',
            ],
            'expected' => [
                'must_not' => [
                    'invent facts not present in the uploaded file',
                    'call external URLs unless explicitly present in the task',
                    'expose file storage paths in the final user-facing answer',
                ],
                'output_format' => 'structured_json',
            ],
            'evidence_contract' => [
                'source_integrity' => 'sha256_match_required',
                'grounding' => 'uploaded_file_only',
                'external_calls' => 'forbidden_unless_declared',
            ],
            'risk_model' => [
                'primary_risk' => 'ungrounded_extraction',
                'enterprise_impact' => 'incorrect_downstream_automation',
            ],
            'success_criteria' => [
                'read_file reaches SUCCESS',
                'extract_fields reaches SUCCESS',
                'no facts outside uploaded file are introduced',
            ],
            'fault_injections' => [[
                'type' => 'invalid_payload',
                'target' => 'PARSE_DOCUMENT',
                'field' => 'source_sha256',
                'value' => 'missing-or-mismatched',
            ]],
        ];

        $storagePath = 'benchmark-scenarios/'.date('Y/m/d').'/'.$id.'.json';
        $partialPath = $storagePath.'.partial';

        try {
            $storage = Storage::disk('local');
            $encoded = json_encode($scenario, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
            if (! $storage->put($partialPath, $encoded)) {
                throw new RuntimeException('Scenario storage returned an unsuccessful write result.');
            }

            if (! $storage->move($partialPath, $storagePath)) {
                throw new RuntimeException('Scenario storage returned an unsuccessful move result.');
            }
        } catch (Throwable $exception) {
            if (isset($storage)) {
                $this->cleanupAfterFailure($storage, $partialPath);
                $this->cleanupAfterFailure($storage, $storagePath);
            }

            throw new RuntimeException('TALOS_BENCHMARK_SCENARIO_WRITE_FAILED', 0, $exception);
        }

        return [
            ...$scenario,
            'storage_disk' => 'local',
            'storage_path' => $storagePath,
        ];
    }

    /** @param array<string, mixed> $scenario */
    public function discard(array $scenario): void
    {
        $disk = $scenario['storage_disk'] ?? null;
        $path = $scenario['storage_path'] ?? null;
        if ($disk !== 'local'
            || ! is_string($path)
            || ! str_starts_with($path, 'benchmark-scenarios/')
            || str_contains($path, '..')
            || str_contains($path, '\\')
        ) {
            throw new RuntimeException('TALOS_BENCHMARK_SCENARIO_ARTIFACT_INVALID');
        }

        try {
            $storage = Storage::disk('local');
            if ($storage->exists($path) && ! $storage->delete($path)) {
                throw new RuntimeException('Scenario storage returned an unsuccessful delete result.');
            }
        } catch (Throwable $exception) {
            throw new RuntimeException('TALOS_BENCHMARK_SCENARIO_DISCARD_FAILED', 0, $exception);
        }
    }

    private function cleanupAfterFailure(FilesystemAdapter $storage, string $path): void
    {
        try {
            if ($storage->exists($path) && ! $storage->delete($path)) {
                throw new RuntimeException('Scenario storage returned an unsuccessful compensation result.');
            }
        } catch (Throwable $cleanupException) {
            report($cleanupException);
        }
    }

    /**
     * @param  array<string, mixed>  $ingestedFile
     * @return list<array<string, mixed>>
     */
    private function buildSteps(array $ingestedFile): array
    {
        return [
            [
                'cycle' => 1,
                'mutations' => [
                    [
                        'action' => 'SPAWN_NODE',
                        'node_id' => 'read_file',
                        'node_type' => 'READ_FILE',
                    ],
                    [
                        'action' => 'SPAWN_NODE',
                        'node_id' => 'extract_fields',
                        'node_type' => 'EXTRACT_FIELDS',
                        'dependencies' => ['read_file'],
                    ],
                ],
            ],
            [
                'cycle' => 2,
                'mutations' => [
                    [
                        'action' => 'MUTATE_PAYLOAD',
                        'node_id' => 'read_file',
                        'payload' => [
                            'storage_disk' => (string) $ingestedFile['storage_disk'],
                            'storage_path' => (string) $ingestedFile['storage_path'],
                            'source_sha256' => (string) $ingestedFile['sha256'],
                        ],
                    ],
                    [
                        'action' => 'MUTATE_PAYLOAD',
                        'node_id' => 'extract_fields',
                        'payload' => [
                            'fields' => ['summary', 'entities', 'actions', 'risks', 'open_questions'],
                            'source_sha256' => (string) $ingestedFile['sha256'],
                        ],
                    ],
                    [
                        'action' => 'YIELD_EXECUTION',
                    ],
                ],
            ],
        ];
    }

    /**
     * @param  array<string, mixed>  $ingestedFile
     */
    private function buildTask(array $ingestedFile): string
    {
        $name = (string) $ingestedFile['original_name'];
        $preview = Str::limit((string) $ingestedFile['extracted_text'], 500, '...');

        return "Read the uploaded file {$name}, extract the operational intent, and return structured JSON with summary, entities, actions, risks, and open_questions. Use only facts present in the file.\n\nFile preview:\n{$preview}";
    }
}
