<?php

declare(strict_types=1);

namespace App\Services\FileIngestion;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

final class FileBenchmarkScenarioFactory
{
    /**
     * @param array<string, mixed> $ingestedFile
     * @return array<string, mixed>
     */
    public function create(array $ingestedFile): array
    {
        $id = 'file_' . substr((string) $ingestedFile['sha256'], 0, 16);
        $name = 'File ingestion: ' . (string) $ingestedFile['original_name'];

        $scenario = [
            'id' => $id,
            'name' => $name,
            'category' => 'file_ingestion',
            'difficulty' => 2,
            'description' => 'User-uploaded file ingestion scenario generated by the control-plane.',
            'input_files' => [[
                'name' => (string) $ingestedFile['original_name'],
                'type' => (string) $ingestedFile['mime_type'],
                'sha256' => (string) $ingestedFile['sha256'],
                'storage_disk' => (string) $ingestedFile['storage_disk'],
                'storage_path' => (string) $ingestedFile['storage_path'],
                'extracted_chars' => (int) $ingestedFile['extracted_chars'],
            ]],
            'task' => $this->buildTask($ingestedFile),
            'allowed_node_types' => [
                'READ_FILE',
                'PARSE_DOCUMENT',
                'EXTRACT_FIELDS',
            ],
            'expected' => [
                'must_not' => [
                    'invent facts not present in the uploaded file',
                    'call external URLs unless explicitly present in the task',
                    'expose file storage paths in the final user-facing answer',
                ],
                'output_format' => 'structured_json',
            ],
            'fault_injections' => [[
                'type' => 'invalid_payload',
                'target' => 'PARSE_DOCUMENT',
                'field' => 'source_sha256',
                'value' => 'missing-or-mismatched',
            ]],
        ];

        $storagePath = 'benchmark-scenarios/' . date('Y/m/d') . '/' . $id . '.json';
        Storage::disk('local')->put($storagePath, (string) json_encode($scenario, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        return [
            ...$scenario,
            'storage_disk' => 'local',
            'storage_path' => $storagePath,
        ];
    }

    /**
     * @param array<string, mixed> $ingestedFile
     */
    private function buildTask(array $ingestedFile): string
    {
        $name = (string) $ingestedFile['original_name'];
        $preview = Str::limit((string) $ingestedFile['extracted_text'], 500, '...');

        return "Read the uploaded file {$name}, extract the operational intent, and return structured JSON with summary, entities, actions, risks, and open_questions. Use only facts present in the file.\n\nFile preview:\n{$preview}";
    }
}
