import {test} from 'node:test';
import assert from 'node:assert/strict';
import {STORAGE_KEY,DEFAULT_PREFS,DEMO_MODELS,normalize,searchSettings,filterModels,validatePrefs,loadSnapshot,saveSnapshot,createState,availability,updateDownload,escapeHTML} from '../src/domain.mjs';
const store=()=>{const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),data};};
const fresh=()=>createState(loadSnapshot(store()));
const ids=ms=>ms.map(x=>x.id);
const job={id:'test',status:'running',progress:0};
test('normalizzazione: accenti, maiuscole, whitespace',()=>assert.equal(normalize('  DENSITÀ  '),'densita'));
test('normalizzazione di null',()=>assert.equal(normalize(null),''));
test('ricerca alias precedente: API key',()=>assert.equal(searchSettings('API key')[0].tab,'providers'));
test('ricerca alias accessibilità: animazioni',()=>assert.equal(searchSettings('animazioni')[0].target,'motion'));
test('ricerca con AND; query inesistente non restituisce tutto',()=>assert.equal(searchSettings('API inesistente').length,0));
test('ricerca vuota restituisce indice non vuoto',()=>assert.equal(searchSettings('').length,9));
test('catalogo completo, 15 fixture distinte',()=>assert.equal(new Set(ids(filterModels(DEMO_MODELS))).size,15));
test('filtro locale non include cloud',()=>assert.equal(filterModels(DEMO_MODELS,{filter:'local'}).length,12));
test('filtro cloud non include locale',()=>assert.equal(filterModels(DEMO_MODELS,{filter:'cloud'}).length,3));
test('installati indipendente da semplice presenza nel catalogo',()=>assert.equal(filterModels(DEMO_MODELS,{filter:'installed'}).length,2));
test('preferiti indipendenti da selezione e installazione',()=>assert.deepEqual(ids(filterModels(DEMO_MODELS,{filter:'favorites',favorites:['local:qwen32']})),['local:qwen32']));
test('attività + provider + ricerca combinabili',()=>assert.deepEqual(ids(filterModels(DEMO_MODELS,{filter:'local',task:'code',query:'qwen 32'})),['local:qwen32']));
test('nessun match non cancella la sorgente',()=>{assert.equal(filterModels(DEMO_MODELS,{query:'xxxyyzz'}).length,0);assert.equal(DEMO_MODELS.length,15);});
test('preferenze: enum invalidi ricondotti al default',()=>assert.deepEqual(validatePrefs({mode:'neon',density:'tiny',motion:'false',textSize:200}),DEFAULT_PREFS));
test('preferenze: booleani false preservati',()=>{const p=validatePrefs({motion:false,resume:false});assert.equal(p.motion,false);assert.equal(p.resume,false);});
test('preferenze: oggetti inattesi non accettati',()=>assert.deepEqual(validatePrefs([]),DEFAULT_PREFS));
test('storage: roundtrip persistente mediante doppio di test',()=>{const s=store(),st=fresh();st.prefs.mode='light';st.favorites=['local:gemma'];st.defaultId='local:gemma';assert.equal(saveSnapshot(s,st),true);const r=loadSnapshot(s);assert.equal(r.prefs.mode,'light');assert.deepEqual(r.favorites,st.favorites);assert.equal(r.defaultId,'local:gemma');});
test('storage: namespace separato e nessun segreto o prompt',()=>{const s=store(),st=fresh();st.apiKey='secret-not-persisted';st.prompt='private draft';saveSnapshot(s,st);assert.deepEqual([...s.data.keys()],[STORAGE_KEY]);assert.doesNotMatch(s.data.get(STORAGE_KEY),/secret-not-persisted|private draft|downloads/);});
test('storage: JSON corrotto recuperabile',()=>{const s=store();s.setItem(STORAGE_KEY,'{{');assert.equal(loadSnapshot(s).defaultId,'local:qwen8');});
test('storage: versione non supportata non migrata arbitrariamente',()=>{const s=store();s.setItem(STORAGE_KEY,JSON.stringify({version:9,prefs:{mode:'light'}}));assert.equal(loadSnapshot(s).prefs.mode,'dark');});
test('storage: identità sconosciute filtrate e preferiti deduplicati',()=>{const s=store();s.setItem(STORAGE_KEY,JSON.stringify({version:1,defaultId:'wrong',favorites:['local:gemma','bad','local:gemma']}));assert.deepEqual(loadSnapshot(s).favorites,['local:gemma']);assert.equal(loadSnapshot(s).defaultId,'local:qwen8');});
test('storage: errore di quota/restrizione non è successo',()=>assert.equal(saveSnapshot({setItem(){throw Error('denied')}},fresh()),false));
test('nuovo stato non condivide gli oggetti modello',()=>{const a=fresh(),b=fresh();a.models[0].installed=false;assert.equal(b.models[0].installed,true);});
test('locale resta disponibile in assenza rete',()=>{const s=fresh();s.scenario='offline';assert.equal(availability(s.models[0],s).usable,true);});
test('cloud indisponibile offline, senza fallback',()=>{const s=fresh();s.scenario='offline';assert.equal(availability(s.models[3],s).usable,false);assert.equal(s.defaultId,'local:qwen8');});
test('credenziale presente ma non verificata non equivale a servizio disponibile',()=>{const s=fresh();s.providerStatus='unverified';assert.equal(availability(s.models[3],s).usable,false);});
test('runtime in errore non è modello disponibile',()=>{const s=fresh();s.scenario='error';assert.equal(availability(s.models[0],s).usable,false);});
test('memoria insufficiente dopo installazione blocca uso',()=>{const s=fresh();s.models[2].installed=true;assert.equal(availability(s.models[2],s).usable,false);assert.equal(availability(s.models[2],s).label,'RAM insufficiente');});
test('tools sconosciuto preservato, non inventato',()=>assert.equal(fresh().models[0].tools,null));
test('download: tick non muta input',()=>{const n=updateDownload(job,'tick');assert.equal(n.progress,8);assert.equal(job.progress,0);});
test('download: pausa congela avanzamento',()=>{const p=updateDownload(job,'pause');assert.equal(updateDownload(p,'tick').progress,0);assert.equal(p.status,'paused');});
test('download: ripresa prosegue',()=>assert.equal(updateDownload(updateDownload(updateDownload(job,'pause'),'resume'),'tick').progress,8));
test('download: annullamento definitivo',()=>{const p=updateDownload(job,'cancel');for(const a of ['resume','tick','pause'])assert.deepEqual(updateDownload(p,a),p);});
test('download: errore ripristinabile',()=>assert.equal(updateDownload({...job,status:'error'},'resume').status,'running'));
test('download: 100% finito e nessun overflow',()=>{const n=updateDownload({...job,progress:96},'tick');assert.equal(n.progress,100);assert.equal(n.status,'completed');assert.deepEqual(updateDownload(n,'tick'),n);});
test('download completato non può essere annullato',()=>assert.equal(updateDownload({...job,status:'completed',progress:100},'cancel').status,'completed'));
test('output utente: escaping impedisce HTML eseguibile',()=>assert.equal(escapeHTML(`<img onerror="alert('x')"> &`),'&lt;img onerror=&quot;alert(&#39;x&#39;)&quot;&gt; &amp;'));
