from pathlib import Path
from playwright.sync_api import sync_playwright
import json, os, shutil
R=Path(__file__).resolve().parents[1]
checks=[]
def check(label, condition):
 assert condition,label
 checks.append(label)
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),args=['--no-sandbox'])
 page=b.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content((R/'talos-sidebar-interattiva.html').read_text())
 page.locator('#toast').evaluate('el=>el.hidden=true');page.screenshot(path=str(R/'artifacts/01-file.png'))
 check('starts in files',page.evaluate('TalosLab.state().activeTab')=='files')
 page.get_by_role('tab',name='Agenti',exact=True).click()
 page.get_by_role('button',name='Dettaglio Navigazione',exact=True).click()
 check('agent detail opens',page.locator('#agentDetail').get_attribute('data-agent-id')=='fix')
 for tab,key in [('File','files'),('Context','context'),('Processi','processes'),('Agenti','agents')]:
  page.get_by_role('tab',name=tab,exact=True).click();check('switch '+key,page.evaluate('TalosLab.state().activeTab')==key)
 check('detail restored',page.locator('#agentDetail').get_attribute('data-agent-id')=='fix')
 page.locator('#toast').evaluate('el=>el.hidden=true');page.screenshot(path=str(R/'artifacts/02-agenti.png'))
 page.get_by_role('tab',name='File',exact=True).click()
 page.get_by_label('Cerca file',exact=True).fill('ext:css')
 check('extension search',page.locator('[data-file]').count()==4)
 page.get_by_label('Cerca file',exact=True).fill('no-match-ever')
 check('empty search',page.get_by_text('Nessuna corrispondenza',exact=True).is_visible())
 page.get_by_role('button',name='Azzera ricerca',exact=True).click()
 page.locator('[data-file="inspector.js"] .fname').click()
 check('preview opens',page.evaluate('TalosLab.state().central')=='file')
 page.get_by_role('button',name='Al Context',exact=True).click()
 check('context receives file',page.locator('#railContent').get_by_text('inspector.js',exact=True).count()==1)
 page.get_by_role('tab',name='File',exact=True).click()
 page.locator('[data-file="main.css"] .fname').click()
 page.get_by_role('button',name='Azioni selezione',exact=True).click();page.get_by_role('menuitem',name='Refactor',exact=True).click()
 check('review from selected file',page.get_by_role('heading',name='Revisione modifiche').is_visible())
 page.get_by_label('Simula conflitto',exact=True).check()
 check('conflict blocks approval',page.get_by_role('button',name='Integra nella demo',exact=True).is_disabled())
 page.locator('#toast').evaluate('el=>el.hidden=true');page.screenshot(path=str(R/'artifacts/04-review-conflitto.png'))
 page.get_by_label('Simula conflitto',exact=True).uncheck()
 page.get_by_role('button',name='Integra nella demo',exact=True).click()
 check('approval is simulated',page.evaluate('TalosLab.state().reviewStatus')=='applied')
 page.get_by_role('button',name='Richiedi revisione',exact=True).click()
 check('revision ready',page.evaluate('TalosLab.state().reviewStatus')=='ready')
 page.get_by_role('button',name='Scarta',exact=True).click()
 check('discard',page.evaluate('TalosLab.state().reviewStatus')=='discarded')
 page.get_by_role('tab',name='Agenti',exact=True).click()
 page.get_by_role('button',name='Apri questo agente nel diagramma',exact=True).click()
 page.wait_for_timeout(100)
 check('graph opens',page.locator('.node').count()==6)
 page.get_by_label('Ambito del diagramma',exact=True).select_option('workspace')
 check('workspace graph',page.locator('.node').count()==8)
 page.get_by_label('Ambito del diagramma',exact=True).select_option('execution')
 check('execution graph',page.locator('.node').count()==5)
 page.get_by_label('Ambito del diagramma',exact=True).select_option('session')
 page.get_by_label('Filtra stato nel diagramma',exact=True).select_option('error')
 check('graph error filter',page.locator('.node').count()==1)
 page.get_by_label('Filtra stato nel diagramma',exact=True).select_option('all')
 page.get_by_label('Cerca agente nel diagramma',exact=True).fill('Confina')
 check('graph search',page.locator('.node').count()==1)
 page.get_by_label('Cerca agente nel diagramma',exact=True).fill('')
 page.get_by_role('button',name='Adatta',exact=True).click()
 page.locator('#toast').evaluate('el=>el.hidden=true');page.screenshot(path=str(R/'artifacts/03-diagramma.png'))
 page.get_by_label('Timeline della simulazione',exact=True).fill('0')
 check('replay initial',page.locator('.node').count()==1)
 page.get_by_label('Timeline della simulazione',exact=True).fill('4')
 page.get_by_role('button',name='Affianca file',exact=True).click()
 check('split preview',page.locator('.split-preview').is_visible())
 page.get_by_role('button',name='Chiudi affiancamento',exact=True).click()
 page.get_by_role('tab',name='File',exact=True).click()
 check('File independent while graph open',page.evaluate('TalosLab.state().central')=='graph')
 page.get_by_label('Simula stato del pannello',exact=True).select_option('loading')
 check('loading',page.get_by_text('Caricamento della vista…',exact=True).is_visible())
 page.get_by_role('tab',name='Agenti',exact=True).click()
 check('tab during loading',page.evaluate('TalosLab.state().activeTab')=='agents')
 page.get_by_label('Simula stato del pannello',exact=True).select_option('error')
 page.get_by_role('button',name='Riprova',exact=True).click()
 check('error retry',page.locator('#agentDetail').is_visible())
 page.get_by_role('tab',name='File',exact=True).click()
 page.get_by_label('Simula stato del pannello',exact=True).select_option('large')
 check('virtual rows bounded',page.locator('[data-file]').count()<=32)
 page.locator('#fileScroll').evaluate('el=>el.scrollTop=25000')
 page.wait_for_timeout(60)
 check('virtual scroll advances',page.locator('[data-file]').first.get_attribute('data-file').startswith('fixture-'))
 page.get_by_label('Simula stato del pannello',exact=True).select_option('normal')
 page.get_by_role('tab',name='File',exact=True).focus();page.keyboard.press('ArrowRight')
 check('keyboard tabs',page.evaluate('TalosLab.state().activeTab')=='agents')
 old=page.evaluate('TalosLab.state().width');page.locator('#resizer').focus();page.keyboard.press('ArrowLeft')
 check('keyboard resize',page.evaluate('TalosLab.state().width')==old+20)
 page.locator('[data-action=session][data-id=docs]').click()
 check('detail scoped to session',page.evaluate('TalosLab.state().selectedAgent') is None)
 page.locator('[data-action=session][data-id=sidebar]').click()
 check('session restores detail',page.evaluate('TalosLab.state().selectedAgent')=='fix')
 page.get_by_role('button',name='Come provarlo',exact=True).click()
 check('guide modal',page.get_by_role('dialog').is_visible())
 page.keyboard.press('Escape');check('guide close',not page.get_by_role('dialog').is_visible())
 page.set_viewport_size({'width':1280,'height':800})
 page.get_by_role('tab',name='File',exact=True).click();page.locator('#toast').evaluate('el=>el.hidden=true');page.screenshot(path=str(R/'artifacts/05-desktop-stretto.png'))
 check('no page overflow at desktop size',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
 check('no script errors',not errors)
 (R/'artifacts/test-report.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'pageErrors':errors},indent=2,ensure_ascii=False))
 print('PASS',len(checks),'checks; page errors:',errors)
 b.close()
