from pathlib import Path
from playwright.sync_api import sync_playwright
import json, os, shutil
R=Path(__file__).resolve().parents[1]; checks=[]; errors=[]; requests=[]
def ck(label, condition):
 assert condition, label
 checks.append(label)
def main():
 with sync_playwright() as p:
  browser=p.chromium.launch(headless=True,executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),args=['--no-sandbox'])
  page=browser.new_page(viewport={'width':1440,'height':1000});page.set_default_timeout(6000)
  page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
  def load(): page.set_content((R/'talos-sidebar-interattiva.html').read_text());page.wait_for_selector('#fileTree')
  def menu(name): page.get_by_role('menuitem',name=name,exact=True).click()
  def row(name): return page.locator('[data-file]').filter(has=page.locator('.fname',has_text=name)).first
  def select(name):page.locator('[data-file="'+name+'"] .fname').click()
  def filemenu(name):page.locator('[data-file="'+name+'"]').hover();page.get_by_role('button',name='Azioni su '+name,exact=True).click()
  def reset():page.get_by_role('button',name='Ripristina demo',exact=True).click()
  load()
  ck('clean default has no selection footer',page.locator('.file-selection').count()==0)
  ck('file filter moved to single native selector',page.get_by_label('Vista file').is_visible() and page.locator('#railFile .filters').count()==0)
  ck('no initial auto-selection',page.evaluate('TalosLab.state().selectedFiles.length')==0)
  page.screenshot(path=str(R/'artifacts/after-calm-file.png'))
  page.get_by_label('Cerca file',exact=True).fill('/[/');ck('invalid regex visible',page.locator('#fileSearchError').is_visible());ck('search invalid semantics',page.get_by_label('Cerca file',exact=True).get_attribute('aria-invalid')=='true')
  page.get_by_label('Cerca file',exact=True).fill('/(a+)+$/');ck('nested quantifier refused',page.locator('#fileSearchError').is_visible())
  page.get_by_label('Cerca file',exact=True).fill('ext:CSS');ck('uppercase extension query',page.locator('[data-file]').count()==4)
  page.get_by_label('Cerca file',exact=True).fill(''); select('inspector.js')
  page.get_by_role('button',name='Al Context',exact=True).click()
  page.locator('[data-action=session][data-id=docs]').click();page.get_by_role('tab',name='File',exact=True).click();select('inspector.js');page.get_by_role('button',name='Al Context',exact=True).click()
  page.locator('[data-action=session][data-id=sidebar]').click();page.get_by_role('tab',name='File',exact=True).click();filemenu('inspector.js');menu('Rinomina')
  page.get_by_label('Nuovo nome del file',exact=True).fill('renamed.js');page.keyboard.press('Enter')
  page.locator('[data-action=session][data-id=docs]').click();page.get_by_role('tab',name='Context',exact=True).click();ck('rename propagates to inactive context',page.locator('#railContext').get_by_text('renamed.js',exact=True).count()==1)
  page.get_by_role('tab',name='File',exact=True).click();filemenu('renamed.js');menu('Duplica');select('copia-1-renamed.js');ck('duplicate preserves body',page.locator('.source-code').inner_text().find('renderInspector')>=0)
  filemenu('renamed.js');menu('Copia');filemenu('main.css');menu('Incolla qui');select('copia-2-renamed.js');ck('copy paste preserves body',page.locator('.source-code').inner_text().find('renderInspector')>=0)
  filemenu('renamed.js');menu('Sposta nel cestino demo');ck('deleted file not in live list',page.locator('[data-file="renamed.js"]').count()==0)
  page.get_by_role('tab',name='Context',exact=True).click();ck('delete removes context reference',page.locator('#railContext').get_by_text('renamed.js',exact=True).count()==0)
  page.get_by_role('tab',name='File',exact=True).click();page.get_by_label('Vista file').select_option('trash');page.get_by_role('button',name='Ripristina',exact=True).click();page.get_by_label('Vista file').select_option('all');ck('restore returns live file',page.locator('[data-file="renamed.js"]').count()==1)
  filemenu('renamed.js');menu('Rinomina');page.get_by_label('Nuovo nome del file',exact=True).fill('__proto__');page.keyboard.press('Enter');ck('invalid rename stays editable',page.get_by_label('Nuovo nome del file',exact=True).get_attribute('aria-invalid')=='true');page.keyboard.press('Escape')
  reset();ck('reset restores original names',page.locator('[data-file="inspector.js"]').count()==1 and page.locator('[data-file="renamed.js"]').count()==0)
  filemenu('inspector-tab-visibility.css');menu('Rinomina');page.get_by_label('Nuovo nome del file',exact=True).fill('renamed-guard.css');page.keyboard.press('Enter')
  page.locator('.center-tabs [data-value=review]').click();ck('review snapshot survives explorer rename',page.locator('.diff').inner_text().find('@supports selector(:has(*))')>=0)
  reset()
  select('main.css');page.get_by_role('button',name='Azioni selezione',exact=True).click();menu('Refactor');page.get_by_label('Simula conflitto',exact=True).check();ck('conflict blocks integration',page.get_by_role('button',name='Integra nella demo',exact=True).is_disabled());page.screenshot(path=str(R/'artifacts/after-review.png'))
  page.get_by_role('tab',name='File',exact=True).click();filemenu('main.css');page.keyboard.press('End');ck('menu End reaches final item',page.evaluate("document.activeElement.textContent").strip()=='Sposta nel cestino demo');page.keyboard.press('Home');ck('menu Home reaches first item',page.evaluate("document.activeElement.textContent").strip()=='Apri agente collegato');page.keyboard.press('Escape');ck('menu Escape restores trigger',page.evaluate("document.activeElement.getAttribute('aria-label')")=='Azioni su main.css')
  page.locator('[data-folder="components"]').focus();page.keyboard.press('ArrowLeft');ck('keyboard collapse',page.locator('[data-file="inspector.js"]').count()==0);page.keyboard.press('ArrowRight');ck('keyboard expand',page.locator('[data-file="inspector.js"]').count()==1);page.keyboard.press('ArrowRight');ck('keyboard child focus',page.evaluate("document.activeElement.dataset.file")=='inspector.js');page.keyboard.press('Space');ck('space multiselect', 'inspector.js' in page.evaluate('TalosLab.state().selectedFiles'))
  page.keyboard.press('Shift+F10');ck('keyboard context menu',page.get_by_role('menu').is_visible());page.keyboard.press('Escape')
  page.get_by_label('Simula stato del pannello',exact=True).select_option('large');page.locator('#fileScroll').evaluate('n=>n.scrollTop=25000');page.wait_for_timeout(50)
  ck('large dataset virtualizes',page.locator('[data-file]').count()<=32);ck('scroll reaches generated file',page.locator('[data-file]').first.get_attribute('data-file').startswith('fixture-'))
  count=page.evaluate('TalosLab.fileCount()');first=page.locator('[data-file]').first.get_attribute('data-file');select(first);ck('opening synthetic file never duplicates record',page.evaluate('TalosLab.fileCount()')==count)
  page.get_by_role('button',name='Densità',exact=True).click();page.wait_for_timeout(50);ck('compact virtual row geometry',abs(page.locator('[data-file]').first.bounding_box()['height']-32)<1)
  ck('compact virtual render stays bounded',page.locator('[data-file]').count()<=36)
  page.locator('[data-file]').first.focus();page.keyboard.press('End');ck('keyboard reaches final virtual file',page.evaluate('document.activeElement.dataset.file')=='fixture-0999.ts');page.keyboard.press('Home');ck('keyboard returns to first virtual file',page.evaluate('document.activeElement.dataset.file')=='inspector.js')
  before=page.locator('#fileScroll').evaluate('n=>n.scrollTop');page.get_by_role('tab',name='Agenti',exact=True).click();page.get_by_role('button',name='Dettaglio Navigazione',exact=True).click();page.get_by_role('tab',name='File',exact=True).click();ck('file scroll independent from agent detail',abs(page.locator('#fileScroll').evaluate('n=>n.scrollTop')-before)<2)
  page.get_by_role('button',name='Come provarlo',exact=True).click();ck('guide makes background inert',page.locator('#shell').evaluate('n=>n.inert'));page.keyboard.press('Escape');ck('guide releases background',not page.locator('#shell').evaluate('n=>n.inert'))
  reset();page.get_by_label('Simula stato del pannello',exact=True).select_option('normal')
  for w,h in [(1280,800),(1440,1000),(1920,1080)]:
   page.set_viewport_size({'width':w,'height':h});page.locator('#resizer').focus();page.keyboard.press('Home');ck('page overflow '+str(w),page.evaluate('document.documentElement.scrollWidth<=innerWidth'));ck('300px sidebar controls fit '+str(w),page.locator('#railFile').evaluate('n=>n.scrollWidth<=n.clientWidth'))
  page.set_viewport_size({'width':1280,'height':800});page.screenshot(path=str(R/'artifacts/after-narrow.png'))
  ck('no page errors',not errors);ck('standalone makes no network requests',not requests)
  (R/'artifacts/hardening-report.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'errors':errors,'requests':requests,'browser':browser.version},indent=2,ensure_ascii=False))
  print('PASS',len(checks),'hardening checks')
  browser.close()
if __name__=='__main__': main()
