from pathlib import Path
from playwright.sync_api import sync_playwright
import json, os, shutil
R=Path(__file__).resolve().parents[1];checks=[]
def ck(t,b):
 assert b,t
 checks.append(t)
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),args=['--no-sandbox'])
 page=b.new_page(viewport={'width':1440,'height':1000})
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content((R/'talos-sidebar-interattiva.html').read_text())
 page.get_by_role('button',name='Crea file demo',exact=True).click()
 page.get_by_label('Nuovo nome del file',exact=True).fill('prova.js');page.keyboard.press('Enter')
 ck('inline create and rename',page.locator('[data-file="prova.js"]').count()==1)
 page.get_by_role('button',name='Azioni su prova.js',exact=True).click()
 page.get_by_role('menuitem',name='Duplica',exact=True).click()
 ck('duplicate',page.locator('[data-file="copia-1-prova.js"]').count()==1)
 page.get_by_role('button',name='Azioni su prova.js',exact=True).click()
 page.get_by_role('menuitem',name='Sposta nel cestino demo',exact=True).click()
 ck('trash',page.locator('[data-file="prova.js"]').count()==0)
 page.get_by_label('Vista file').select_option('trash')
 page.get_by_role('button',name='Ripristina',exact=True).click()
 page.get_by_label('Vista file').select_option('all')
 ck('restore',page.locator('[data-file="prova.js"]').count()==1)
 page.get_by_label('Cerca file',exact=True).fill('/^src\\/styles/')
 ck('regex search',page.locator('[data-file]').count()==4)
 page.get_by_label('Cerca file',exact=True).fill('~inspcss')
 ck('fuzzy search',page.locator('[data-file="inspector-tab-visibility.css"]').count()==1)
 page.get_by_label('Cerca file',exact=True).fill('testo:--talos-background')
 ck('fixture full-text search',page.locator('[data-file="index.css"]').count()==1)
 page.get_by_label('Cerca file',exact=True).fill('')
 page.locator('[data-file="index.css"] .fname').click()
 page.get_by_role('button',name='Al Context',exact=True).click()
 page.locator('[data-action=session][data-id=docs]').click()
 ck('context isolated between sessions',page.get_by_role('heading',name='Nessun file aggiunto').is_visible())
 page.locator('[data-action=session][data-id=sidebar]').click()
 ck('context restored',page.locator('#railContent').get_by_text('index.css',exact=True).count()==1)
 page.get_by_role('tab',name='Agenti',exact=True).click()
 page.get_by_role('button',name='Apri visuale diagramma',exact=True).click()
 page.locator('.node[data-agent="fix"] [data-action="collapse-branch"]').click()
 ck('collapse hides descendants',page.locator('.node').count()==4)
 page.locator('.node[data-agent="fix"] [data-action="collapse-branch"]').click()
 ck('expand restores descendants',page.locator('.node').count()==6)
 page.locator('.node[data-agent="fix"]').click()
 page.get_by_role('button',name='Isola nel diagramma',exact=True).click()
 ck('isolation',page.locator('.node').count()==1)
 page.get_by_role('button',name='Esci da isolamento',exact=True).click()
 ck('exit isolation',page.locator('.node').count()==6)
 for tab in page.locator('#railTabs button').all():
  ck('ARIA target exists '+tab.inner_text(),page.locator('#'+tab.get_attribute('aria-controls')).count()==1)
 ck('no errors',not errors)
 (R/'artifacts/explorer-test-report.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'pageErrors':errors},indent=2))
 print('PASS',len(checks),'additional checks')
 b.close()
