/** CP06: a model is a destination, never an inspector. No remote Markdown is executed. */
import {availability,escapeHTML,fmt,fmtPrice} from './domain.mjs';
import {icon,modelGlyph,button,badge,emptyState} from './ui.mjs';

export const MODEL_SOURCES = Object.freeze({
  'local:qwen8': {repo:'Qwen/Qwen3-8B-GGUF', url:'https://huggingface.co/Qwen/Qwen3-8B-GGUF', kind:'GGUF', params:'8,2B', layers:'36', summary:true},
  'local:qwen32': {repo:'Qwen/Qwen3-32B-GGUF', url:'https://huggingface.co/Qwen/Qwen3-32B-GGUF', kind:'GGUF', params:'32,8B', layers:'64', summary:true},
  'local:gemma': {repo:'google/gemma-3-12b-it', url:'https://huggingface.co/google/gemma-3-12b-it', kind:'Modello base', summary:false},
});
export const DETAIL_TABS = Object.freeze(['card','files','compatibility']);
export function modelSource(id){return MODEL_SOURCES[id]||null;}
export function sourceLink(source,label='Apri su Hugging Face',cls='text-link'){
  return source?`<a class="${cls}" href="${escapeHTML(source.url)}" target="_blank" rel="noopener noreferrer" aria-label="${escapeHTML(label)} · nuova scheda">${escapeHTML(label)}${icon('external')}</a>`:'';
}
export function modelPrimaryAction(m,state){
  const a=availability(m,state),cloud=m.destination==='cloud',def=m.id===state.defaultId;
  const job=state.downloads.find(j=>j.modelId===m.id&&['running','paused','error'].includes(j.status));
  if(!m.installed&&!cloud&&job)return button('Vedi download','open-downloads',{id:'model-primary-action',ic:'download',data:`data-model="${m.id}"`});
  return button(def?'Già predefinito':!m.installed&&!cloud?'Scarica · demo':'Usa per le nuove chat',!m.installed&&!cloud?'download-model':'set-default',{id:'model-primary-action',kind:def?'secondary':'primary',ic:def?'check':!m.installed&&!cloud?'download':'arrow',data:`data-model="${m.id}"`,disabled:def||(!cloud&&(!m.file||!m.format))||(!a.usable&&(m.installed||cloud))});
}
export function renderModelPage(m,state){
  const source=modelSource(m.id),a=availability(m,state),cloud=m.destination==='cloud',favorite=state.favorites.includes(m.id);
  return `<div class="model-page" data-model-page="${m.id}">
    <div class="model-page-toolbar">
      ${button('Tutti i modelli','back-catalog',{kind:'ghost',ic:'back',id:'back-catalog'})}
      <span class="toolbar-identity">${escapeHTML(m.name)}<span>${cloud?'Cloud':'Locale'}</span></span>
      <div class="model-page-actions">${button('Banco prova','test-model',{ic:'play',data:`data-model="${m.id}"`,disabled:!a.usable})}${modelPrimaryAction(m,state)}</div>
    </div>
    <header class="model-hero">
      <div class="model-hero-identity">${modelGlyph(m.glyph,true)}<div><div class="eyebrow">${cloud?'MODELLO VIA PROVIDER':'NEL TUO LABORATORIO'}</div><h1 id="page-title" tabindex="-1">${escapeHTML(m.name)}</h1><p class="model-repository">${source?icon('document'):icon('cloud')}<span>${escapeHTML(source?.repo||(m.synthetic?'Fixture TALOS · nessun repository':m.provider))}</span>${source?.kind==='Modello base'?badge('Scheda del modello base'):''}</p></div></div>
      <button class="button ghost model-page-favorite ${favorite?'is-favorite':''}" data-action="favorite" data-model="${m.id}" aria-pressed="${favorite}" aria-label="${favorite?'Rimuovi':'Aggiungi'} ${escapeHTML(m.name)} ${favorite?'dai':'ai'} preferiti">${icon('star')}<span>${favorite?'Nei preferiti':'Preferito'}</span></button>
      <p class="model-hero-caption">${cloud?'Prima la destinazione dei dati. Poi la scelta.':'Conosci il modello. Scegli come usarlo.'}</p>
    </header>
    <section class="model-context-strip" aria-label="Configurazione TALOS dimostrativa">
      <div>${icon(cloud?'cloud':'screen')}<span><small>DESTINAZIONE</small><strong>${cloud?escapeHTML(m.provider):'Sul dispositivo'}</strong></span></div>
      <div><span><small>${cloud?'ACCESSO':'PROFILO DEMO'}</small><strong>${cloud?'Via provider':escapeHTML((m.format||'Formato non noto')+' · '+(m.quantization||'quantizzazione non nota'))}</strong></span></div>
      <div><span><small>STATO DEMO</small>${badge(a.label,a.tone,true)}</span></div>
      <div class="model-context-choice"><span><small>NUOVE CHAT</small><strong>${m.id===state.defaultId?'Modello predefinito':'Non è il predefinito'}</strong></span></div>
    </section>
    ${!a.usable&&(m.installed||cloud)?`<div class="inline-notice warning action-reason">${icon('alert')}<span>${escapeHTML(a.reason)}</span>${state.scenario==='error'&&!cloud?button('Riprova','recover-runtime',{kind:'ghost',ic:'refresh'}):''}</div>`:''}
    <div class="model-page-tabs" role="tablist" aria-label="Sezioni della scheda modello">${[['card',cloud?'Scheda provider':m.synthetic?'Scheda demo':'Scheda Hugging Face','document'],['files',cloud?'Accesso e identità':'File del modello','folder'],['compatibility','Compatibilità','cpu']].map(([id,label,ic])=>`<button role="tab" type="button" id="model-tab-${id}" data-action="model-detail-tab" data-value="${id}" aria-selected="${state.detailTab===id}" aria-controls="model-detail-panel" tabindex="${state.detailTab===id?0:-1}">${icon(ic)}${label}</button>`).join('')}<span class="model-page-tab-note">${icon('shield')}Nessun avvio automatico</span></div>
    <section id="model-detail-panel" role="tabpanel" aria-labelledby="model-tab-${state.detailTab}" tabindex="0">${state.detailTab==='card'?renderModelCard(m,state):state.detailTab==='files'?renderModelFiles(m,state):renderModelCompatibility(m,state)}</section>
    <p class="model-page-end">${icon('info')}Leggere una scheda non scarica file, non carica il modello e non cambia le nuove chat.</p>
  </div>`;
}
function cardStatePicker(state){
 return `<label class="card-state-picker"><span>Stato demo</span><select id="card-preview-state" aria-label="Stato dimostrativo della scheda">${[['ready','Disponibile'],['loading','Caricamento'],['missing','Assente'],['error','Errore']].map(([v,t])=>`<option value="${v}" ${v===state.cardStatus?'selected':''}>${t}</option>`).join('')}</select></label>`;
}
export function renderModelCard(m,state){
 const source=modelSource(m.id),cloud=m.destination==='cloud';
 const stateHeader=`<div class="readme-chrome"><span>${icon('document')}<strong>${cloud?'Scheda provider':'README.md'}</strong><span class="readme-format">${cloud?'Record demo':'Anteprima editoriale'}</span></span>${!cloud?cardStatePicker(state):badge('Non è una scheda Hugging Face')}</div>`;
 if(m.synthetic&&!cloud)return renderSyntheticCard(m);
 if(cloud)return `<article class="readme-surface">${stateHeader}<div class="readme-body provider-document"><div class="eyebrow">PROVENIENZA DISTINTA</div><h2>${escapeHTML(m.name)}</h2><p class="readme-lead">${escapeHTML(m.description)}</p><section><h3>Un modello cloud non è un file locale.</h3><p>Questo record è una fixture del catalogo ${escapeHTML(m.provider)}. Nessun repository Hugging Face è stato associato: non mostriamo una scheda inventata.</p></section><section><h3>Prima di usarlo</h3><p>La scelta per le nuove chat richiede una conferma della destinazione dei dati. Disponibilità, costi e supporto strumenti reali devono essere verificati separatamente.</p>${button('Provider e accessi','providers-tab',{ic:'key'})}</section><section><h3>Valori del record dimostrativo</h3><dl class="document-metadata"><div><dt>Provider</dt><dd>${escapeHTML(m.provider)}</dd></div><div><dt>Contesto demo</dt><dd>${m.context===null?'Non noto':fmt(m.context)+' token'}</dd></div><div><dt>Costo corrente</dt><dd>Non verificato</dd></div>${m.synthetic?`<div><dt>Input · USD/M · demo</dt><dd>${fmtPrice(m.priceInput)}</dd></div><div><dt>Output · USD/M · demo</dt><dd>${fmtPrice(m.priceOutput)}</dd></div>`:''}</dl></section></div></article>`;
 let content='';
 if(state.cardStatus==='loading')content=`<div class="readme-state" role="status" aria-live="polite"><div class="eyebrow">STATO DI CARICAMENTO · SIMULATO</div><h2>La scheda sta arrivando.</h2><p>La pagina e le azioni TALOS restano disponibili.</p><div class="skeleton-document" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>${button('Completa caricamento demo','card-retry',{ic:'check'})}</div>`;
 else if(state.cardStatus==='missing')content=`<div class="readme-state">${icon('document')}<h2>La scheda non è disponibile.</h2><p>Il modello resta nel catalogo. Puoi consultare file e compatibilità senza un README.</p>${sourceLink(source)}${button('Ripristina anteprima','card-retry',{kind:'ghost',ic:'refresh'})}</div>`;
 else if(state.cardStatus==='error')content=`<div class="readme-state" role="status">${icon('alert')}<h2>Non è stato possibile leggere la scheda.</h2><p>Errore simulato: non indica un problema del runtime o del modello installato.</p>${button('Riprova · demo','card-retry',{ic:'refresh'})}${sourceLink(source)}</div>`;
 else content=`${state.scenario==='offline'?`<div class="document-notice warning">${icon('info')}Rete assente · stai leggendo l’anteprima inclusa nel mockup, non una scheda aggiornata.</div>`:''}
 <nav class="readme-index" aria-label="Indice della scheda"><span>IN QUESTA SCHEDA</span>${[['overview','Panoramica'],['usage','Utilizzo'],['limits','Contesto e limiti'],['source','Fonte']].map(([id,label])=>`<button data-action="card-anchor" data-value="${id}">${label}</button>`).join('')}</nav>
 <div class="readme-body">
  ${source?.summary?renderQwenSummary(m,source):renderBaseCard(m,source)}
  <section class="document-section" aria-labelledby="readme-usage"><h3 id="readme-usage" tabindex="-1">Utilizzo nel laboratorio</h3><p class="editor-note">NOTA TALOS · NON FA PARTE DELLA SCHEDA DELL’AUTORE</p><p>Le indicazioni del repository e la configurazione effettiva sono due cose diverse. Qui puoi leggere la documentazione, controllare il file locale e preparare una prova prima di scegliere il modello.</p><div class="document-flow"><div><span>01</span><strong>Leggi la scheda</strong><p>Origine, istruzioni e limiti.</p></div><div><span>02</span><strong>Verifica il profilo</strong><p>File e risorse del dispositivo.</p></div><div><span>03</span><strong>Prova, poi scegli</strong><p>Nessun avvio implicito.</p></div></div><div class="document-code"><div>${icon('code')}Identità del profilo · esempio, non un comando</div><pre><code>${escapeHTML(JSON.stringify({modello:m.id,file:m.file,contesto_demo:8192},null,2))}</code></pre></div></section>
  <section class="document-section" aria-labelledby="readme-limits"><h3 id="readme-limits" tabindex="-1">Contesto e limiti</h3>${source?.summary?'<p>La scheda Qwen distingue 32.768 token nativi dall’estensione a 131.072 con YaRN e segnala possibili effetti sui testi brevi.</p>':'<p>Per modalità d’uso, requisiti e limitazioni consulta la documentazione del modello base. Questa anteprima non riproduce il README completo di Gemma.</p>'}<div class="document-callout">${icon('shield')}<div><strong>Una capacità dichiarata non è una verifica sul tuo PC.</strong><p>Memoria, quantizzazione e runtime vanno controllati in TALOS. I valori nella scheda Compatibilità sono fixture, non misure del tuo hardware.</p></div></div><p class="editor-note">NOTA TALOS</p><p>Non sono stati eseguiti benchmark o inferenze. Le sezioni lunghe, i blocchi di codice e le tabelle hanno spazio nella pagina; le valutazioni dell’autore non diventano automaticamente risultati del laboratorio.</p></section>
  <section class="document-section source-section" aria-labelledby="readme-source"><h3 id="readme-source" tabindex="-1">Fonte e provenienza</h3><p>Questa è ${source?.summary?'una sintesi italiana preparata per il mockup':'una composizione dimostrativa'}, non il README originale né una sincronizzazione live. Fonte consultata il 17 settembre 2026.</p><dl class="document-metadata"><div><dt>Repository di riferimento</dt><dd>${escapeHTML(source?.repo||'Non associato')}</dd></div><div><dt>Collegamento al file demo</dt><dd>Non verificato · nessun hash acquisito</dd></div><div><dt>Revisione del README</dt><dd>Non acquisita</dd></div></dl>${sourceLink(source,'Leggi la scheda originale su Hugging Face','button secondary source-button')}</section>
 </div>`;
 return `<article class="readme-surface" aria-label="Scheda del modello da Hugging Face · anteprima">${stateHeader}${content}</article>`;
}
function renderQwenSummary(m,source){
 return `<section class="document-section document-intro" aria-labelledby="readme-overview"><div class="document-kicker">MODEL CARD <span>/</span> ${escapeHTML(source.kind)}</div><h2 id="readme-overview" tabindex="-1">${escapeHTML(source.repo.split('/')[1])}</h2><p class="readme-lead">Un modello della famiglia Qwen3 per la generazione di testo, con modalità thinking e non-thinking. Questa versione distribuisce i pesi nel formato GGUF.</p><div class="document-tags">${badge('Text generation')}${badge('GGUF')}${badge('Apache-2.0')}${badge('Multilingue')}</div><h3>Il modello, in breve</h3><p>Secondo la scheda dell’autore, il modello supporta oltre 100 lingue e dialetti. Le due modalità di ragionamento possono essere richiamate attraverso le indicazioni del prompt.</p><dl class="architecture-strip"><div><dt>Parametri</dt><dd>${source.params}</dd></div><div><dt>Layer</dt><dd>${source.layers}</dd></div><div><dt>Contesto nativo</dt><dd>32.768 <small>token</small></dd></div></dl><p class="source-caption">Sintesi dalla scheda Qwen · dati dichiarati dall’autore, non misurati da TALOS. ${sourceLink(source,'Fonte')}</p></section>`;
}
function renderBaseCard(m,source){
 return `<section class="document-section document-intro" aria-labelledby="readme-overview"><div class="document-kicker">MODEL CARD <span>/</span> MODELLO BASE</div><h2 id="readme-overview" tabindex="-1">${escapeHTML(m.name)}</h2><p class="readme-lead">Una pagina per leggere la documentazione del modello senza comprimerla in un pannello laterale.</p><div class="document-tags">${badge('Anteprima di layout')}${badge('Fonte base, non file GGUF')}</div><h3>Documentazione e variante locale</h3><p>Il riferimento ${escapeHTML(source?.repo)} identifica la scheda del modello base. Non dimostra la provenienza del file GGUF dello scenario. La scheda originale non è inclusa: qui viene mostrata soltanto la struttura di lettura.</p>${sourceLink(source,'Apri la scheda del modello base')}</section>`;
}
export function renderModelFiles(m,state){
 const cloud=m.destination==='cloud';
 if(cloud)return `<section class="detail-secondary"><div class="subpage-heading"><div><h2>Un accesso, nessun GGUF.</h2><p>Il modello è raggiunto attraverso ${escapeHTML(m.provider)}.</p></div>${badge('Record demo')}</div><dl class="document-metadata"><div><dt>Identità</dt><dd>${escapeHTML(m.id)}</dd></div><div><dt>Credenziale</dt><dd>Gestita separatamente dal provider</dd></div><div><dt>Prezzo corrente</dt><dd>Non verificato</dd></div></dl>${button('Apri provider e accessi','providers-tab',{ic:'key'})}</section>`;
 return `<section class="detail-secondary"><div class="subpage-heading"><div><h2>Il file che userai, senza ambiguità.</h2><p>Un solo profilo dimostrativo. Questo non è l’elenco live del repository.</p></div>${badge((m.format||'Formato non noto')+' · demo')}</div>
 <article class="gguf-file"><div class="gguf-file-identity">${icon('document')}<div><h3>${escapeHTML(m.file||'Nessun file associato')}</h3><p>${escapeHTML(m.quantization||'Quantizzazione non nota')} <span>·</span> ${m.size===null?'Peso non noto':fmt(m.size)+' GiB'} nello scenario</p></div>${badge(m.installed?'Installato · demo':'Da scaricare',m.installed?'success':'muted',true)}</div><dl class="file-verification"><div><dt>Revisione repository</dt><dd>Non acquisita</dd></div><div><dt>Checksum SHA-256</dt><dd>Non verificato</dd></div><div><dt>Provenienza del file</dt><dd>Fixture TALOS</dd></div></dl><div class="gguf-file-actions">${m.installed?button('Rimuovi dallo scenario','remove-model',{kind:'danger-ghost',ic:'trash',data:`data-model="${m.id}"`,disabled:m.id===state.defaultId}):button('Scarica questo file · demo','download-model',{ic:'download',data:`data-model="${m.id}"`,disabled:!m.file||!m.format})}<span>${m.id===state.defaultId?'Scegli un altro predefinito prima di rimuoverlo.':'Nessun file reale viene modificato.'}</span></div></article>
 <div class="inline-notice">${icon('info')}<span>In integrazione, ogni variante avrà identità, dimensione e revisione proprie. Aprire la scheda non seleziona né scarica una quantizzazione diversa.</span></div></section>`;
}
export function renderModelCompatibility(m,state){
 const a=availability(m,state),cloud=m.destination==='cloud';
 return `<section class="detail-secondary"><div class="subpage-heading"><div><h2>${cloud?'Verifica prima il collegamento.':'La scheda descrive. TALOS verifica.'}</h2><p>Le informazioni dell’autore non sostituiscono un controllo del runtime.</p></div>${badge('SCENARIO DEMO')}</div>
 ${!cloud?`<div class="memory-wide ${m.fit==='incompatible'?'warning':''}"><div><span class="eyebrow">STIMA RAM · CONTESTO 8.192 TOKEN</span><strong>${m.required===null?'Non nota':fmt(m.required)} <small>/ 18,6 GiB disponibili nello scenario</small></strong></div><div class="fit-track"><span style="width:${Math.min(100,m.required/18.6*100)}%"></span></div><p>${m.required===null?'Dati insufficienti: la compatibilità non è deducibile.':m.fit==='incompatible'?'La stima supera il budget. Il download non rende il modello utilizzabile.':'La stima rientra nel budget dello scenario. Non è una garanzia di esecuzione sul tuo computer.'}</p></div>`:''}
 <dl class="compatibility-list"><div><dt>${cloud?'Provider':'Runtime locale'}</dt><dd>${escapeHTML(a.label)} ${badge('Simulato')}</dd></div><div><dt>Supporto strumenti</dt><dd>${m.tools?'Da catalogo demo':'Da verificare'}</dd></div><div><dt>${cloud?'Prezzo corrente':'GPU / VRAM'}</dt><dd>${cloud?'Non verificato':'Non rilevate'}</dd></div><div><dt>Inferenze eseguite</dt><dd>0</dd></div><div><dt>Passaggio automatico al cloud</dt><dd>Non autorizzato</dd></div></dl>
 <div class="inline-notice">${icon('shield')}<span>${cloud?'La scelta cloud richiede una conferma esplicita della destinazione dei dati.':'L’inferenza locale non rende automaticamente offline gli strumenti dell’agente.'}</span></div>${button(cloud?'Apri provider':'Apri sistema',cloud?'providers-tab':'system-tab',{ic:cloud?'key':'cpu'})}</section>`;
}

function renderSyntheticCard(m){
 const value=n=>n===null?'Non noto':fmt(n);
 return `<article class="readme-surface"><div class="readme-chrome"><span>${icon('document')}<strong>Scheda dimostrativa</strong></span>${badge('Modello fittizio')}</div><div class="readme-body"><div class="document-kicker">FIXTURE TALOS / RICERCA E FILTRI</div><h2>${escapeHTML(m.name)}</h2><p class="readme-lead">Questo modello è inventato per esercitare dimensioni, capacità e casi limite. Non è una scheda Hugging Face né un prodotto consigliato.</p><dl class="document-metadata"><div><dt>Parametri totali</dt><dd>${value(m.parametersB)}${m.parametersB===null?'':'B'}</dd></div><div><dt>Parametri attivi</dt><dd>${m.architecture==='moe'?value(m.activeParametersB)+'B':'Non separati / architettura densa o non nota'}</dd></div><div><dt>Architettura</dt><dd>${escapeHTML(m.architecture||'Non nota')}</dd></div><div><dt>Capacità demo</dt><dd>${m.capabilities===null?'Non note':escapeHTML(m.capabilities.join(', ')||'Nessuna dichiarata')}</dd></div><div><dt>Lingue demo</dt><dd>${m.languages===null?'Non note':escapeHTML(m.languages.join(', '))}</dd></div><div><dt>Contesto massimo demo</dt><dd>${value(m.context)}${m.context===null?'':' token'}</dd></div><div><dt>Provenienza</dt><dd>Fixture sintetica. Nessun README remoto, hash o misura hardware.</dd></div></dl><div class="document-callout">${icon('info')}<div><strong>La ricerca non modifica il profilo.</strong><p>Aprire una corrispondenza non scarica il file, non avvia il runtime e non cambia le nuove chat.</p></div></div></div></article>`;
}
