import {selectCatalog,parameterValue,validateCatalogFilters} from './catalog-engine.mjs';
import {renderCatalogControls,renderCatalogEmpty,catalogContext} from './catalog-controls.mjs';
import {availability,filterModels,escapeHTML,fmt,fmtPrice} from './domain.mjs';
import {icon,modelGlyph,button,badge,emptyState} from './ui.mjs';
import {renderModelPage} from './model-page.mjs';
export function renderModelLab(state) {
 if(state.detailId){const model=state.models.find(m=>m.id===state.detailId);if(model)return renderModelPage(model,state);}
 const current=state.models.find(m=>m.id===state.defaultId);
 const empty=state.scenario==='empty'||!current;
 return `<header class="page-heading"><div><div class="eyebrow">INTELLIGENZA, SOTTO CONTROLLO</div><h1 tabindex="-1" id="page-title">Laboratorio modelli</h1><p>Il modello giusto. La scelta resta tua.</p></div>${button('Aggiungi modello','add-model',{kind:'primary',ic:'plus',id:'add-model'})}</header>
 <section class="setup-band" aria-label="Configurazione dimostrativa"><div class="setup-current">${modelGlyph(empty?'qwen':current?.glyph||'qwen')}<div><span class="overline">MODELLO PER LE NUOVE CHAT</span><div class="setup-name">${empty?'Nessun modello scelto':escapeHTML(current?.name||'Nessuno')}${!empty?badge(current?.destination==='local'?'Locale':'Cloud',current?.destination==='local'?'success':'accent',true):''}</div><p>${empty?'Esplora il laboratorio, anche senza configurare un provider.':'Le chat già aperte non cambiano.'}</p></div></div><div class="setup-budget"><span class="overline">BUDGET RAM · SCENARIO DEMO</span><div class="budget-number">18,6 <span>GiB</span><small>su 32 GiB</small></div><div class="budget-track"><span></span></div></div><button class="setup-policy" data-action="privacy-info">${icon('shield')}<span>Nessun passaggio<br>automatico al cloud</span>${icon('chevron')}</button></section>
 <div class="lab-tabs" role="tablist" aria-label="Viste del laboratorio">${[['models','Modelli','models'],['providers','Provider','key'],['downloads','Download','download'],['system','Sistema','cpu']].map(([id,label,ic])=>`<button type="button" role="tab" id="tab-${id}" aria-controls="lab-panel" aria-selected="${state.tab===id}" tabindex="${state.tab===id?0:-1}" data-action="tab" data-value="${id}">${icon(ic)}${label}${id==='downloads'&&state.downloads.some(j=>['running','paused','error'].includes(j.status))?`<span class="tab-count">${state.downloads.filter(j=>['running','paused','error'].includes(j.status)).length}</span>`:''}</button>`).join('')}<span class="tab-end">${icon('info')}Dati dimostrativi</span></div>
 <section id="lab-panel" role="tabpanel" aria-labelledby="tab-${state.tab}" tabindex="0">${state.tab==='models'?renderCatalog(state):state.tab==='providers'?renderProviders(state):state.tab==='downloads'?renderDownloads(state):renderSystem(state)}</section>`;
}
export function renderCatalog(state) {
 const source=state.scenario==='empty'?[]:state.models;
 const models=selectCatalog(source,state.catalogFilters,catalogContext(state));
 const selected=models.find(m=>m.id===state.selectedId);
 return `${renderCatalogControls(state,source,models)}
 ${state.scenario==='offline'?`<div class="inline-notice warning">${icon('alert')}<span><strong>Rete assente nello scenario.</strong> I modelli locali restano consultabili; il cloud non è raggiungibile.</span></div>`:''}${state.scenario==='error'?`<div class="inline-notice danger">${icon('alert')}<span><strong>Il runtime locale non risponde.</strong> Catalogo e preferenze restano disponibili.</span>${button('Riprova','recover-runtime',{kind:'ghost',ic:'refresh'})}</div>`:''}
 ${!models.length?(state.scenario==='empty'?emptyState('Il tuo laboratorio comincia qui.','Esplora i modelli senza scegliere automaticamente un provider.','add-model','Esplora i modelli'):renderCatalogEmpty(state,source)): `<div class="catalog-layout catalog-full"><div class="model-list" aria-label="Catalogo modelli">${validateCatalogFilters(state.catalogFilters).sort==='catalog'?['local','cloud'].map(dest=>{const group=models.filter(m=>m.destination===dest);return group.length?`<div class="list-group-label">${icon(dest==='local'?'screen':'cloud')}<span>${dest==='local'?'SUL DISPOSITIVO':'VIA PROVIDER'}</span><span>${group.length}</span></div>${group.map(m=>renderModelRow(m,state,selected?.id===m.id)).join('')}`:'';}).join(''):models.map(m=>renderModelRow(m,state,selected?.id===m.id)).join('')}<div class="list-footnote">${icon('info')}Apri un modello per leggere la scheda completa. La scelta per le nuove chat non cambia.</div>${state.compare.length?`<div class="compare-bar"><span>${state.compare.length}/2 da confrontare</span>${button('Confronta','compare',{kind:'secondary',ic:'compare',disabled:state.compare.length!==2})}${button('Azzera','clear-compare',{kind:'ghost'})}</div>`:''}</div></div>`}`;
}
export function renderModelRow(m,state,selected) {
 const a=availability(m,state);const favorite=state.favorites.includes(m.id);const checked=state.compare.includes(m.id);
 return `<article data-catalog-model="${escapeHTML(m.id)}" class="model-row ${selected?'selected':''}"><button type="button" class="model-select" id="select-${m.id.replace(':','-')}" data-action="select-model" data-model="${m.id}" aria-label="Apri la scheda di ${escapeHTML(m.name)}">${modelGlyph(m.glyph)}<span class="model-row-copy"><span class="model-name">${escapeHTML(m.name)}${state.defaultId===m.id?'<span class="default-mark" title="Predefinito per le nuove chat">Predefinito</span>':''}</span><span class="model-meta"><span class="mobile-parameter">${parameterValue(m,state.catalogFilters.basis)===null?'Parametri non noti':fmt(parameterValue(m,state.catalogFilters.basis))+'B'} · </span>${escapeHTML(m.family)}<span>·</span>${m.destination==='local'?`${m.size===null?'Peso non noto':fmt(m.size)+' GiB'} · ${m.quantization||'Quantizzazione non nota'}`:escapeHTML(m.provider)+(m.priceInput!==null?' · input '+fmtPrice(m.priceInput)+' $/M · demo':' · prezzo non noto')}</span><span class="row-availability ${a.tone}"><span class="status-dot" aria-hidden="true"></span>${a.label}</span></span><span class="row-capacity"><strong>${parameterValue(m,state.catalogFilters.basis)===null?'Non noti':fmt(parameterValue(m,state.catalogFilters.basis))+'B'}</strong><small>parametri ${state.catalogFilters.basis==='active'?'attivi':'totali'}</small><span class="capacity-context">${m.context===null?'Contesto non noto':fmt(m.context)+' token'}</span></span>${icon('chevron')}</button><div class="row-tools"><button class="icon-button favorite ${favorite?'is-favorite':''}" data-action="favorite" data-model="${m.id}" aria-pressed="${favorite}" aria-label="${favorite?'Rimuovi':'Aggiungi'} ${escapeHTML(m.name)} ${favorite?'dai':'ai'} preferiti" title="Preferito">${icon('star')}</button><label class="compare-check" title="Confronta ${escapeHTML(m.name)}"><input type="checkbox" id="compare-${m.id.replace(':','-')}" data-compare="${m.id}" ${checked?'checked':''} aria-label="Confronta ${escapeHTML(m.name)}">${icon('compare')}</label></div></article>`;
}
export function renderProviders(state) {
 const s=state.providerStatus;const offline=state.scenario==='offline';
 return `<div class="subpage-heading"><div><h2 id="providers-title" tabindex="-1">Collegamenti, non scatole nere.</h2><p>Credenziale, configurazione e raggiungibilità sono tre fatti diversi.</p></div>${badge('Nessuna chiave reale','muted')}</div><div class="provider-grid"><article class="provider-card"><div class="provider-head">${modelGlyph('cloud')}<div><h3>OpenRouter</h3><p>Accesso ai modelli cloud</p></div>${badge(offline?'Offline':s==='connected'?'Verificato · demo':s==='testing'?'Verifica…':s==='denied'?'Accesso rifiutato':s==='unverified'?'Da verificare':'Da configurare',s==='connected'&&!offline?'success':s==='denied'?'danger':'warning',true)}</div><dl class="provider-facts"><div><dt>Credenziale</dt><dd>${s==='missing'?'Assente':'Esempio presente'}</dd></div><div><dt>Configurazione</dt><dd>Endpoint di esempio</dd></div><div><dt>Ultima prova</dt><dd>${offline?'Rete assente':s==='connected'?'Servizio raggiunto · simulato':s==='denied'?'Rifiutata · 401 simulato':s==='testing'?'In corso · simulata':'Non eseguita'}</dd></div></dl><div class="provider-actions">${button('Configura','configure-provider',{ic:'sliders'})}${button(s==='testing'?'Verifica in corso…':'Verifica accesso','probe-provider',{ic:'refresh',disabled:s==='testing'||s==='missing'})}</div>${s==='denied'?`<div class="inline-notice danger">${icon('alert')}<span>Credenziale rifiutata nello scenario. La configurazione non è stata cancellata.</span></div>`:''}</article><article class="provider-card local-card"><div class="provider-head">${modelGlyph('qwen')}<div><h3>llama.cpp</h3><p>Runtime locale</p></div>${badge(state.scenario==='error'?'Non raggiunto':'Locale · demo',state.scenario==='error'?'danger':'success',true)}</div><p>I modelli restano sul dispositivo. Non serve una chiave API per il runtime locale dello scenario.</p><div class="provider-facts"><div><span>Credenziale cloud</span><strong>Non richiesta</strong></div><div><span>Stato operativo</span><strong>Simulato</strong></div></div>${button('Apri sistema','system-tab',{ic:'cpu'})}</article></div><div class="inline-notice">${icon('shield')}<span><strong>Qui non inserire chiavi reali.</strong> Questa anteprima non contatta provider e non salva credenziali. Le destinazioni sono mostrate per valutarne l’esperienza.</span></div>`;
}
export function renderDownloads(state) {
 const labels={running:'Download simulato',paused:'In pausa',completed:'Completato · demo',cancelled:'Annullato',error:'Interrotto · rete assente'};
 return `<div class="subpage-heading"><div><h2 id="downloads-title" tabindex="-1">Ogni download, al suo posto.</h2><p>Avanzamento, pause e recupero senza perdere il contesto.</p></div>${button('Esplora modelli','add-model',{ic:'plus'})}</div>${!state.downloads.length?emptyState('Nessun download in coda.','Il prossimo modello può aspettare. Oppure puoi esplorare il catalogo di esempio.','add-model','Esplora il catalogo','download'):`<div class="download-list">${state.downloads.map(j=>`<article class="download-card"><div class="download-header">${modelGlyph('qwen')}<div><h3>${escapeHTML(j.name)}</h3><p>${labels[j.status]} · nessun file scaricato</p></div><strong>${j.progress}%</strong></div><progress value="${j.progress}" max="100" aria-label="Download simulato ${escapeHTML(j.name)}"></progress><div class="download-footer"><span>Le percentuali sono generate dal prototipo.</span><div>${j.status==='running'?button('Pausa','download-pause',{ic:'pause',data:`data-job="${j.id}"`}):['paused','error'].includes(j.status)?button('Riprendi','download-resume',{ic:'play',data:`data-job="${j.id}"`}):''}${['running','paused','error'].includes(j.status)?button('Annulla','download-cancel',{kind:'ghost',data:`data-job="${j.id}"`}):''}${j.status==='completed'?button('Vedi modello','show-downloaded',{ic:'arrow',data:`data-model="${j.modelId}"`}):''}</div></div></article>`).join('')}</div>`}`;
}
export function renderSystem(state) {
 return `<div class="subpage-heading"><div><h2 id="system-title" tabindex="-1">Il dispositivo, senza supposizioni.</h2><p>Distingui ciò che è misurato, stimato o ancora sconosciuto.</p></div>${badge('Hardware non rilevato','muted')}</div><div class="system-grid"><article class="system-card"><div class="section-heading"><h3>${icon('cpu')}Memoria di esempio</h3>${badge('Fixture')}</div><div class="system-value">18,6 <small>GiB</small></div><p>Budget allocabile su 32 GiB di RAM nello scenario.</p><div class="budget-track large-track"><span></span></div><dl class="model-facts"><div><dt>Origine</dt><dd>Fixture TALOS</dd></div><div><dt>Misura sul tuo PC</dt><dd>Non disponibile</dd></div><div><dt>GPU / VRAM</dt><dd>Non rilevate</dd></div></dl></article><article class="system-card"><div class="section-heading"><h3>${icon('activity')}Runtime locale</h3>${badge(state.scenario==='error'?'Errore demo':state.probe==='running'?'Verifica…':'Pronto · demo',state.scenario==='error'?'danger':'success',true)}</div><h3 class="runtime-name">llama.cpp</h3><p>Lo stato del prototipo non corrisponde a un processo avviato sul tuo computer.</p><dl class="model-facts"><div><dt>Indirizzo</dt><dd>Loopback · esempio</dd></div><div><dt>Ultima verifica reale</dt><dd>Mai eseguita</dd></div><div><dt>Inferenze eseguite</dt><dd>0</dd></div></dl>${button(state.probe==='running'?'Verifica simulata…':'Simula nuova verifica','probe-runtime',{ic:'refresh',disabled:state.probe==='running'})}</article></div><div class="inline-notice">${icon('info')}<span>In integrazione, il backend resta l’unica fonte dello stato. RAM libera, stime di caricamento e memoria occupata dal modello non sono la stessa misura.</span></div>`;
}
