import {icon,button,badge} from './ui.mjs';
import {escapeHTML} from './domain.mjs';
import {APPEARANCE_FIELDS,STUDIO_IDS,THEME_NAMES,APPEARANCE_DEFAULTS} from './appearance-domain.mjs';
const HELP={themePreset:'Scegli una delle 14 palette TALOS. La scena resta una scelta indipendente.',colorMode:'Chiaro, scuro oppure sincronizzato con il sistema operativo.',uiDensity:'Più respiro o più elementi: non cambia la dimensione dei controlli.',uiLanguage:'Lingua dei menu nel prodotto. La proposta di questa anteprima è in italiano.',uiFontScale:'Scala l’interfaccia senza cambiare il contenuto del lavoro.',chatFontScale:'Dimensione dei messaggi, indipendente dalla scala dell’interfaccia.',composerShape:'La forma del campo dove scrivi.',composerPlus:'Scegli come aprire gli strumenti di composizione.',messageStyle:'Separa i messaggi con sezioni o bolle.',streamingAnimation:'Preferenza conservata. Nel Desktop standalone l’hotfix di streaming rende il testo immediato.',windowPresentation:'Presentazione dei pannelli strumenti; non cambia la pagina dedicata del modello.',interfaceMotion:'Attiva le transizioni UI, senza prevalere sul movimento ridotto.',pauseWhenHidden:'La scena si ferma quando questa finestra non è visibile.',respectDataSaver:'Riduce il lavoro grafico quando il browser segnala il risparmio dati.',reducedMotion:'Ferma l’animazione, mantenendo la scena visibile. La preferenza del sistema prevale sempre.',backgroundMotion:'Spento all’inizio, come nel prodotto. Non aggiunge un velo alle pagine di impostazioni.',sceneOverride:'Atmosfera e palette possono essere scelte separatamente.',motionMode:'Off, immagine statica o renderer della scena.',motionQuality:'Qualità richiesta al renderer; la politica adattiva può ridurla.',motionProfile:'Predefinito, minimo o espressivo; i cursori restano conservati.',motionEasing:'Curva temporale delle transizioni.',immersiveHeader:'Riduce il peso visivo dell’intestazione della conversazione.',chatFullWidth:'Allarga lo spazio di lettura; la scheda modello non cambia.'};
export function appearanceField(f,p,{prefix=''}={}){
 const id=prefix+f.id,value=p[f.chiave];
 const note=HELP[f.chiave]|| (f.tipo==='range'?`Intervallo ${f.min}–${f.max}${f.unita}. Il valore si applica durante la regolazione.`:'Attiva questa famiglia di transizioni, quando il movimento è consentito.');
 const data=`id="${id}" data-appearance="${f.chiave}"`;
 const control=f.tipo==='select'?`<select ${data}>${f.opzioni.map(([v,label])=>`<option value="${v}" ${v===value?'selected':''}>${escapeHTML(label)}</option>`).join('')}</select>`:f.tipo==='checkbox'?`<input ${data} type="checkbox" role="switch" ${value?'checked':''}>`:`<input ${data} type="range" min="${f.min}" max="${f.max}" step="1" value="${value}" data-unit="${f.unita}">`;
 return `<div class="setting-row appearance-field" data-appearance-row="${f.id}"><div class="setting-copy"><label for="${id}">${escapeHTML(f.titolo)}</label><p id="${id}-help">${escapeHTML(note)}</p></div><div class="setting-control">${control.replace(' data-appearance=',` aria-describedby="${id}-help" data-appearance=`)}</div></div>`;
}
export function renderSettings(state) {
 const p=state.appearance||APPEARANCE_DEFAULTS,theme=THEME_NAMES.find(t=>t[0]===p.themePreset)?.[1]||'Calm';
 const fields=APPEARANCE_FIELDS.filter(f=>!STUDIO_IDS.includes(f.id));
 const groups=[['design','Interfaccia e conversazione'],['sfondo','Accessibilità e risorse'],['animazioni','Movimento dell’interfaccia'],['desktop','Desktop'],['chat','Spazio di lettura']];
 return `<header class="page-heading"><div><div class="eyebrow">IL TUO SPAZIO</div><h1 tabindex="-1" id="page-title">Aspetto e movimento</h1><p>Il tema è solo l’inizio. Ogni preferenza resta al suo posto.</p></div>${badge('40 controlli · 14 temi','muted',true)}</header>
 <section class="theme-launcher"><div class="theme-launcher-swatch" aria-hidden="true"><span></span><i></i><i></i></div><div><div class="eyebrow">IL TUO TEMA</div><h2 id="current-theme-name">${theme}</h2><p>Palette, modalità colore, scene e tutte le regolazioni dello sfondo.</p></div>${button('Temi e atmosfere','open-theme-studio',{kind:'primary',ic:'sun'})}</section>
 <div class="settings-layout"><div class="settings-main">${groups.map(([id,label],i)=>{const list=fields.filter(f=>f.gruppo===id);return list.length?`<section class="settings-section appearance-group" aria-labelledby="group-${id}"><div class="section-heading"><h2 id="group-${id}">${label}</h2><span class="text-caption">${list.length} CONTROLLI</span></div>${i===2?`<details class="appearance-details" ${state.motionAdvanced?'open':''}><summary>Profilo e regolazioni avanzate</summary>${list.map(f=>appearanceField(f,p)).join('')}</details>`:list.map(f=>appearanceField(f,p)).join('')}</section>`:'';}).join('')}
 <div class="settings-bottom"><p>${icon('shield')}Questa anteprima non scrive nelle preferenze TALOS.</p>${button('Ripristina solo movimento','reset-appearance-motion',{kind:'ghost',ic:'refresh'})}${button('Ripristina aspetto','reset-prefs',{kind:'ghost'})}</div></div>
 <aside class="appearance-preview" aria-label="Anteprima dal vivo"><div class="eyebrow">ANTEPRIMA DEL TEMA</div>${renderAppearancePreview(p)}<div class="preview-note">${icon('check')}Palette dal foglio temi del prodotto.</div><div class="quiet-note"><strong>Un controllo, una preferenza.</strong><p>La pagina espone tutte le opzioni attuali. Nel prodotto, i controlli custom usano il percorso di salvataggio esistente.</p><p>Qui lingua, layout degli strumenti e streaming sono illustrati dal campione, non collegati a un agente.</p></div></aside></div>`;
}
export function renderAppearancePreview(p){return `<div class="preview-window theme-live-preview" data-preview-scene><div class="preview-chrome"><span></span><span></span><span></span><small>TALOS</small></div><div class="preview-body"><div class="preview-date">${p.uiLanguage==='en'?'YOUR NEXT PROJECT':'IL TUO PROSSIMO PROGETTO'}</div><h3>${p.uiLanguage==='en'?'Room for ideas.':'Spazio alle idee.'}</h3><p>${p.uiLanguage==='en'?'Your space, your pace.':'Meno rumore. Più attenzione al tuo lavoro.'}</p><div class="preview-message">${p.uiLanguage==='en'?'Where do we start?':'Da dove cominciamo?'}</div><div class="preview-answer">${p.uiLanguage==='en'?'One thing at a time.':'Una cosa alla volta.'}<br>${p.uiLanguage==='en'?'With the context you need.':'Con tutto il contesto che serve.'}</div><div class="preview-composer"><button type="button" data-action="preview-composer-plus" aria-label="Apri strumenti nell’anteprima">+</button><span>${p.uiLanguage==='en'?'Write a message…':'Scrivi un messaggio…'}</span>${icon('arrow')}</div><div class="preview-tools" hidden></div></div><div class="scene-caption" data-scene-caption>Scena spenta</div></div>`;}
export function renderThemeStudio(state){const p=state.appearance;return `<p class="studio-intro">Un’atmosfera, non un altro spazio di lavoro. Le scelte si applicano subito; chiudere non le annulla.</p><div class="studio-layout"><div><div class="studio-theme-grid" role="radiogroup" aria-label="Tema TALOS">${THEME_NAMES.map(([id,name])=>`<button type="button" class="studio-theme ${p.themePreset===id?'selected':''}" role="radio" aria-checked="${p.themePreset===id}" tabindex="${p.themePreset===id?0:-1}" data-theme-choice="${id}" style="--swatch-accent:var(--swatch-${id});"><span class="studio-theme-swatch" aria-hidden="true"><i></i><i></i><i></i></span><span>${name}</span><span class="studio-theme-tick" aria-hidden="true">${p.themePreset===id?'✓':''}</span></button>`).join('')}</div><div class="studio-fields">${APPEARANCE_FIELDS.filter(f=>STUDIO_IDS.includes(f.id)).map(f=>appearanceField(f,p)).join('')}</div></div><aside class="studio-preview"><div class="eyebrow">ANTEPRIMA DAL VIVO</div>${renderAppearancePreview(p)}<p class="form-hint">Scene del prodotto, non un’immagine statica. Movimento ridotto e risparmio dati hanno priorità.</p>${button('Ripristina solo movimento','reset-appearance-motion',{kind:'ghost',ic:'refresh'})}</aside></div>`;}
