import type {CliPaths} from '../paths.ts';
import type {EffectiveConfig,TalosCliConfig} from './types.ts';
import {readConfigScope,replaceConfigScope} from './load.ts';
export type ConfigScope='user'|'project'|'project-user';
function parts(path:string){const p=path.split('.').filter(Boolean);if(!p.length||p.some(x=>!/^[A-Za-z][A-Za-z0-9_-]*$/u.test(x)))throw new Error('CONFIG_PATH_INVALID');return p;}
export function configGet(value:unknown,path:string):unknown{let cursor:any=value;for(const p of parts(path)){if(!cursor||typeof cursor!=='object'||Array.isArray(cursor)||!Object.hasOwn(cursor,p))throw new Error('CONFIG_PATH_NOT_FOUND');cursor=cursor[p];}return structuredClone(cursor);}
function setAt(root:Record<string,unknown>,path:string,value:unknown){const ps=parts(path);let c=root;for(const p of ps.slice(0,-1)){const old=c[p];if(old===undefined)c[p]={};else if(!old||typeof old!=='object'||Array.isArray(old))throw new Error('CONFIG_PATH_CONFLICT');c=c[p] as Record<string,unknown>;}c[ps.at(-1)!]=structuredClone(value);}
function unsetAt(root:Record<string,unknown>,path:string){const ps=parts(path);const stack:Array<[Record<string,unknown>,string]>=[];let c=root;for(const p of ps.slice(0,-1)){if(!c[p]||typeof c[p]!=='object'||Array.isArray(c[p]))return;stack.push([c,p]);c=c[p] as Record<string,unknown>;}delete c[ps.at(-1)!];for(let i=stack.length-1;i>=0;i--){const [parent,key]=stack[i]!;const node=parent[key];if(node&&typeof node==='object'&&!Array.isArray(node)&&Object.keys(node).length===0)delete parent[key];else break;}}
export async function configSet({paths,projectRoot,scope,path,value}:{paths:CliPaths;projectRoot:string;scope:ConfigScope;path:string;value:unknown}){const current=await readConfigScope({paths,projectRoot,scope});const next=structuredClone(current) as Record<string,unknown>;setAt(next,path,value);await replaceConfigScope({paths,projectRoot,scope,value:next as TalosCliConfig});}
export async function configUnset({paths,projectRoot,scope,path}:{paths:CliPaths;projectRoot:string;scope:ConfigScope;path:string}){const current=await readConfigScope({paths,projectRoot,scope});const next=structuredClone(current) as Record<string,unknown>;unsetAt(next,path);await replaceConfigScope({paths,projectRoot,scope,value:next as TalosCliConfig});}
function leaves(v:unknown,prefix=''):Array<{path:string;value:unknown}>{if(v&&typeof v==='object'&&!Array.isArray(v)){return Object.entries(v as Record<string,unknown>).flatMap(([k,x])=>leaves(x,prefix?`${prefix}.${k}`:k));}return prefix?[{path:prefix,value:v}]:[];}
export function configOrigins(effective:EffectiveConfig){return leaves(effective.value).map(row=>({...row,origin:effective.origins.get(row.path)??effective.origins.get(row.path.split('.')[0]!)??'default'}));}
