import {join} from 'node:path';import {readFile} from 'node:fs/promises';import type {CommandContext} from './context.ts';import {assertNoUnknownOptions,takeOption,writeValue} from './context.ts';import {importTalosModule} from '../runtime/repo.ts';
import {createMemoryFacade,type MemoryKind} from '../services/memory-facade.ts';
import {createNotesFacade,type NoteTargetKind} from '../services/notes-facade.ts';
import {createTaskBoardFacade,type TaskPriority,type TaskStatus} from '../services/task-board-facade.ts';
import {createLibraryFacade} from '../services/library-facade.ts';
import {createForgeFacade} from '../services/forge-facade.ts';
const clean=(v:any):any=>{if(Array.isArray(v))return v.map(clean);if(v&&typeof v==='object'){const o:any={};for(const[k,x]of Object.entries(v)){if(/percorso|path/iu.test(k))continue;o[k]=clean(x);}return o;}return v;};
function req(args:string[],what:string){const v=args.shift();if(!v)throw new Error(`${what}_REQUIRED`);return v;}
export async function runNotesCommand(ctx:CommandContext,args0:string[]){const a=[...args0],op=a.shift()??'list';const notes=createNotesFacade({projectRoot:ctx.projectRoot,paths:ctx.paths,repoRoot:ctx.repoRoot});let r:any;if(op==='list'){assertNoUnknownOptions(a);const x=await notes.list();r=x.state==='ready'?x.legacyRows:x;}else if(op==='add'){const title=req(a,'TITLE'),body=req(a,'BODY');assertNoUnknownOptions(a);r=(await notes.add({title,content:body})).legacy;}else if(op==='update'){const id=req(a,'ID');const title=takeOption(a,'--title'),content=takeOption(a,'--body');assertNoUnknownOptions(a);r=(await notes.update(id,{...(title!==undefined?{title}:{}),...(content!==undefined?{content}:{})})).legacy;}else if(op==='delete'){const id=req(a,'ID');assertNoUnknownOptions(a);r=(await notes.delete(id)).legacy;}else if(op==='link'||op==='unlink'){const noteId=req(a,'NOTE_ID'),targetKind=req(a,'TARGET_KIND') as NoteTargetKind,targetId=req(a,'TARGET_ID');assertNoUnknownOptions(a);r=op==='link'?await notes.link(noteId,targetKind,targetId):await notes.unlink(noteId,targetKind,targetId);}else throw new Error(`Unsupported notes operation: ${op}`);writeValue(ctx,clean(r));return 0;}
export async function runTasksCommand(ctx:CommandContext,args0:string[]){const a=[...args0],op=a.shift()??'list';const tasks=createTaskBoardFacade({projectRoot:ctx.projectRoot,paths:ctx.paths,repoRoot:ctx.repoRoot});let r:any;if(op==='list'){assertNoUnknownOptions(a);const x=await tasks.list();r=x.state==='ready'?x.legacyRows:x;}else if(op==='add'){const title=req(a,'TITLE'),description=req(a,'DESCRIPTION'),priority=(takeOption(a,'--priority')??'normal') as TaskPriority;assertNoUnknownOptions(a);r=(await tasks.add({title,description,priority})).legacy;}else if(op==='update'){const id=req(a,'ID');const title=takeOption(a,'--title'),description=takeOption(a,'--description'),priority=takeOption(a,'--priority') as TaskPriority|undefined;assertNoUnknownOptions(a);r=(await tasks.update(id,{...(title!==undefined?{title}:{}),...(description!==undefined?{description}:{}),...(priority!==undefined?{priority}:{})})).legacy;}else if(op==='complete'){const id=req(a,'ID'),status=(a.shift()??'done') as TaskStatus;assertNoUnknownOptions(a);r=(await tasks.complete(id,status)).legacy;}else if(op==='delete'){const id=req(a,'ID');assertNoUnknownOptions(a);r=(await tasks.delete(id)).legacy;}else if(op==='depend'||op==='undepend'){const id=req(a,'TASK_ID'),target=req(a,'DEPENDENCY_TASK_ID');assertNoUnknownOptions(a);r=op==='depend'?await tasks.depend(id,target):await tasks.undepend(id,target);}else if(op==='evidence'||op==='unevidence'){const id=req(a,'TASK_ID'),sessionId=req(a,'SESSION_ID');assertNoUnknownOptions(a);r=op==='evidence'?await tasks.addEvidence(id,sessionId):await tasks.removeEvidence(id,sessionId);}else if(op==='assign'||op==='unassign'){const id=req(a,'TASK_ID'),sessionId=req(a,'AGENT_SESSION_ID');assertNoUnknownOptions(a);r=op==='assign'?await tasks.assignAgent(id,sessionId):await tasks.unassignAgent(id,sessionId);}else if(op==='schedule'||op==='unschedule'){const id=req(a,'TASK_ID'),automationId=req(a,'AUTOMATION_ID');assertNoUnknownOptions(a);r=op==='schedule'?await tasks.attachSchedule(id,automationId):await tasks.detachSchedule(id,automationId);}else throw new Error(`Unsupported tasks operation: ${op}`);writeValue(ctx,clean(r));return 0;}
export async function runMemoryCommand(ctx:CommandContext,args0:string[]){const a=[...args0],op=a.shift()??'list';const memory=createMemoryFacade({projectRoot:ctx.projectRoot,paths:ctx.paths,repoRoot:ctx.repoRoot});let r:any;if(op==='list'){assertNoUnknownOptions(a);const x=await memory.list();r=x.state==='ready'?x.legacyRows:x;}else if(op==='search'){const query=req(a,'QUERY');assertNoUnknownOptions(a);const x=await memory.search(query);r=x.state==='ready'?x.legacy:x;}else if(op==='add'){const title=req(a,'TITLE'),content=req(a,'CONTENT'),kind=(takeOption(a,'--kind')??'preference') as MemoryKind;assertNoUnknownOptions(a);r=(await memory.add({title,content,kind})).legacy;}else if(op==='update'){const id=req(a,'ID'),title=takeOption(a,'--title'),content=takeOption(a,'--content'),kind=takeOption(a,'--kind') as MemoryKind|undefined;assertNoUnknownOptions(a);r=(await memory.update(id,{...(title!==undefined?{title}:{}),...(content!==undefined?{content}:{}),...(kind!==undefined?{kind}:{})})).legacy;}else if(op==='delete'){const id=req(a,'ID');assertNoUnknownOptions(a);r=(await memory.delete(id)).legacy;}else throw new Error(`Unsupported memory operation: ${op}`);writeValue(ctx,clean(r));return 0;}
export async function runLibraryCommand(ctx:CommandContext,args0:string[]){const a=[...args0],op=a.shift()??'list';const library=createLibraryFacade({projectRoot:ctx.projectRoot,paths:ctx.paths,repoRoot:ctx.repoRoot});let r:any;if(op==='list'){assertNoUnknownOptions(a);const x=await library.list();r=x.state==='ready'?x.legacyRows:x;}else if(op==='search'){const query=req(a,'QUERY');assertNoUnknownOptions(a);r=(await library.search(query)).legacy;}else if(op==='read'){const id=req(a,'ID');assertNoUnknownOptions(a);r=(await library.read(id)).legacy;}else if(op==='preview'){const id=req(a,'ID');assertNoUnknownOptions(a);r=await library.preview(id);}else if(op==='duplicates'){const id=req(a,'ID');assertNoUnknownOptions(a);r=await library.duplicates(id);}else if(op==='context-ref'){const id=req(a,'ID');assertNoUnknownOptions(a);r=await library.prepareContextReference(id);}else if(op==='import'){const file=req(a,'FILE');assertNoUnknownOptions(a);r=await library.importFile(file);}else if(op==='export'){const id=req(a,'ID'),out=takeOption(a,'--out');assertNoUnknownOptions(a);if(!out)throw new Error('LIBRARY_EXPORT_OUT_REQUIRED');r=(await library.exportFile(id,out)).legacy;}else if(op==='rename'){const id=req(a,'ID'),name=req(a,'NAME');assertNoUnknownOptions(a);r=(await library.rename(id,name)).legacy;}else if(op==='delete'){const id=req(a,'ID');assertNoUnknownOptions(a);r=(await library.delete(id)).legacy;}else throw new Error(`Unsupported library operation: ${op}`);writeValue(ctx,clean(r));return 0;}
export async function runForgeCommand(ctx:CommandContext,args0:string[]){
  const a=[...args0],op=a.shift()??'list',forgeRoot=join(ctx.paths.dataRoot,'forge');const base=createForgeFacade({forgeRoot,repoRoot:ctx.repoRoot});let r:any;
  const packageFrom=async()=>JSON.parse(await readFile(req(a,'PACKAGE_FILE'),'utf8'));
  const owner=async(sessionId:string)=>{const rc=await ctx.createRuntimeContext({projectRoot:ctx.projectRoot,paths:ctx.paths,repoRoot:ctx.repoRoot,model:ctx.invocation.model??'openai:gpt-5-mini',environmentKeys:'consent'});await rc.registry?.ripristina?.();return createForgeFacade({forgeRoot,repoRoot:ctx.repoRoot},{registry:rc.registry});};
  if(op==='list'){assertNoUnknownOptions(a);const x=await base.list();r=x.state==='ready'?x.rows:x;}
  else if(op==='inspect'){const id=req(a,'ID');assertNoUnknownOptions(a);r=await base.read(id);}
  else if(op==='validate'){const pkg=await packageFrom();assertNoUnknownOptions(a);r=base.validatePackage(pkg);}
  else if(op==='scan'){const pkg=await packageFrom();assertNoUnknownOptions(a);r=await base.scanPackage(pkg);}
  else if(op==='simulate'){const pkg=await packageFrom();assertNoUnknownOptions(a);r=await base.analyzePackage(pkg);}
  else if(op==='install'){const session=takeOption(a,'--session'),pkg=await packageFrom();assertNoUnknownOptions(a);if(!session)throw new Error('FORGE_SESSION_REQUIRED');r=await (await owner(session)).installPackage(session,pkg);}
  else if(op==='versions'){const id=req(a,'ID'),session=takeOption(a,'--session');assertNoUnknownOptions(a);if(!session)throw new Error('FORGE_SESSION_REQUIRED');r=await (await owner(session)).versions(session,id);}
  else if(op==='rollback'){const id=req(a,'ID'),revision=Number(req(a,'REVISION')),session=takeOption(a,'--session');assertNoUnknownOptions(a);if(!Number.isSafeInteger(revision)||revision<1)throw new Error('FORGE_REVISION_INVALID');if(!session)throw new Error('FORGE_SESSION_REQUIRED');r=await (await owner(session)).rollback(session,id,revision);}
  else if(op==='enable'||op==='disable'){
    const id=req(a,'ID'),session=takeOption(a,'--session');assertNoUnknownOptions(a);
    if(session)r=await (await owner(session)).setEnabled(session,id,op==='enable');
    else{const m:any=await importTalosModule(ctx.repoRoot,'tool-forge-store.mjs');r=await m.abilitaToolForgiato({cartella:forgeRoot,id,abilitato:op==='enable'});}
  }else throw new Error(`Unsupported forge operation: ${op}`);
  writeValue(ctx,clean(r));return 0;
}
