import { t as traduci, tn, linguaCorrenteDiT } from './lingua.js';
import { testoDelCampo, nomeDelFornitore, esecuzioneDelFornitore } from './testo-server.js'; // K4a: i dettagli che il server manda come dati, nella lingua corrente
/* Date nella lingua dell'interfaccia (italiano → it-IT, inglese → en-US), letta a ogni uso. */
const localeUI=()=>(linguaCorrenteDiT()==='en'?'en-US':'it-IT');
// 05/9 Fase 2: Doctor; il grado di certezza segue il dato, non la sua presenza.
/* ⛔ Le parole della gravità sono funzioni: si leggono a ogni uso e seguono il cambio di lingua. */
const GRAVITA={danger:()=>traduci('varie.doctor.severity.danger'),warning:()=>traduci('varie.doctor.severity.warning'),info:()=>traduci('varie.doctor.severity.info'),success:()=>traduci('varie.doctor.severity.ok')};
const ORDINE={danger:0,warning:1,info:2,success:3};
const oggetto=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const testo=v=>typeof v==='string'?v:'';
function valida(r){
 const errore=()=>{throw new Error(traduci('varie.doctor.error.invalidResponse'));};
 if(!oggetto(r)||!['chiaveApi','git','naviga'].every(k=>typeof r[k]==='boolean')||!['desktop','wsl2','none'].includes(r.shell))errore();
 const tipi={labs:{accesi:'array'},ricercaWeb:{fonte:'string',pronta:'boolean'},cartelleProgetto:{disponibili:'boolean',conteggio:'number'},providers:{storeAvailable:'boolean',items:'array'},ownerRuntime:{configurato:'boolean',pronto:'boolean'},catalogoTask:{disponibile:'boolean'},sessioniPersistenza:{corrotte:'array'}};
 for(const [k,shape] of Object.entries(tipi)){if(!(k in r))continue;if(!oggetto(r[k]))errore();for(const [f,t] of Object.entries(shape)){const v=r[k][f];if(t==='array'?!Array.isArray(v):typeof v!==t||(t==='number'&&(!Number.isFinite(v)||v<0)))errore();}if('dettaglio' in r[k]&&typeof r[k].dettaglio!=='string')errore();}
 if(r.labs&&!r.labs.accesi.every(v=>typeof v==='string'))errore();
 if(r.providers&&!r.providers.items.every(p=>oggetto(p)&&typeof p.id==='string'&&typeof p.label==='string'&&typeof p.keyConfigured==='boolean'))errore();
 const s=r.sessioniPersistenza;if(s){if(!s.corrotte.every(v=>typeof v==='string'))errore();if('scartate'in s&&(!Array.isArray(s.scartate)||!s.scartate.every(v=>oggetto(v)&&typeof v.sessionId==='string'&&typeof v.motivo==='string'&&(!('dettaglio'in v)||typeof v.dettaglio==='string'))))errore();if('ultimaLettura'in s&&(!oggetto(s.ultimaLettura)||!['ripristinate','totali'].every(k=>Number.isInteger(s.ultimaLettura[k])&&s.ultimaLettura[k]>=0)))errore();}
}
export function controlliDoctor(r){
 valida(r);const c=[];const add=(id,titolo,gravita,...righe)=>c.push({id,titolo,gravita,righe:righe.flat().filter(Boolean)});const ignoto=(id,titolo)=>add(id,titolo,'info',traduci('varie.doctor.notObserved'));
 add('chiave',traduci('varie.doctor.check.apiKey.title'),r.chiaveApi?'info':'warning',r.chiaveApi?traduci('varie.doctor.check.apiKey.configured'):traduci('varie.doctor.check.apiKey.missing'));
 add('shell',traduci('varie.doctor.check.shell.title'),r.shell==='none'?'danger':r.shell==='wsl2'?'success':'info',r.shell==='none'?traduci('varie.doctor.check.shell.none'):r.shell==='wsl2'?traduci('varie.doctor.check.shell.wsl2'):traduci('varie.doctor.check.shell.desktop'));
 add('git','Git',r.git?'success':'warning',r.git?traduci('varie.doctor.check.git.ok'):traduci('varie.doctor.check.git.bad'));
 add('browser',traduci('varie.doctor.check.browser.title'),r.naviga?'info':'warning',r.naviga?traduci('varie.doctor.check.browser.ok'):traduci('varie.doctor.check.browser.bad'));
 if(r.ownerRuntime)add('runtime',traduci('varie.doctor.check.runtime.title'),r.ownerRuntime.pronto?'success':'warning',r.ownerRuntime.configurato?traduci('varie.doctor.check.runtime.configured'):traduci('varie.doctor.check.runtime.notConfigured'),testoDelCampo(r.ownerRuntime,'dettaglio')|| (r.ownerRuntime.pronto?traduci('varie.doctor.check.runtime.ready'):traduci('varie.doctor.check.runtime.notReady')));else ignoto('runtime',traduci('varie.doctor.check.runtime.title'));
 if(r.catalogoTask)add('catalogo',traduci('varie.doctor.check.catalog.title'),r.catalogoTask.disponibile?'success':'warning',testoDelCampo(r.catalogoTask,'dettaglio')||(r.catalogoTask.disponibile?traduci('varie.doctor.check.catalog.available'):traduci('varie.doctor.check.catalog.unavailable')));else ignoto('catalogo',traduci('varie.doctor.check.catalog.title'));
 if(r.cartelleProgetto)add('cartelle',traduci('varie.doctor.check.folders.title'),r.cartelleProgetto.disponibili?'success':'warning',tn('varie.doctor.check.folders.allowedOne','varie.doctor.check.folders.allowedMany',r.cartelleProgetto.conteggio),testoDelCampo(r.cartelleProgetto,'dettaglio'));else ignoto('cartelle',traduci('varie.doctor.check.folders.title'));
 if(r.ricercaWeb)add('ricerca',traduci('varie.doctor.check.search.title'),r.ricercaWeb.pronta||r.ricercaWeb.fonte==='off'?'info':'warning',testoDelCampo(r.ricercaWeb,'etichetta')||r.ricercaWeb.fonte,testoDelCampo(r.ricercaWeb,'dettaglio'),traduci('varie.doctor.check.search.note'));else ignoto('ricerca',traduci('varie.doctor.check.search.title'));
 if(r.providers)add('fornitori',traduci('varie.doctor.check.providers.title'),r.providers.storeAvailable?'info':'warning',r.providers.storeAvailable?traduci('varie.doctor.check.providers.keychainAvailable'):traduci('varie.doctor.check.providers.keychainUnavailable'),r.providers.items.map(p=>nomeDelFornitore(p)+': '+(p.keyConfigured?traduci('varie.doctor.check.providers.keyConfigured'):p.requiresKey===false?traduci('varie.doctor.check.providers.keyOptional'):traduci('varie.doctor.check.providers.keyMissing'))+(testo(p.execution)?' · '+esecuzioneDelFornitore(p.execution): '')), traduci('varie.doctor.check.providers.note'));else ignoto('fornitori',traduci('varie.doctor.check.providers.title'));
 if(r.labs)add('labs',traduci('varie.doctor.check.labs.title'),'info',testoDelCampo(r.labs,'dettaglio')||traduci('varie.doctor.check.labs.on',{list:r.labs.accesi.join(', ')||traduci('varie.doctor.check.labs.none')}));else ignoto('labs',traduci('varie.doctor.check.labs.title'));
 if(r.sessioniPersistenza){const s=r.sessioniPersistenza,scarti=s.scartate||[],nonElencate=s.corrotte.filter(id=>!scarti.some(v=>v.sessionId===id));add('sessioni',traduci('varie.doctor.check.sessions.title'),s.corrotte.length||scarti.some(v=>['corrotta','lettura-fallita'].includes(v.motivo))?'danger':scarti.length?'warning':'success',testoDelCampo(s,'dettaglio')||(s.ultimaLettura?traduci('varie.doctor.check.sessions.restored',{restored:s.ultimaLettura.ripristinate,total:s.ultimaLettura.totali}):traduci('varie.doctor.check.sessions.notObserved')),scarti.map(v=>v.sessionId+' · '+v.motivo+(v.dettaglio?' · '+v.dettaglio:'')),nonElencate.map(id=>traduci('varie.doctor.check.sessions.corrupt',{id})));}else ignoto('sessioni',traduci('varie.doctor.check.sessions.title'));
 return c.sort((a,b)=>ORDINE[a.gravita]-ORDINE[b.gravita]);
}
export function contaGravitaDoctor(voci){const n={success:0,info:0,warning:0,danger:0};for(const v of voci)n[v.gravita]++;return n;}
function nodo(doc,tag,classe,valore){const e=doc.createElement(tag);if(classe)e.className=classe;if(valore!==undefined)e.textContent=valore;return e;}
export function creaCheckCard(voce,opzioni={}){const d=opzioni.document||globalThis.document;const card=nodo(d,'div','talos-card talos-check-card'+(voce.gravita==='success'?'':' talos-check-card--'+voce.gravita));card.dataset.c='CheckCard';card.dataset.doctorId=voce.id;const stripe=nodo(d,'span','talos-check-card__stripe');stripe.setAttribute('aria-hidden','true');const body=nodo(d,'div','talos-check-card__body');const title=nodo(d,'div','talos-check-card__title',GRAVITA[voce.gravita]()+' · '+voce.titolo);body.append(title,...voce.righe.map(r=>nodo(d,'p','',r)));card.append(stripe,body);return card;}
const schermi=new WeakMap();
export function aggiornaDoctor(s,risultato,opzioni={}){
 let st=schermi.get(s);if(!st){st={};schermi.set(s,st);s.querySelector('[data-doctor-refresh]').addEventListener('click',()=>st.opzioni.onRicontrolla?.());s.querySelector('[data-doctor-export]').addEventListener('click',()=>{if(st.risultato&&!st.opzioni.caricamento)st.opzioni.onEsporta?.();});}st.opzioni=opzioni;st.risultato=risultato;
 const loading=!!opzioni.caricamento,errore=opzioni.errore||'',voci=risultato?controlliDoctor(risultato):[],n=contaGravitaDoctor(voci);const q=sel=>s.querySelector(sel);
 q('[data-doctor-refresh]').disabled=loading;q('[data-doctor-refresh]').textContent=loading?traduci("varie.doctor.refresh.checking"):traduci("varie.doctor.refresh.checkAgain");q('[data-doctor-export]').disabled=!risultato||loading;
 q('[data-doctor-tempo]').textContent=opzioni.ricevutoAlle?traduci('varie.doctor.time.received', { when: new Intl.DateTimeFormat(localeUI(),{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Rome'}).format(new Date(opzioni.ricevutoAlle)) }):traduci("varie.doctor.time.notRun");
 q('[data-doctor-esito]').textContent=loading?traduci('varie.doctor.summary.checking'):risultato?((p)=>errore?traduci('varie.doctor.summary.resultKept',p):traduci('varie.doctor.summary.result',p))({ count: tn('varie.doctor.checks.one','varie.doctor.checks.many',voci.length), review: n.warning+n.danger }):traduci("varie.doctor.summary.noResults");
 q('[data-doctor-errore]').textContent=errore;q('[data-doctor-errore]').hidden=!errore;q('[data-doctor-counts]').hidden=!risultato;
 for(const [k,v] of Object.entries(n))q('[data-doctor-count='+k+']').textContent=String(v);
 const lista=q('[data-doctor-list]');lista.setAttribute('aria-busy',String(loading));lista.replaceChildren(...voci.map(v=>creaCheckCard(v,{document:s.ownerDocument})));
}
