// 05/9 Fase 2: configurazione ricerca, dentro Impostazioni.
import { t as traduci, tn } from './lingua.js';
import { testoDelCampo } from './testo-server.js'; // K4a: il nome della fonte arriva dal server con la sua chiave
const INDIRIZZO_ESEMPIO = 'https://search.example.org';
const IDS=['duckduckgo','tavily','brave','searxng','custom'];
/* ⛔ Le note si leggono a ogni uso (getter), non alla creazione del modulo: seguono il cambio di lingua. */
const NOTE={get duckduckgo(){return traduci('sezioni.searchSource.note.duckduckgo');},get tavily(){return traduci('sezioni.searchSource.note.tavily');},get brave(){return traduci('sezioni.searchSource.note.brave');},get searxng(){return traduci('sezioni.searchSource.note.searxng');},get custom(){return traduci('sezioni.searchSource.note.custom');},get off(){return traduci('sezioni.searchSource.note.off');}};
const LINKS={tavily:'https://app.tavily.com',brave:'https://api-dashboard.search.brave.com'};
const oggetto=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
export function normalizzaFonteRicerca(r){
 const errore=()=>{throw Error(traduci('sezioni.searchSource.error.invalidConfig'));};
 if(!oggetto(r)||!IDS.concat('off').includes(r.source)||typeof r.endpoint!=='string'||!['pronta','spenta','chiave-mancante','indirizzo-mancante'].includes(r.readiness)||!Array.isArray(r.fonti)||r.fonti.length!==5)errore();
 if(new Set(r.fonti.map(f=>f?.id)).size!==5||!r.fonti.every(f=>oggetto(f)&&IDS.includes(f.id)&&typeof f.label==='string'&&['needsKey','needsEndpoint','keyless','keyConfigured'].every(k=>typeof f[k]==='boolean')))errore();
 const fonti=r.fonti.map(f=>({id:f.id,label:testoDelCampo(f,'label'),needsKey:f.needsKey,needsEndpoint:f.needsEndpoint,keyless:f.keyless,keyConfigured:f.keyConfigured,nota:NOTE[f.id]}));
 const scelta=fonti.find(f=>f.id===r.source),pronta=r.source!=='off'&&r.readiness==='pronta';
 const messaggio=r.source==='off'?traduci('sezioni.searchSource.status.off'):r.readiness==='pronta'?traduci('sezioni.searchSource.status.ready'):r.readiness==='chiave-mancante'?traduci('sezioni.searchSource.status.needsKey'):r.readiness==='indirizzo-mancante'?traduci('sezioni.searchSource.status.needsEndpoint'):traduci('sezioni.searchSource.status.off');
 return {source:r.source,endpoint:r.endpoint,readiness:r.readiness,fonti,scelta,pronta,messaggio};
}
export function normalizzaProvaRicerca(r){if(!oggetto(r)||typeof r.fonte!=='string'||!r.fonte.trim()||!Number.isInteger(r.risultati)||r.risultati<0||!Array.isArray(r.titoli)||!r.titoli.every(t=>typeof t==='string'))throw Error(traduci('sezioni.searchSource.error.invalidTest'));return {fonte:r.fonte,risultati:r.risultati,titoli:[...r.titoli]};}
function nodo(tag,classe,testo){const e=document.createElement(tag);if(classe)e.className=classe;if(testo!=null)e.textContent=testo;return e;}
function bottone(testo,azione,fn){const e=nodo('button','talos-button talos-button--secondary',testo);e.type='button';e.dataset.searchAction=azione;e.addEventListener('click',()=>fn?.());return e;}
export function creaScelteFonte(dati,{scegli}={}){
 const stato=normalizzaFonteRicerca(dati),gruppo=nodo('div','talos-choice-grid');gruppo.dataset.c='ChoiceCards';gruppo.setAttribute('role','radiogroup');gruppo.setAttribute('aria-label',traduci("sezioni.searchSource.groupLabel"));
 const fonti=[...stato.fonti,{id:'off',label:traduci('sezioni.searchSource.noSearch'),nota:NOTE.off}];
 for(const fonte of fonti){const b=nodo('button','talos-choice');b.type='button';b.dataset.searchSource=fonte.id;b.setAttribute('role','radio');b.setAttribute('aria-checked',String(stato.source===fonte.id));b.tabIndex=stato.source===fonte.id?0:-1;const title=nodo('span','talos-choice__title',fonte.label);title.id='fonte-label-'+fonte.id;b.setAttribute('aria-labelledby',title.id);b.append(title,nodo('span','talos-muted',fonte.id==='off'?traduci('sezioni.searchSource.choice.off'):fonte.needsKey?(fonte.keyConfigured?traduci('sezioni.searchSource.choice.keyPresent'):traduci('sezioni.searchSource.choice.keyNeeded')):fonte.needsEndpoint?traduci('sezioni.searchSource.choice.endpointNeeded'):traduci('sezioni.searchSource.choice.keyless')));b.addEventListener('click',()=>{if(fonte.id!==stato.source)scegli?.(fonte.id);});b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();if(gruppo.closest('[aria-busy=true]'))return;const i=fonti.indexOf(fonte),n=e.key==='Home'?0:e.key==='End'?fonti.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+fonti.length)%fonti.length;gruppo.children[n].focus();if(fonti[n].id!==stato.source)scegli?.(fonti[n].id);});gruppo.append(b);}
 return gruppo;
}
export function aggiornaFonteRicerca(mount,dati,{scegli,salvaChiave,rimuoviChiave,salvaIndirizzo,prova,ricarica,feedback='',query='TALOS local-first coding agent',esito}={}){
 const s=normalizzaFonteRicerca(dati),d=nodo('div','talos-settings__section');d.dataset.searchDetails='';
 const scelta=s.scelta;d.append(nodo('p','talos-muted',NOTE[s.source]));
 const campo=(titolo,type,value,id)=>{const label=nodo('label','talos-field');label.append(nodo('span','talos-setting__label',titolo));const input=nodo('input','talos-field__input');input.type=type;input.value=value;input.autocomplete='off';input.spellcheck=false;input.setAttribute('aria-label',titolo);input.id=id;label.append(input);d.append(label);return input;};
 if(scelta&&(scelta.needsKey||scelta.keyConfigured||scelta.id==='custom')){const key=campo(traduci('sezioni.searchSource.key.label',{source:scelta.label}),'password','','fonte-chiave');key.dataset.searchKeyInput=scelta.id;key.maxLength=4096;key.placeholder=scelta.keyConfigured?traduci("sezioni.searchSource.key.replace"):scelta.id==='custom'?traduci("sezioni.searchSource.key.optional"):traduci("sezioni.searchSource.key.paste");const a=nodo('div','talos-settings__actions'),save=bottone(traduci('sezioni.searchSource.key.save'),'save-key',()=>{if(!key.value.trim()){key.setCustomValidity(traduci('sezioni.searchSource.key.required'));key.reportValidity();return;}salvaChiave?.(scelta.id,key.value);});key.addEventListener('input',()=>key.setCustomValidity(''));key.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();save.click();}});a.append(save);if(LINKS[scelta.id]){const link=nodo('a','talos-button talos-button--secondary',traduci('sezioni.searchSource.key.get',{source:scelta.label}));link.href=LINKS[scelta.id];link.target='_blank';link.rel='noopener noreferrer';a.append(link);}if(scelta.keyConfigured)a.append(bottone(traduci('sezioni.searchSource.key.forget'),'forget-key',()=>rimuoviChiave?.(scelta.id)));d.append(a);}
 if(scelta?.needsEndpoint){const endpoint=campo(traduci('sezioni.searchSource.endpoint.label'),'url',s.endpoint,'fonte-indirizzo');endpoint.dataset.searchEndpointInput=scelta.id;endpoint.placeholder=INDIRIZZO_ESEMPIO;const salva=bottone(traduci('sezioni.searchSource.endpoint.save'),'save-endpoint',()=>{let u;try{u=new URL(endpoint.value.trim());}catch{}if(!u||!['http:','https:'].includes(u.protocol)){endpoint.setCustomValidity(traduci('sezioni.searchSource.endpoint.invalid'));endpoint.reportValidity();return;}salvaIndirizzo?.(scelta.id,endpoint.value);});endpoint.addEventListener('input',()=>endpoint.setCustomValidity(''));endpoint.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();salva.click();}});const a=nodo('div','talos-settings__actions');a.append(salva);d.append(a);}
 const readiness=nodo('p','talos-muted',esito?traduci('sezioni.searchSource.status.answered'):s.messaggio);readiness.dataset.searchReadiness=s.readiness;d.append(readiness);
 const q=campo(traduci('sezioni.searchSource.test.queryLabel'),'text',query,'fonte-query');q.dataset.searchQuery='';q.maxLength=2000;q.disabled=!s.pronta;const test=bottone(traduci('sezioni.searchSource.test.run'),'test',()=>{if(!q.value.trim()){q.setCustomValidity(traduci('sezioni.searchSource.test.queryRequired'));q.reportValidity();return;}prova?.(q.value);});test.disabled=!s.pronta;q.addEventListener('input',()=>q.setCustomValidity(''));q.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();test.click();}});const azioni=nodo('div','talos-settings__actions');azioni.append(test,bottone(traduci('sezioni.searchSource.test.reload'),'reload',ricarica));d.append(azioni);
 const stato=nodo('p','talos-muted',feedback);stato.dataset.searchFeedback='';stato.setAttribute('role','status');stato.hidden=!feedback;
 const errore=nodo('p','talos-muted');errore.dataset.searchError='';errore.setAttribute('role','alert');errore.hidden=true;
 const risultato=nodo('div','talos-settings__section');risultato.dataset.searchResult='';risultato.hidden=!esito;if(esito){const e=normalizzaProvaRicerca(esito);risultato.append(nodo('h4','',tn('sezioni.searchSource.result.headingOne','sezioni.searchSource.result.headingMany',e.risultati,{source:e.fonte})));const ul=nodo('ul','');for(const t of e.titoli)ul.append(nodo('li','',t));risultato.append(ul,nodo('p','talos-muted',traduci('sezioni.searchSource.result.note')));}
 mount.replaceChildren(creaScelteFonte(dati,{scegli}),d,stato,errore,risultato);
}
