// 05/9 Fase 2: configurazione ricerca, dentro Impostazioni.
const IDS=['duckduckgo','tavily','brave','searxng','custom'];
const NOTE={duckduckgo:'Risultati pubblici, senza account. Il servizio può limitare le richieste.',tavily:'Servizio di ricerca con chiave API.',brave:'Servizio Brave Search con chiave API.',searxng:'La tua istanza interroga i motori configurati. Deve consentire le risposte JSON.',custom:'Il tuo servizio di ricerca. Indirizzo obbligatorio, chiave facoltativa.',off:'Disattiva la ricerca web. Le altre funzioni di rete restano separate.'};
const LINKS={tavily:'https://app.tavily.com',brave:'https://api-dashboard.search.brave.com'};
const oggetto=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
export function normalizzaFonteRicerca(r){
 const errore=()=>{throw Error('La risposta della configurazione ricerca non è valida.');};
 if(!oggetto(r)||!IDS.concat('off').includes(r.source)||typeof r.endpoint!=='string'||!['pronta','spenta','chiave-mancante','indirizzo-mancante'].includes(r.readiness)||!Array.isArray(r.fonti)||r.fonti.length!==5)errore();
 if(new Set(r.fonti.map(f=>f?.id)).size!==5||!r.fonti.every(f=>oggetto(f)&&IDS.includes(f.id)&&typeof f.label==='string'&&['needsKey','needsEndpoint','keyless','keyConfigured'].every(k=>typeof f[k]==='boolean')))errore();
 const fonti=r.fonti.map(f=>({id:f.id,label:f.label,needsKey:f.needsKey,needsEndpoint:f.needsEndpoint,keyless:f.keyless,keyConfigured:f.keyConfigured,nota:NOTE[f.id]}));
 const scelta=fonti.find(f=>f.id===r.source),pronta=r.source!=='off'&&r.readiness==='pronta';
 const messaggio=r.source==='off'?'Ricerca web disattivata.':r.readiness==='pronta'?'Configurazione pronta. Connessione non ancora verificata.':r.readiness==='chiave-mancante'?'Serve una chiave API. La ricerca resta disattivata.':r.readiness==='indirizzo-mancante'?'Serve l’indirizzo del servizio. La ricerca resta disattivata.':'Ricerca web disattivata.';
 return {source:r.source,endpoint:r.endpoint,readiness:r.readiness,fonti,scelta,pronta,messaggio};
}
export function normalizzaProvaRicerca(r){if(!oggetto(r)||typeof r.fonte!=='string'||!r.fonte.trim()||!Number.isInteger(r.risultati)||r.risultati<0||!Array.isArray(r.titoli)||!r.titoli.every(t=>typeof t==='string'))throw Error('La risposta della prova di ricerca non è valida.');return {fonte:r.fonte,risultati:r.risultati,titoli:[...r.titoli]};}
function nodo(tag,classe,testo){const e=document.createElement(tag);if(classe)e.className=classe;if(testo!=null)e.textContent=testo;return e;}
function bottone(testo,azione,fn){const e=nodo('button','talos-button talos-button--secondary',testo);e.type='button';e.dataset.searchAction=azione;e.addEventListener('click',()=>fn?.());return e;}
export function creaScelteFonte(dati,{scegli}={}){
 const stato=normalizzaFonteRicerca(dati),gruppo=nodo('div','talos-choice-grid');gruppo.dataset.c='ChoiceCards';gruppo.setAttribute('role','radiogroup');gruppo.setAttribute('aria-label','Origine della ricerca web');
 const fonti=[...stato.fonti,{id:'off',label:'Nessuna ricerca web',nota:NOTE.off}];
 for(const fonte of fonti){const b=nodo('button','talos-choice');b.type='button';b.dataset.searchSource=fonte.id;b.setAttribute('role','radio');b.setAttribute('aria-checked',String(stato.source===fonte.id));b.tabIndex=stato.source===fonte.id?0:-1;const title=nodo('span','talos-choice__title',fonte.label);title.id='fonte-label-'+fonte.id;b.setAttribute('aria-labelledby',title.id);b.append(title,nodo('span','talos-muted',fonte.id==='off'?'Spenta':fonte.needsKey?(fonte.keyConfigured?'Chiave presente':'Chiave necessaria'):fonte.needsEndpoint?'Indirizzo richiesto':'Senza chiave'));b.addEventListener('click',()=>{if(fonte.id!==stato.source)scegli?.(fonte.id);});b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();if(gruppo.closest('[aria-busy=true]'))return;const i=fonti.indexOf(fonte),n=e.key==='Home'?0:e.key==='End'?fonti.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+fonti.length)%fonti.length;gruppo.children[n].focus();if(fonti[n].id!==stato.source)scegli?.(fonti[n].id);});gruppo.append(b);}
 return gruppo;
}
export function aggiornaFonteRicerca(mount,dati,{scegli,salvaChiave,rimuoviChiave,salvaIndirizzo,prova,ricarica,feedback='',query='TALOS local-first coding agent',esito}={}){
 const s=normalizzaFonteRicerca(dati),d=nodo('div','talos-settings__section');d.dataset.searchDetails='';
 const scelta=s.scelta;d.append(nodo('p','talos-muted',NOTE[s.source]));
 const campo=(titolo,type,value,id)=>{const label=nodo('label','talos-field');label.append(nodo('span','talos-setting__label',titolo));const input=nodo('input','talos-field__input');input.type=type;input.value=value;input.autocomplete='off';input.spellcheck=false;input.setAttribute('aria-label',titolo);input.id=id;label.append(input);d.append(label);return input;};
 if(scelta&&(scelta.needsKey||scelta.keyConfigured||scelta.id==='custom')){const key=campo('Chiave API '+scelta.label,'password','','fonte-chiave');key.dataset.searchKeyInput=scelta.id;key.maxLength=4096;key.placeholder=scelta.keyConfigured?'Sostituisci la chiave salvata':scelta.id==='custom'?'Facoltativa':'Incolla la chiave';const a=nodo('div','talos-settings__actions'),save=bottone('Salva chiave','save-key',()=>{if(!key.value.trim()){key.setCustomValidity('Inserisci una chiave.');key.reportValidity();return;}salvaChiave?.(scelta.id,key.value);});key.addEventListener('input',()=>key.setCustomValidity(''));key.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();save.click();}});a.append(save);if(LINKS[scelta.id]){const link=nodo('a','talos-button talos-button--secondary','Ottieni una chiave '+scelta.label);link.href=LINKS[scelta.id];link.target='_blank';link.rel='noopener noreferrer';a.append(link);}if(scelta.keyConfigured)a.append(bottone('Dimentica la chiave','forget-key',()=>rimuoviChiave?.(scelta.id)));d.append(a);}
 if(scelta?.needsEndpoint){const endpoint=campo('Indirizzo istanza','url',s.endpoint,'fonte-indirizzo');endpoint.dataset.searchEndpointInput=scelta.id;endpoint.placeholder='https://search.example.org';const salva=bottone('Salva indirizzo','save-endpoint',()=>{let u;try{u=new URL(endpoint.value.trim());}catch{}if(!u||!['http:','https:'].includes(u.protocol)){endpoint.setCustomValidity('Inserisci un indirizzo completo http o https.');endpoint.reportValidity();return;}salvaIndirizzo?.(scelta.id,endpoint.value);});endpoint.addEventListener('input',()=>endpoint.setCustomValidity(''));endpoint.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();salva.click();}});const a=nodo('div','talos-settings__actions');a.append(salva);d.append(a);}
 const readiness=nodo('p','talos-muted',esito?'La fonte ha risposto alla prova corrente.':s.messaggio);readiness.dataset.searchReadiness=s.readiness;d.append(readiness);
 const q=campo('Testo della prova','text',query,'fonte-query');q.dataset.searchQuery='';q.maxLength=2000;q.disabled=!s.pronta;const test=bottone('Prova la ricerca','test',()=>{if(!q.value.trim()){q.setCustomValidity('Scrivi cosa cercare.');q.reportValidity();return;}prova?.(q.value);});test.disabled=!s.pronta;q.addEventListener('input',()=>q.setCustomValidity(''));q.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();test.click();}});const azioni=nodo('div','talos-settings__actions');azioni.append(test,bottone('Aggiorna stato','reload',ricarica));d.append(azioni);
 const stato=nodo('p','talos-muted',feedback);stato.dataset.searchFeedback='';stato.setAttribute('role','status');stato.hidden=!feedback;
 const errore=nodo('p','talos-muted');errore.dataset.searchError='';errore.setAttribute('role','alert');errore.hidden=true;
 const risultato=nodo('div','talos-settings__section');risultato.dataset.searchResult='';risultato.hidden=!esito;if(esito){const e=normalizzaProvaRicerca(esito);risultato.append(nodo('h4','',e.risultati+' risultati · '+e.fonte));const ul=nodo('ul','');for(const t of e.titoli)ul.append(nodo('li','',t));risultato.append(ul,nodo('p','talos-muted','La prova riguarda questa richiesta. I risultati non attestano la verifica delle pagine.'));}
 mount.replaceChildren(creaScelteFonte(dati,{scegli}),d,stato,errore,risultato);
}
