import test from 'node:test';
import assert from 'node:assert/strict';
import {summarize} from '../lib/statistics.mjs';
import {analyseTrace} from '../lib/trace.mjs';
const metadata={scope:'fixture',event_origin:'fixture',run_id:'r',clock_id:'c',product:'TEST FIXTURE NOT TALOS',build_identity:'fixture',task_identity:'fixture',model_identity:'NO MODEL'};
const e=(event,mono_ms,extra={})=>({event,mono_ms,clock_id:'c',run_id:'r',...extra});
const t=events=>({schema_version:1,metadata:{...metadata},events});
const base=()=>t([e('task_submitted',0),e('provider_request_started',1,{request_id:'p'}),e('provider_first_token',6,{request_id:'p'}),e('renderer_first_token',9,{request_id:'p'}),e('task_verified',10,{verifier_exit_code:0})]);
test('empty statistics retain null, never zero',()=>assert.equal(summarize([]).p95,null));
test('statistics interpolate exact sample quantiles',()=>assert.deepEqual(summarize([1,2,3,4]),{n:4,min:1,median:2.5,p95:3.8499999999999996,p99:3.9699999999999998,max:4}));
test('statistics do not mutate input',()=>{const v=[3,1];summarize(v);assert.deepEqual(v,[3,1]);});
test('statistics reject non-finite or coerced data',()=>{for(const v of [[NaN],[Infinity],['1'],null])assert.throws(()=>summarize(v));});
test('single sample is descriptive, not an estimate',()=>assert.equal(summarize([5]).median,5));
test('trace keeps layers separate',()=>{const a=analyseTrace(base());assert.equal(a.metrics.provider_ttft_ms.median,5);assert.equal(a.metrics.first_token_ingest_to_render_ms.median,3);assert.equal(a.metrics.user_to_first_rendered_token_ms,9);assert.equal(a.metrics.task_verified_wall_ms,10);});
test('trace never infers throughput or desktop RAM',()=>{const a=analyseTrace(base());assert.equal(a.metrics.tokens_per_second,null);assert.equal(a.metrics.total_desktop_rss_bytes,null);});
test('empty trace is incomplete, not a successful zero',()=>{const a=analyseTrace(t([]));assert.equal(a.status,'incomplete');assert.equal(a.metrics.task_verified_wall_ms,null);});
test('missing pair stays null',()=>assert.equal(analyseTrace(t([e('task_submitted',1)])).metrics.user_to_first_rendered_token_ms,null));
test('fixtures cannot be relabelled desktop',()=>{const b=base();b.metadata.scope='desktop';assert.throws(()=>analyseTrace(b),/Fixture/);});
test('unknown markers are rejected',()=>assert.throws(()=>analyseTrace(t([e('unknown',0)]))));
test('mixed clocks are rejected',()=>assert.throws(()=>analyseTrace(t([e('task_submitted',1,{clock_id:'other'})])),/Mixed/));
test('mixed runs are rejected',()=>assert.throws(()=>analyseTrace(t([e('task_submitted',1,{run_id:'other'})])),/Mixed/));
test('mixed event origins are rejected',()=>assert.throws(()=>analyseTrace(t([e('task_submitted',1,{origin:'manual'})])),/origins/));
test('nonmonotonic time is rejected',()=>assert.throws(()=>analyseTrace(t([e('task_submitted',2),e('task_failed',1)])),/ordering/));
test('NaN and negative time are rejected',()=>{for(const n of [NaN,-1,Infinity])assert.throws(()=>analyseTrace(t([e('task_submitted',n)])));});
test('duplicate singleton is rejected',()=>assert.throws(()=>analyseTrace(t([e('task_submitted',1),e('task_submitted',2)])),/Duplicate/));
test('conflicting terminal outcomes are rejected',()=>assert.throws(()=>analyseTrace(t([e('task_failed',1),e('task_verified',2,{verifier_exit_code:0})])),/terminal/));
test('verified task needs an independent verifier exit status',()=>assert.throws(()=>analyseTrace(t([e('task_verified',2)])),/verifier/));
test('tool end must have start and outcome',()=>{assert.throws(()=>analyseTrace(t([e('tool_finished',1,{tool_call_id:'x',outcome:'ok'})])));assert.throws(()=>analyseTrace(t([e('tool_started',1,{tool_call_id:'x'}),e('tool_finished',2,{tool_call_id:'x'})])));});
test('incomplete tools are not erased',()=>{const a=analyseTrace(t([e('tool_started',1,{tool_call_id:'x'})]));assert.equal(a.metrics.tool_calls_incomplete,1);assert.equal(a.metrics.complete_tool_durations_ms.n,0);});
test('parallel tools retain durations and failures independently',()=>{const a=analyseTrace(t([e('tool_started',0,{tool_call_id:'a'}),e('tool_started',1,{tool_call_id:'b'}),e('tool_finished',4,{tool_call_id:'b',outcome:'failed'}),e('tool_finished',8,{tool_call_id:'a',outcome:'ok'})]));assert.equal(a.metrics.complete_tool_durations_ms.median,5.5);assert.equal(a.metrics.tool_calls_failed,1);assert.equal(a.metrics.tool_calls_completed,2);});
test('duplicate tool starts are rejected',()=>assert.throws(()=>analyseTrace(t([e('tool_started',0,{tool_call_id:'a'}),e('tool_started',1,{tool_call_id:'a'})])),/Duplicate/));
test('multiple requests in a long task do not overwrite each other',()=>{const a=analyseTrace(t([e('provider_request_started',0,{request_id:'a'}),e('provider_first_token',3,{request_id:'a'}),e('provider_request_started',4,{request_id:'b'}),e('provider_first_token',9,{request_id:'b'})]));assert.equal(a.metrics.provider_requests_started,2);assert.equal(a.metrics.provider_ttft_ms.median,4);});
test('unfinished provider requests remain visible',()=>assert.equal(analyseTrace(t([e('provider_request_started',0,{request_id:'a'})])).metrics.requests_without_observed_first_token,1));
test('token without request start is rejected',()=>assert.throws(()=>analyseTrace(t([e('provider_first_token',1,{request_id:'a'})]))));
test('rendered token without ingest is rejected',()=>assert.throws(()=>analyseTrace(t([e('provider_request_started',0,{request_id:'a'}),e('renderer_first_token',1,{request_id:'a'})]))));
test('request ID is required',()=>assert.throws(()=>analyseTrace(t([e('provider_request_started',0)]))));
test('cancellation measures quiescence, never success',()=>{const a=analyseTrace(t([e('cancel_requested',10),e('task_quiescent',15)]));assert.equal(a.metrics.cancel_to_quiescent_ms,5);assert.equal(a.metrics.task_verified_wall_ms,null);});
test('clock-sorted but causally reversed task is rejected',()=>assert.throws(()=>analyseTrace(t([e('task_verified',0,{verifier_exit_code:0}),e('task_submitted',1)])),/Causal/));
test('arbitrary metadata fields are not copied to the output',()=>{const b=base();b.metadata.secret='not-for-output';assert.equal(analyseTrace(b).metadata.secret,undefined);});
test('placeholder manifest cannot masquerade as measured trace',()=>{const b=base();b.metadata.build_identity=null;assert.throws(()=>analyseTrace(b));});
