import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const preload=new URL('../probes/node-preload.mjs',import.meta.url).href;
const run=extra=>spawnSync(process.execPath,['--import',preload,'--input-type=module','-e','await new Promise(r=>setTimeout(r,75));'],{env:{...process.env,TALOS_AUDIT_DIRECTORY:'',...extra},encoding:'utf8',timeout:5000});
test('preload is opt-in and exits without config',()=>{const p=run({});assert.equal(p.status,0);assert.equal(p.stderr,'');});
test('preload invalid config fails open with generic warning',()=>{const p=run({TALOS_AUDIT_DIRECTORY:'relative'});assert.equal(p.status,0);assert.match(p.stderr,/did not start/);assert.ok(!p.stderr.includes('relative'));});
test('preload child process exits and flushes final probe record',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'preload-fixture-'));try{const p=run({TALOS_AUDIT_DIRECTORY:d,TALOS_AUDIT_INTERVAL_MS:'25'});assert.equal(p.status,0,p.stderr);const files=await fs.readdir(d);assert.equal(files.length,1);const rows=(await fs.readFile(path.join(d,files[0]),'utf8')).trim().split('\n').map(JSON.parse);assert.equal(rows.at(-1).event,'probe_stop');assert.ok(rows.some(r=>r.event==='sample'));}finally{await fs.rm(d,{recursive:true,force:true});}});
