import type { TalosCommand } from './talosTypes'

export const talosCommands: TalosCommand[] = [
    {
        id: 'new_session',
        label: 'New session',
        description: 'Start a clean chat session in the current TALOS surface.',
        category: 'chat',
        risk: 'low',
        capability: 'talos.chat.session.create',
        disabledReason: 'Command palette is not wired to the chat session handler yet.',
    },
    {
        id: 'send_message',
        label: 'Send message',
        description: 'Send the current composer message through the real TALOS chat endpoint.',
        category: 'chat',
        risk: 'low',
        capability: 'talos.chat.message.create',
        disabledReason: 'Command palette is not wired to the chat composer handler yet.',
    },
    {
        id: 'attach_file',
        label: 'Attach file',
        description: 'Upload a local file into the dashboard Context Vault.',
        category: 'context',
        risk: 'medium',
        capability: 'talos.files.upload',
        disabledReason: 'Command palette file picker is not wired yet; use the dashboard Context Vault upload panel.',
    },
    {
        id: 'open_context_vault',
        label: 'Open Context Vault',
        description: 'Open persisted files, chunks, and context sets.',
        category: 'context',
        risk: 'low',
        capability: 'talos.context.read',
        disabledReason: 'Command palette navigation is not wired yet; use the dashboard Context Vault panel.',
    },
    {
        id: 'run_avm_compare',
        label: 'Run AVM compare',
        description: 'Run an AVM ON/OFF benchmark comparison with stored evidence.',
        category: 'benchmark',
        risk: 'medium',
        capability: 'talos.benchmarks.create',
        disabledReason: 'Open the dashboard workbench and select a benchmark scenario path.',
    },
    {
        id: 'open_trace_replay',
        label: 'Open trace replay',
        description: 'Inspect replayable trace events for a persisted TALOS run.',
        category: 'run',
        risk: 'low',
        capability: 'talos.runs.replay',
        disabledReason: 'Select a run in the dashboard timeline.',
    },
    {
        id: 'recover_failed_node',
        label: 'Recover failed node',
        description: 'Request controlled HMI recovery for a failed AVM node.',
        category: 'run',
        risk: 'high',
        capability: 'talos.runs.recover',
        disabledReason: 'Select a failed node in the dashboard timeline.',
    },
    {
        id: 'open_benchmark_workbench',
        label: 'Open benchmark workbench',
        description: 'Open the dashboard workbench for AVM evidence comparisons.',
        category: 'benchmark',
        risk: 'low',
        capability: 'talos.benchmarks.read',
        disabledReason: 'Benchmark workbench is available in the dashboard.',
    },
    {
        id: 'open_model_center',
        label: 'Open model center',
        description: 'Manage provider profiles and model probes.',
        category: 'model',
        risk: 'medium',
        capability: 'talos.models.read',
        disabledReason: 'Command palette navigation is not wired yet; use the dashboard Model Center panel.',
    },
    {
        id: 'open_doctor',
        label: 'Open doctor',
        description: 'Inspect TALOS readiness checks and degraded dependencies.',
        category: 'system',
        risk: 'low',
        capability: 'talos.doctor.read',
        disabledReason: 'Command palette navigation is not wired yet; use the dashboard Doctor panel.',
    },
    {
        id: 'open_audit_log',
        label: 'Open audit log',
        description: 'Inspect persisted security and operator audit events.',
        category: 'system',
        risk: 'low',
        capability: 'talos.audit.read',
        disabledReason: 'Command palette navigation is not wired yet; use the dashboard Audit Log panel.',
    },
    {
        id: 'open_policy_panel',
        label: 'Open policy panel',
        description: 'Inspect default-deny admin capabilities and scoped token status.',
        category: 'system',
        risk: 'low',
        capability: 'talos.policy.read',
        disabledReason: 'Command palette navigation is not wired yet; use the dashboard Policy panel.',
    },
    {
        id: 'open_backup_panel',
        label: 'Open backup panel',
        description: 'Inspect backup manifest domains and restore safety policy.',
        category: 'system',
        risk: 'medium',
        capability: 'talos.backup.read',
        disabledReason: 'Command palette navigation is not wired yet; use the dashboard Backup panel.',
    },
    {
        id: 'validate_backup_restore',
        label: 'Validate backup restore',
        description: 'Validate a TALOS backup manifest through the dry-run restore endpoint.',
        category: 'system',
        risk: 'high',
        capability: 'talos.backup.restore',
        disabledReason: 'Open the dashboard Backup panel; restore validation is dry-run only and requires a scoped admin token.',
    },
    {
        id: 'export_report',
        label: 'Export report',
        description: 'Export a replayable evidence or benchmark report.',
        category: 'report',
        risk: 'medium',
        capability: 'talos.reports.export',
        disabledReason: 'Report export requires a dedicated export API endpoint.',
    },
    {
        id: 'open_notes',
        label: 'Open notes',
        description: 'Inspect and create untrusted workspace notes.',
        category: 'productivity',
        risk: 'low',
        capability: 'talos.notes.read',
        disabledReason: 'Notes are available in the dashboard productivity panel.',
    },
    {
        id: 'open_tasks',
        label: 'Open tasks',
        description: 'Inspect run-linked TALOS tasks.',
        category: 'productivity',
        risk: 'low',
        capability: 'talos.tasks.read',
        disabledReason: 'Tasks are available in the dashboard productivity panel.',
    },
    {
        id: 'open_calendar_drafts',
        label: 'Open calendar drafts',
        description: 'Inspect draft-only calendar actions that require manual confirmation.',
        category: 'productivity',
        risk: 'medium',
        capability: 'talos.calendar.read',
        disabledReason: 'Calendar drafts are available in the dashboard productivity panel.',
    },
    {
        id: 'open_email_triage',
        label: 'Open email triage',
        description: 'Inspect read-only email context and draft replies.',
        category: 'email',
        risk: 'medium',
        capability: 'talos.email.read',
        disabledReason: 'Email triage is available in the dashboard email panel.',
    },
    {
        id: 'create_email_draft',
        label: 'Create email draft',
        description: 'Create a draft from selected email messages without sending it.',
        category: 'email',
        risk: 'medium',
        capability: 'talos.email.draft',
        disabledReason: 'Select an email message in the dashboard triage panel.',
    },
    {
        id: 'send_email_draft',
        label: 'Send email draft',
        description: 'Send a reviewed email draft.',
        category: 'email',
        risk: 'critical',
        capability: 'talos.email.send',
        disabledReason: 'Email send is disabled until HMI confirmation and audit exist.',
    },
]

export function isTalosCommandEnabled(command: TalosCommand) {
    return !command.disabledReason
}

export function findTalosCommand(id: TalosCommand['id']) {
    return talosCommands.find((command) => command.id === id)
}
