<script setup lang="ts">
import { computed } from 'vue'
import { Braces, Download, FileJson, FileText, X } from '@lucide/vue'
import Button from '../../ui/Button.vue'
import Badge from '../../ui/Badge.vue'
import type { TalosSession, TalosSessionExportFormat, TalosSessionExportPayload } from '../../../lib/talosTypes'

const props = defineProps<{
    session: TalosSession | null
    result: TalosSessionExportPayload | null
    exporting: boolean
    error: string | null
}>()

const emit = defineEmits<{
    close: []
    export: [format: TalosSessionExportFormat]
}>()

const formats: Array<{
    format: TalosSessionExportFormat
    label: string
    action: string
    detail: string
}> = [
    {
        format: 'json',
        label: 'JSON evidence pack',
        action: 'Export JSON evidence pack',
        detail: 'Messages, runs, replay state, grounding sources, and benchmark readiness.',
    },
    {
        format: 'markdown',
        label: 'Markdown transcript',
        action: 'Export Markdown transcript',
        detail: 'Human-readable transcript for reports and handoff.',
    },
    {
        format: 'context_manifest',
        label: 'Context manifest',
        action: 'Export Context manifest',
        detail: 'Grounding source IDs, file names, hashes, and previews without storage paths.',
    },
    {
        format: 'benchmark_scenario',
        label: 'Benchmark scenario',
        action: 'Export Benchmark scenario',
        detail: 'Benchmark-ready scenario only when prompt and context hashes are complete.',
    },
]

const preview = computed(() => {
    if (!props.result) {
        return ''
    }

    if (typeof props.result.content === 'string') {
        return props.result.content
    }

    return JSON.stringify(props.result, null, 2)
})

const contextSourceNames = computed(() => {
    const manifest = props.result?.context_manifest
    if (!manifest || typeof manifest !== 'object') {
        return []
    }

    const sets = (manifest as { context_sets?: unknown }).context_sets
    if (!Array.isArray(sets)) {
        return []
    }

    return sets.flatMap((set) => {
        if (!set || typeof set !== 'object') {
            return []
        }

        const sources = (set as { sources?: unknown }).sources
        if (!Array.isArray(sources)) {
            return []
        }

        return sources.flatMap((source) => {
            if (!source || typeof source !== 'object') {
                return []
            }

            const file = (source as { file?: unknown }).file
            if (!file || typeof file !== 'object') {
                return []
            }

            const name = (file as { original_name?: unknown }).original_name

            return typeof name === 'string' ? [name] : []
        })
    })
})

const benchmarkReady = computed(() => props.result?.benchmark_readiness?.ready === true || props.result?.report_type === 'talos_benchmark_scenario_export')
</script>

<template>
    <div class="fixed inset-0 z-50 bg-black/45 px-4 py-10 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Export session evidence" @click.self="emit('close')">
        <section class="mx-auto flex max-h-[calc(100vh-5rem)] w-full max-w-4xl flex-col overflow-hidden rounded-md border border-[var(--talos-border)] bg-[var(--talos-card)] shadow-2xl">
            <header class="flex items-start justify-between gap-3 border-b border-[var(--talos-border)] p-4">
                <div class="min-w-0">
                    <div class="flex items-center gap-2 text-xs font-semibold uppercase text-[var(--talos-muted)]">
                        <Download class="h-4 w-4 text-[var(--talos-accent)]" />
                        Export session evidence
                    </div>
                    <h3 class="mt-1 truncate text-base font-semibold text-[var(--talos-text)]">{{ props.session?.title ?? 'No active session' }}</h3>
                    <p class="mt-1 max-w-2xl text-xs leading-5 text-[var(--talos-muted)]">
                        Exports are generated by the TALOS control plane with redacted metadata, context provenance, and replayability state.
                    </p>
                </div>
                <Button type="button" variant="ghost" size="icon" aria-label="Close export dialog" @click="emit('close')">
                    <X class="h-4 w-4" />
                </Button>
            </header>

            <div class="grid min-h-0 flex-1 gap-4 overflow-y-auto p-4 lg:grid-cols-[320px_minmax(0,1fr)]">
                <div class="space-y-3">
                    <article v-for="format in formats" :key="format.format" class="rounded-md border border-[var(--talos-border)] bg-[var(--talos-panel-soft)] p-3">
                        <div class="flex items-start gap-2">
                            <FileJson v-if="format.format === 'json' || format.format === 'benchmark_scenario'" class="mt-0.5 h-4 w-4 shrink-0 text-[var(--talos-accent)]" />
                            <FileText v-else-if="format.format === 'markdown'" class="mt-0.5 h-4 w-4 shrink-0 text-[var(--talos-accent)]" />
                            <Braces v-else class="mt-0.5 h-4 w-4 shrink-0 text-[var(--talos-accent)]" />
                            <div class="min-w-0">
                                <div class="text-sm font-semibold text-[var(--talos-text)]">{{ format.label }}</div>
                                <p class="mt-1 text-xs leading-5 text-[var(--talos-muted)]">{{ format.detail }}</p>
                            </div>
                        </div>
                        <Button type="button" size="sm" class="mt-3 w-full" :aria-label="format.action" :disabled="!props.session || props.exporting" @click="emit('export', format.format)">
                            <Download class="h-4 w-4" />
                            Generate
                        </Button>
                    </article>
                </div>

                <div class="min-w-0 rounded-md border border-[var(--talos-border)] bg-[var(--talos-panel-soft)] p-3">
                    <div class="flex flex-wrap items-center justify-between gap-2">
                        <div>
                            <div class="text-xs font-semibold uppercase text-[var(--talos-muted)]">Export preview</div>
                            <div class="mt-1 text-sm font-semibold text-[var(--talos-text)]">{{ props.result?.report_type ?? 'No export generated yet' }}</div>
                        </div>
                        <div class="flex flex-wrap gap-2">
                            <Badge v-if="benchmarkReady" tone="success">Benchmark ready</Badge>
                            <Badge v-if="props.result" tone="neutral">{{ props.result.export_status }}</Badge>
                        </div>
                    </div>

                    <div v-if="props.error" class="mt-3 rounded-md border border-[var(--talos-warning-border)] bg-[var(--talos-warning-soft)] px-3 py-2 text-sm text-[var(--talos-text)]">
                        {{ props.error }}
                    </div>

                    <div v-if="contextSourceNames.length" class="mt-3 rounded-md border border-[var(--talos-border)] bg-[var(--talos-panel)] px-3 py-2">
                        <div class="text-[11px] font-semibold uppercase text-[var(--talos-muted)]">Context sources</div>
                        <div class="mt-1 flex flex-wrap gap-2">
                            <Badge v-for="name in contextSourceNames" :key="name" tone="neutral">{{ name }}</Badge>
                        </div>
                    </div>

                    <pre v-if="preview" data-testid="talos-session-export-preview" class="mt-3 max-h-[460px] overflow-auto whitespace-pre-wrap rounded-md border border-[var(--talos-border)] bg-[var(--talos-panel)] p-3 text-xs leading-5 text-[var(--talos-muted)]">{{ preview }}</pre>
                    <div v-else class="mt-3 rounded-md border border-[var(--talos-border)] bg-[var(--talos-panel)] px-3 py-8 text-center text-sm text-[var(--talos-muted)]">
                        Choose an export format to generate a session artifact.
                    </div>
                </div>
            </div>
        </section>
    </div>
</template>
