import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {avviaCapabilityDiProva} from './capability-backend-fixture.mjs';
const APP='http://127.0.0.1:4177',ORIGINALE='http://127.0.0.1:4179',ROTTE=/\/api\/v1\/(?:tools|sessions\/[^/]+\/(?:tools|settings))$/;
const FOTO=path.resolve('artifacts/astra-fase2/ToolList');
async function foto(page,nome,info){await mkdir(FOTO,{recursive:true});await page.screenshot({path:path.join(FOTO,nome+'-'+info.project.use.viewport.width+'.png'),animations:'disabled'});}
async function pronta(page,url=APP){await page.goto(url);const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();await expect(page.getByRole('textbox',{name:'Messaggio',exact:true})).toBeVisible();}
async function apri(page){await page.getByRole('button',{name:/^Capability(?: \d+)?$/,exact:false}).click();}
test('CAP-ORIGINALE: leggo lo stesso catalogo e il foglio permessi',async({page},info)=>{const lab=await avviaCapabilityDiProva();try{await page.route(ROTTE,r=>lab.inoltra(r));await pronta(page,ORIGINALE);if(info.project.use.viewport.width<=1040)await page.getByRole('button',{name:'Mostra o nascondi inspector',exact:true}).click();await page.getByRole('button',{name:'Gestisci capability',exact:true}).click();await expect(page.locator('#toolsListMount [data-tool-name]')).toHaveCount(6);await foto(page,'originale-catalogo',info);await page.getByRole('button',{name:'Chiudi pannello',exact:true}).click();await page.setViewportSize({width:1440,height:900});await page.locator('[data-open-sheet="permissions"]').first().click();await page.setViewportSize(info.project.use.viewport);await expect(page.locator('[data-tool-permission-select]').first()).toBeVisible();await foto(page,'originale-permessi',info);}finally{try{await page.unrouteAll({behavior:'wait'});}finally{await lab.chiudi();}}});
test('CAP-VUOTO: il runtime mancante non diventa un catalogo inventato',async({page},info)=>{await pronta(page);await apri(page);const p=page.locator('#schermoCapability');await expect(p.getByText(/runtime agente non/)).toBeVisible();await expect(p.locator('[role="option"]')).toHaveCount(0);await foto(page,'app-non-osservabile',info);});

test('CAP-PERSISTENZA: cerco un attrezzo, scelgo il permesso e lo ritrovo dopo il ricaricamento',async({page},info)=>{
 const lab=await avviaCapabilityDiProva();let sessionId;try{
 await page.route(ROTTE,r=>{const m=new URL(r.request().url()).pathname.match(/sessions\/([^/]+)\/tools$/);if(m)sessionId=decodeURIComponent(m[1]);return lab.inoltra(r);});await pronta(page);await apri(page);const p=page.locator('#schermoCapability'),select=p.getByRole('combobox',{name:'Permesso per questo attrezzo',exact:true});await expect(p.locator('[data-cap-list]').getByRole('option')).toHaveCount(6);await foto(page,'app-catalogo',info);
 await p.getByRole('searchbox',{name:'Cerca fra gli attrezzi'}).fill('documento');await expect(p.locator('[data-cap-list]').getByRole('option')).toHaveCount(1);await p.locator('[data-cap-list]').getByRole('option').click();await expect(select).toHaveValue('');await expect(select).toBeEnabled();await foto(page,'app-dettaglio',info);
 await p.getByRole('searchbox').fill('');
 for(const valore of ['sempre','chiedi','nega','']){await select.focus();await select.selectOption(valore);await expect.poll(async()=> (await lab.leggiPermessi(sessionId)).find(a=>a.nome==='document_create').permesso).toBe(valore||null);await expect(select).toBeEnabled();await expect(select).toHaveValue(valore);await expect(select).toBeFocused();}
 expect(await lab.leggiDisco(sessionId)).toContain('impostazioni');await page.reload();await apri(page);await p.getByRole('searchbox').fill('documento');await expect(select).toHaveValue('');await expect(select).toBeEnabled();await select.selectOption('nega');await expect(select).toBeEnabled();await page.reload();await apri(page);await p.getByRole('searchbox').fill('documento');await expect(select).toHaveValue('nega');await foto(page,'app-ricaricata',info);
 await p.getByRole('searchbox').fill('');await p.getByRole('tab',{name:'Da configurare',exact:true}).click();await expect(p.locator('[data-cap-list]').getByRole('option')).toHaveCount(1);await expect(select).toBeDisabled();await foto(page,'app-dipendenza',info);await p.getByRole('tab',{name:'Tutti',exact:true}).click();await p.locator('[data-cap-list]').getByRole('option').first().focus();await page.keyboard.press('End');await expect(p.locator('[data-cap-list]').getByRole('option').last()).toBeFocused();await page.keyboard.press('Home');await expect(p.locator('[data-cap-list]').getByRole('option').first()).toBeFocused();
 }finally{try{if(!page.isClosed())await page.unrouteAll({behavior:'wait'});}finally{await lab.chiudi();}}
});
test('CAP-RECUPERO: un errore non cambia il permesso e posso riprovare',async({page},info)=>{
 const lab=await avviaCapabilityDiProva();let guasto='lettura',bloccaPost;const gate=new Promise(r=>bloccaPost=r);let iniziato;const inizio=new Promise(r=>iniziato=r);try{
 await page.route(ROTTE,async r=>{if(r.request().method()==='GET'&&guasto==='lettura')return r.fulfill({status:503,json:{ok:false,error:{code:'UNAVAILABLE',message:'Catalogo temporaneamente non disponibile'}}});if(r.request().method()==='GET'&&guasto==='null')return r.fulfill({json:{ok:true,data:{attrezzi:[null]}}});if(r.request().method()==='POST'&&guasto==='scrittura'){iniziato();await gate;return r.fulfill({status:503,json:{ok:false,error:{code:'UNAVAILABLE',message:'Salvataggio temporaneamente non disponibile'}}});}return lab.inoltra(r);});await pronta(page);await apri(page);const p=page.locator('#schermoCapability'),select=p.getByRole('combobox',{name:'Permesso per questo attrezzo'});await expect(p.getByRole('alert')).toContainText('Catalogo');await foto(page,'app-errore-lettura',info);guasto='null';await p.getByRole('button',{name:'Aggiorna',exact:true}).click();await expect(p.getByRole('alert')).toContainText('voci non valide');guasto='';await p.getByRole('button',{name:'Aggiorna',exact:true}).click();await expect(select).toBeEnabled();await expect(select).toHaveValue('');guasto='scrittura';await select.selectOption('sempre');await inizio;await expect(select).toBeDisabled();await expect(select).toHaveValue('');await p.locator('[data-cap-list]').getByRole('option').filter({hasText:'scrittura di un file'}).click();await expect(select).toHaveValue('');await expect(select).toBeDisabled();await page.getByRole('button',{name:/^Board \d+$/}).click();await apri(page);await expect(select).toBeDisabled();bloccaPost();await expect(p.locator('[data-cap-errore-azione]')).toContainText('comando nel terminale');await expect(select).toBeEnabled();await expect(select).toHaveValue('');await foto(page,'app-errore-salvataggio',info);guasto='';await p.locator('[data-cap-list]').getByRole('option').filter({hasText:'comando nel terminale'}).click();await select.selectOption('sempre');await expect(select).toBeEnabled();await expect(select).toHaveValue('sempre');await expect(p.locator('[data-cap-errore-azione]')).toBeHidden();
 }finally{bloccaPost();try{if(!page.isClosed())await page.unrouteAll({behavior:'wait'});}finally{await lab.chiudi();}}
});
