import {test,expect} from '@playwright/test';
import {mkdir,readFile} from 'node:fs/promises';
import path from 'node:path';
const APP='http://127.0.0.1:4177',ORIG='http://127.0.0.1:4179',FOTO=path.resolve('artifacts/astra-fase2/Doctor');
async function foto(page,nome,info){await mkdir(FOTO,{recursive:true});await page.screenshot({path:path.join(FOTO,nome+'-'+info.project.use.viewport.width+'.png'),animations:'disabled'});}
async function pronta(page,url=APP){await page.goto(url);const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();await expect(page.getByRole('textbox',{name:'Messaggio',exact:true})).toBeVisible();}
async function control(page){await page.keyboard.press('Control+k');await page.locator('[data-command=control]:visible').click();}
test('DOCTOR-ORIGINALE: chiedo un controllo e leggo il risultato',async({page},info)=>{await pronta(page,ORIG);await control(page);await page.locator('#sheetBody [data-control-action=doctor]').click();await expect(page.locator('#toastRegion')).toContainText('Doctor:');await page.getByRole('button',{name:'Chiudi pannello',exact:true}).click();await expect(page.locator('#harnessDialogBackdrop')).toBeHidden();await expect(page.locator('#toastRegion .toast').last()).toBeVisible();await foto(page,'originale',info);});
test('DOCTOR-PAGINA: vedo gli stessi dati della diagnosi reale e li posso scaricare',async({page},info)=>{await pronta(page);await control(page);await page.locator('#sheetBody [data-control-action=doctor]').click();const s=page.locator('#schermoDoctor');await expect(s.locator('[data-doctor-esito]')).toContainText('controlli');await expect(s.locator('[data-doctor-id=runtime]')).toContainText('non è pronto');await expect(s.locator('[data-doctor-id=shell]')).toContainText('desktop');await expect(s).not.toContainText('1.565');await expect(page.locator('#harnessDialogBackdrop')).toBeHidden();await foto(page,'app',info);await s.locator('[data-doctor-id=sessioni]').scrollIntoViewIfNeeded();await expect(s.locator('[data-doctor-id=sessioni]')).toContainText('73');await foto(page,'app-dettagli',info);const download=page.waitForEvent('download');await s.getByRole('button',{name:'Esporta in JSON',exact:true}).click();const d=await download;const parsed=JSON.parse(await readFile(await d.path(),'utf8'));expect(parsed.risultato.shell).toBe('desktop');expect(parsed.risultato.ownerRuntime.pronto).toBe(false);await page.reload();await control(page);await page.locator('#sheetBody [data-control-action=doctor]').click();await expect(page.locator('[data-doctor-id=runtime]')).toContainText('non è pronto');});

test('DOCTOR-RECUPERO: capisco il problema, riprovo e conservo l’ultimo risultato',async({page},info)=>{
 let mode='errore';const minimo={chiaveApi:false,shell:'none',git:false,naviga:false};await page.route('**/api/v1/doctor',r=>mode==='reale'?r.continue():r.fulfill(mode==='errore'?{status:503,json:{ok:false,error:{code:'UNAVAILABLE',message:'Servizio temporaneamente non disponibile'}}}:{json:{ok:true,data:mode==='invalido'?{}:minimo}}));
 await pronta(page);await control(page);await page.locator('#sheetBody [data-control-action=doctor]').click();const s=page.locator('#schermoDoctor'),b=s.getByRole('button',{name:'Ricontrolla',exact:true});await expect(s.getByRole('alert')).toContainText('temporaneamente');await expect(s.getByRole('button',{name:'Esporta in JSON',exact:true})).toBeDisabled();await foto(page,'app-errore',info);
 mode='invalido';await b.click();await expect(s.getByRole('alert')).toContainText('non è valida');mode='minimo';await b.click();await expect(s.locator('[data-doctor-id=runtime]')).toContainText('Non osservato');await expect(s.locator('[data-doctor-count=danger]')).toHaveText('1');await foto(page,'app-parziale',info);
 mode='errore';await b.click();await expect(s.getByRole('status')).toContainText('ultimo risultato conservato');await expect(s.locator('[data-doctor-id=shell]')).toContainText('Nessun ambiente');await expect(s.getByRole('button',{name:'Esporta in JSON',exact:true})).toBeEnabled();mode='reale';await b.focus();await b.click();await expect(s.locator('[data-doctor-id=runtime]')).toContainText('non è pronto');await expect(s.getByRole('alert')).toBeHidden();await expect(b,'DOCTOR-FOCUS').toBeFocused();
});
test('DOCTOR-SCARTI-VISIBILI: leggo perché una sessione non è stata ripristinata',async({page},info)=>{
 const dato={chiaveApi:true,shell:'wsl2',git:true,naviga:true,sessioniPersistenza:{corrotte:['sessione-a'],scartate:[{sessionId:'sessione-a',motivo:'corrotta',dettaglio:'Registro incompleto'},{sessionId:'sessione-b',motivo:'lettura-fallita',dettaglio:'Accesso negato'}],ultimaLettura:{ripristinate:71,totali:73},dettaglio:'71 ripristinate, 2 scartate su 73.'}};
 await page.route('**/api/v1/doctor',r=>r.fulfill({json:{ok:true,data:dato}}));await pronta(page);await control(page);await page.locator('#sheetBody [data-control-action=doctor]').click();const s=page.locator('#schermoDoctor');await expect(s.locator('[data-doctor-list] [data-doctor-id]').first()).toHaveAttribute('data-doctor-id','sessioni');await expect(s.locator('[data-doctor-id=sessioni]')).toContainText('sessione-b · lettura-fallita · Accesso negato');await foto(page,'app-scarti',info);
});
