import {test,expect} from '@playwright/test';import {mkdir} from 'node:fs/promises';import path from 'node:path';import {avviaEstensioniDiProva} from './estensioni-backend-fixture.mjs';
const APP='http://127.0.0.1:4177',ORIGINALE='http://127.0.0.1:4179',ROTTE=/\/api\/v1\/sessions\/[^/]+\/(?:skills|mcp|plugins|hooks)(?:\/[^/]+\/trust)?$/;
const FOTO=path.resolve('artifacts/astra-fase2/ExtensionList');async function foto(page,nome,info){await mkdir(FOTO,{recursive:true});await page.screenshot({path:path.join(FOTO,nome+'-'+info.project.use.viewport.width+'.png'),animations:'disabled'});}
async function pronta(page,url=APP){await page.goto(url);const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();await expect(page.getByRole('textbox',{name:'Messaggio',exact:true})).toBeVisible();}
async function apri(page,tipo){await page.getByRole('button',{name:/^Capability(?: \d+)?$/}).click();await page.locator('#schermoCapability').getByRole('tab',{name:tipo,exact:true}).click();}
test('EXT-ORIGINALE: leggo skill, server e plugin del progetto',async({page},info)=>{const lab=await avviaEstensioniDiProva();try{await page.route(ROTTE,r=>lab.inoltra(r));await pronta(page,ORIGINALE);if(info.project.use.viewport.width<=1040)await page.getByRole('button',{name:'Mostra o nascondi inspector',exact:true}).click();await page.getByRole('button',{name:'Gestisci capability',exact:true}).click();for(const [tipo,id,testo] of [['skills','skillsListMount','Revisione del progetto'],['mcp','mcpListMount','documentazione'],['plugins','pluginsListMount','Qualità del progetto']]){const p=page.locator('#'+id);await expect(p).toContainText(testo);await p.scrollIntoViewIfNeeded();await foto(page,'originale-'+tipo,info);}await page.getByRole('button',{name:'Chiudi pannello',exact:true}).click();await page.keyboard.press('Control+k');await page.locator('[data-command=control]').click();await expect(page.locator('#hooksListMount')).toContainText('prima-del-comando');await page.locator('#hooksListMount').scrollIntoViewIfNeeded();await foto(page,'originale-hooks',info);}finally{await page.unrouteAll({behavior:'wait'});await lab.chiudi();}});
test('EXT-PAGINE: ogni sezione apre il proprio inventario',async({page},info)=>{await pronta(page);await apri(page,'Skill');await expect(page.locator('[data-cap-panel=skills]')).toBeVisible();await expect(page.locator('[data-cap-panel=skills]')).toContainText('0 di 0');await foto(page,'app-vuota',info);});

test('EXT-FIDUCIA-PERSISTITA: cerco, leggo e fido; al ricarico ritrovo la scelta',async({page},info)=>{
 const lab=await avviaEstensioniDiProva();try{await page.route(ROTTE,r=>lab.inoltra(r));await pronta(page);await apri(page,'Skill');
 for(const [tipo,label] of [['skills','Skill'],['mcp','Connettori'],['plugins','Plugin'],['hooks','Hook']]){await page.locator('#schermoCapability').getByRole('tab',{name:label,exact:true}).click();const p=page.locator('[data-cap-panel='+tipo+']');await expect(p.locator('[data-ext-list] [role=option]')).toHaveCount(tipo==='plugins'?1:2);if(tipo==='skills'){await p.getByRole('searchbox').fill('consegna');await expect(p.getByRole('option')).toHaveCount(1);}await foto(page,'app-'+tipo,info);if(tipo!=='skills'){if(tipo==='mcp')await expect(p.locator('[data-ext-detail]')).toContainText('--read-only');await p.getByRole('button',{name:'Fida',exact:true}).focus();await p.getByRole('button',{name:'Fida',exact:true}).click();await expect(p.locator('[data-ext-stato]')).toHaveText('Fidato');await expect(p.locator('[data-ext-detail] h3'),'EXT-FOCUS-FIDUCIA').toBeFocused();const id={mcp:'documentazione',plugins:'quality',hooks:'prima-del-comando'}[tipo];expect((await lab.leggiFiducia(tipo,id)).hash).toMatch(/^[a-f0-9]{64}$/);if(tipo==='plugins')await expect(p.locator('[data-ext-warnings]')).toContainText('credenziale');await foto(page,'app-fidata-'+tipo,info);}}
 await page.reload();await apri(page,'Plugin');for(const [tipo,label] of [['plugins','Plugin'],['hooks','Hook'],['mcp','Connettori']]){await page.locator('#schermoCapability').getByRole('tab',{name:label,exact:true}).click();await expect(page.locator('#capPanel-'+tipo+' [data-ext-stato]')).toHaveText('Fidato');if(tipo==='plugins')await expect(page.locator('#capPanel-plugins [data-ext-warnings]')).toContainText('credenziale');}const p=page.locator('[data-cap-panel=mcp]');await expect(p.locator('[data-ext-stato]')).toHaveText('Fidato');await lab.cambiaManifesto();await p.getByRole('button',{name:'Aggiorna',exact:true}).click();await expect(p.locator('[data-ext-stato]')).toHaveText('Da fidare');await expect(p.locator('[data-ext-detail]')).toContainText('--updated');await foto(page,'app-modificata',info);
 const tab=page.locator('#capTab-mcp');await tab.focus();await page.keyboard.press('End');await expect(page.locator('#capTab-hooks')).toBeFocused();await expect(tab).toHaveAttribute('aria-selected','true');await page.keyboard.press('Enter');await expect(page.locator('#capPanel-hooks')).toBeVisible();await page.locator('#capPanel-hooks [role=option]').first().focus();await page.keyboard.press('End');await expect(page.locator('#capPanel-hooks [role=option]').last()).toBeFocused();
 }finally{await page.unrouteAll({behavior:'wait'});await lab.chiudi();}
});
test('EXT-RECUPERO: manifesto rotto e fiducia fallita non diventano successo',async({page},info)=>{
 const lab=await avviaEstensioniDiProva();let fallisci=false,rilascia,inizio;const gate=new Promise(r=>rilascia=r),iniziata=new Promise(r=>inizio=r);try{await lab.guastaManifesto();await page.route(ROTTE,async r=>{if(fallisci&&r.request().method()==='POST'){inizio();await gate;return r.fulfill({status:503,json:{ok:false,error:{code:'UNAVAILABLE',message:'Registro temporaneamente non disponibile'}}});}return lab.inoltra(r);});await pronta(page);await apri(page,'Connettori');const p=page.locator('#capPanel-mcp');await expect(p.getByRole('alert')).toContainText('non è un JSON valido');await foto(page,'app-errore-lettura',info);await lab.riparaManifesto();await p.getByRole('button',{name:'Aggiorna',exact:true}).click();await expect(p.getByRole('button',{name:'Fida',exact:true})).toBeEnabled();fallisci=true;await p.getByRole('button',{name:'Fida',exact:true}).click();await iniziata;await expect(p.getByRole('button',{name:'Salvataggio…',exact:true})).toBeDisabled();await p.getByRole('option').filter({hasText:'archivio'}).click();await page.locator('#capTab-plugins').click();await expect(page.locator('#capPanel-plugins').getByRole('button',{name:'Salvataggio…',exact:true})).toBeDisabled();await page.locator('#capTab-mcp').click();rilascia();await expect(p.locator('[data-ext-errore]')).toContainText('documentazione');await expect(p.locator('[data-ext-detail] h3')).toHaveText('archivio');await expect(p.getByRole('button',{name:'Fida',exact:true})).toBeEnabled();await foto(page,'app-errore-fiducia',info);fallisci=false;await p.getByRole('option').filter({hasText:'documentazione'}).click();await p.getByRole('button',{name:'Fida',exact:true}).click();await expect(p.locator('[data-ext-stato]')).toHaveText('Fidato');await expect(p.locator('[data-ext-errore]')).toBeHidden();
 }finally{rilascia();await page.unrouteAll({behavior:'wait'});await lab.chiudi();}
});
test('EXT-RISPOSTA-OBSOLETA: un caricamento vecchio non sostituisce quello nuovo',async({page})=>{const lab=await avviaEstensioniDiProva();let n=0,rilascia,inizio;const gate=new Promise(r=>rilascia=r),iniziata=new Promise(r=>inizio=r);try{await page.route(ROTTE,async r=>{if(r.request().url().endsWith('/skills')&&++n===1){inizio();await gate;return r.fulfill({json:{ok:true,data:{skills:[{id:'vecchia',name:'Risposta obsoleta',description:'Non deve sostituire il nuovo inventario.'}],errore:null}}});}return lab.inoltra(r);});await pronta(page);await apri(page,'Skill');await iniziata;await page.locator('#capTab-mcp').click();await expect(page.locator('#capPanel-mcp [role=option]')).toHaveCount(2);await page.locator('#capTab-skills').click();await expect(page.locator('#capPanel-skills [role=option]')).toHaveCount(2);const rispostaVecchia=page.waitForResponse(r=>r.url().endsWith('/skills'));rilascia();await rispostaVecchia;await expect(page.locator('#capPanel-skills')).not.toContainText('Risposta obsoleta');await expect(page.locator('#capPanel-skills')).toContainText('Revisione del progetto');}finally{rilascia();await page.unrouteAll({behavior:'wait'});await lab.chiudi();}});
