import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';import path from 'node:path';
import {avviaFonteDiProva} from './fonte-ricerca-backend-fixture.mjs';
const ROTTE=/\/api\/v1\/search-source(?:\/(?:key(?:\/remove)?|test))?$/,FOTO=path.resolve('artifacts/astra-fase2/FonteRicerca');
async function foto(page,nome,info){await mkdir(FOTO,{recursive:true});await page.screenshot({path:path.join(FOTO,nome+'-'+info.project.use.viewport.width+'.png'),animations:'disabled'});}
async function apri(page,url='http://127.0.0.1:4177'){await page.goto(url);const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();await expect(page.getByRole('textbox',{name:'Messaggio',exact:true})).toBeVisible();await page.getByRole('button',{name:/^Impostazioni(?: \(Ctrl ,\))?$/}).click();await page.getByRole('tab',{name:'Strumenti agente e permessi',exact:true}).click();await expect(page.locator('#searchSourceMount [role=radio]')).toHaveCount(6);await page.locator('#searchSourceMount').scrollIntoViewIfNeeded();return page.locator('#searchSourceMount');}
test('FONTE-ORIGINALE: confronto le sei scelte e i campi da conservare',async({page},info)=>{const lab=await avviaFonteDiProva();try{await page.route(ROTTE,r=>lab.inoltra(r));const p=await apri(page,'http://127.0.0.1:4179');await foto(page,'originale-scelte',info);for(const id of ['tavily','searxng','custom','off']){await p.locator('[data-search-source='+id+']').click();await expect(p.locator('[data-search-source='+id+']')).toHaveAttribute('aria-checked','true');await p.locator('[data-search-action=test]').scrollIntoViewIfNeeded();await foto(page,'originale-'+id,info);}}finally{await page.unrouteAll({behavior:'wait'});await lab.chiudi();}});
test('FONTE-CUSTOM-CHIAVE: imposto il mio servizio e ritrovo la scelta al ricarico',async({page},info)=>{const lab=await avviaFonteDiProva();try{await page.route(ROTTE,r=>lab.inoltra(r));const p=await apri(page);await foto(page,'app-scelte',info);await p.locator('[data-search-source=custom]').click();const key=p.getByLabel('Chiave API Endpoint personalizzato',{exact:true});await expect(key).toBeVisible();await key.fill('chiave-artificiale-di-prova');await p.getByRole('button',{name:'Salva chiave',exact:true}).click();await expect(key).toHaveValue('');await p.getByLabel('Indirizzo istanza',{exact:true}).fill('https://search.example.org');await p.getByRole('button',{name:'Salva indirizzo',exact:true}).click();await expect(p.locator('[data-search-readiness]')).toContainText('non ancora verificata');await foto(page,'app-custom',info);await page.reload();await page.getByRole('button',{name:/^Impostazioni(?: \(Ctrl ,\))?$/}).click();await page.getByRole('tab',{name:'Strumenti agente e permessi',exact:true}).click();await expect(p.locator('[data-search-source=custom]')).toHaveAttribute('aria-checked','true');await expect(p.getByLabel('Indirizzo istanza',{exact:true})).toHaveValue('https://search.example.org');await expect(key).toHaveValue('');expect(lab.riapri().source).toBe('custom');expect(await lab.leggiFile()).not.toContain('chiave-artificiale');await p.getByRole('button',{name:'Dimentica la chiave',exact:true}).click();await expect(p.getByRole('button',{name:'Dimentica la chiave',exact:true})).toHaveCount(0);await p.locator('[data-search-source=off]').click();await expect(p.locator('[data-search-readiness]')).toContainText('disattivata');await expect(p.getByRole('button',{name:'Prova la ricerca',exact:true})).toBeDisabled();expect(lab.riapri().source).toBe('off');await foto(page,'app-off',info);}finally{await page.unrouteAll({behavior:'wait'});await lab.chiudi();}});

test('FONTE-TASTIERA: scelgo i servizi con le frecce e gestisco le loro chiavi',async({page},info)=>{
 const lab=await avviaFonteDiProva();try{await page.route(ROTTE,r=>lab.inoltra(r));const p=await apri(page);await p.locator('[data-search-source=duckduckgo]').focus();await page.keyboard.press('ArrowDown');await expect(p.locator('[data-search-source=tavily]')).toHaveAttribute('aria-checked','true');await expect(p.locator('[data-search-source=tavily]')).toBeFocused();await expect(p.locator('[role=radio][tabindex="0"]')).toHaveCount(1);
 for(const [id,label] of [['tavily','Tavily'],['brave','Brave Search']]){await p.locator('[data-search-source='+id+']').click();const key=p.getByLabel('Chiave API '+label,{exact:true});await key.fill('solo-prova-'+id);await key.press('Enter');await expect(key).toHaveValue('');await expect(p.getByRole('button',{name:'Prova la ricerca',exact:true})).toBeEnabled();await expect(p.getByRole('link',{name:'Ottieni una chiave '+label,exact:true})).toHaveAttribute('rel','noopener noreferrer');await foto(page,'app-'+id,info);await p.getByRole('button',{name:'Dimentica la chiave',exact:true}).click();await expect(p.getByRole('button',{name:'Prova la ricerca',exact:true})).toBeDisabled();}
 await p.locator('[data-search-source=searxng]').click();await p.getByLabel('Indirizzo istanza',{exact:true}).fill('https://searx.example.org');await p.getByRole('button',{name:'Salva indirizzo',exact:true}).click();await expect(p.locator('[data-search-readiness]')).toContainText('non ancora verificata');await foto(page,'app-searxng',info);
 }finally{await page.unrouteAll({behavior:'wait'});await lab.chiudi();}
});
test('FONTE-PROVA e FONTE-ESITO-SCADUTO: cerco con parole mie e un errore successivo non resta verde',async({page},info)=>{
 const lab=await avviaFonteDiProva();try{await page.route(ROTTE,r=>lab.inoltra(r));const p=await apri(page),q=p.getByRole('textbox',{name:'Testo della prova',exact:true});await q.fill('come configuro la ricerca? guida su docs.searxng.org');await q.press('Enter');await expect(p.locator('[data-search-result]')).toContainText('Documentazione ufficiale');expect(lab.richieste).toEqual(['come configuro la ricerca? guida su docs.searxng.org']);await expect(p.locator('[data-search-readiness]')).toContainText('ha risposto');await expect(q).toBeFocused();await expect(p.locator('[data-search-result]'),'FONTE-ESITO-VISIBILE').toBeInViewport({ratio:1});await foto(page,'app-prova',info);lab.guastaProva(true);await q.fill('riprova con la guida aggiornata');await q.press('Enter');await expect(p.getByRole('alert')).toBeVisible();await expect(p.locator('[data-search-result]')).toBeHidden();await expect(p.locator('[data-search-readiness]')).not.toContainText('ha risposto');await expect(q).toHaveValue('riprova con la guida aggiornata');await expect(p.getByRole('alert'),'FONTE-ESITO-VISIBILE').toBeInViewport({ratio:1});await foto(page,'app-errore-prova',info);lab.guastaProva(false);await q.press('Enter');await expect(p.locator('[data-search-result]')).toBeVisible();await expect(p.getByRole('alert')).toBeHidden();
 }finally{await page.unrouteAll({behavior:'wait'});await lab.chiudi();}
});
test('FONTE-RECUPERO: il server non risponde, riprovo e conservo i campi da correggere',async({page},info)=>{
 const lab=await avviaFonteDiProva();let guasto='get';try{await page.route(ROTTE,r=>{const req=r.request();if(guasto==='get'&&req.method()==='GET'||guasto==='post'&&req.method()==='POST')return r.fulfill({status:503,json:{ok:false,error:{code:'SEARCH_STORE_UNAVAILABLE',message:'Configurazione temporaneamente non disponibile'}}});if(guasto==='invalido'&&req.method()==='GET')return r.fulfill({json:{ok:true,data:{source:'duckduckgo',fonti:null}}});return lab.inoltra(r);});await page.goto('http://127.0.0.1:4177');const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();await page.getByRole('button',{name:/^Impostazioni(?: \(Ctrl ,\))?$/}).click();await page.getByRole('tab',{name:'Strumenti agente e permessi',exact:true}).click();const p=page.locator('#searchSourceMount');await expect(p.getByRole('alert')).toBeVisible();await expect(p.getByRole('button',{name:'Aggiorna stato',exact:true})).toBeEnabled();await expect(p,'FONTE-LETTURA-TERMINATA').not.toContainText('Lettura dello stato');await foto(page,'app-errore-lettura',info);guasto='';await p.getByRole('button',{name:'Aggiorna stato',exact:true}).click();await expect(p.getByRole('radio')).toHaveCount(6);await p.locator('[data-search-source=custom]').click();const endpoint=p.getByLabel('Indirizzo istanza',{exact:true});await endpoint.fill('https://search.example.org');guasto='post';await p.getByRole('button',{name:'Salva indirizzo',exact:true}).click();await expect(p.getByRole('alert')).toBeVisible();await expect(endpoint).toHaveValue('https://search.example.org');await expect(p.getByRole('button',{name:'Salva indirizzo',exact:true})).toBeFocused();await foto(page,'app-errore-salvataggio',info);guasto='';await p.getByRole('button',{name:'Salva indirizzo',exact:true}).click();await expect(p.locator('[data-search-readiness]')).toContainText('non ancora verificata');guasto='invalido';await p.getByRole('button',{name:'Aggiorna stato',exact:true}).click();await expect(p.getByRole('alert')).toContainText('non è valida');await expect(endpoint).toHaveValue('https://search.example.org');guasto='';await p.getByRole('button',{name:'Aggiorna stato',exact:true}).click();await expect(p.getByRole('alert')).toBeHidden();
 }finally{await page.unrouteAll({behavior:'wait'});await lab.chiudi();}
});
test('FONTE-CONCORRENZA: una scelta in corso non si duplica e non mi riporta indietro',async({page})=>{
 const lab=await avviaFonteDiProva();let rilascio,inizio,post=0;const gate=new Promise(r=>rilascio=r),started=new Promise(r=>inizio=r);try{await page.route(ROTTE,async r=>{if(r.request().method()==='POST'){post++;inizio();await gate;}return lab.inoltra(r);});const p=await apri(page);await p.locator('[data-search-source=tavily]').click();await started;await expect(p).toHaveAttribute('aria-busy','true');await expect(p.locator('[data-search-source=brave]')).toBeDisabled();await page.getByRole('tab',{name:'Privacy e dati locali',exact:true}).click();rilascio();await expect(p).not.toHaveAttribute('aria-busy');await expect(page.getByRole('tab',{name:'Privacy e dati locali',exact:true})).toBeFocused();expect(post).toBe(1);await page.getByRole('tab',{name:'Strumenti agente e permessi',exact:true}).click();await expect(p.locator('[data-search-source=tavily]')).toHaveAttribute('aria-checked','true');
 }finally{rilascio();await page.unrouteAll({behavior:'wait'});await lab.chiudi();}
});
test('FONTE-SERVER-REALE: leggo la configurazione effettiva senza cambiarla',async({page})=>{const p=await apri(page);await expect(p.locator('[data-search-readiness]')).toBeVisible();await expect(p.getByRole('radio')).toHaveCount(6);await expect(p.getByRole('alert')).toBeHidden();});
