import {test,expect} from '@playwright/test';import {mkdir} from 'node:fs/promises';import path from 'node:path';
import {CAPACITA_MEMORIA as C,RUNTIME_MEMORIA as R} from '../../lab/fixtures/misura-memoria.js';
const FOTO=path.resolve('artifacts/astra-fase2/MemoryMeter');
async function foto(page,n,info){await mkdir(FOTO,{recursive:true});await page.screenshot({path:path.join(FOTO,n+'-'+info.project.use.viewport.width+'.png'),animations:'disabled'});}
async function dati(page){await page.route('**/api/v1/model-lab/capacity',r=>r.fulfill({json:{ok:true,data:C}}));await page.route('**/api/v1/runtime',r=>r.fulfill({json:{ok:true,data:{items:R}}}));}
async function apri(page,url='http://127.0.0.1:4177'){await page.goto(url);const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();await page.getByRole('button',{name:/^Impostazioni(?: \(Ctrl ,\))?$/}).click();await page.getByRole('tab',{name:'Laboratorio modelli',exact:true}).click();await page.locator('[data-model-lab-tab=overview]').click();await expect(page.locator('#machineMemoryMetric')).not.toHaveText('—');return page.locator('#modelLabOverviewPanel');}
test('MEM-ORIGINALE: guardo memoria disco e azioni originali',async({page},info)=>{await dati(page);const p=await apri(page,'http://127.0.0.1:4179');await p.locator('#machineMemoryMetric').scrollIntoViewIfNeeded();await foto(page,'originale-misure',info);await p.locator('#memoriaScarica').scrollIntoViewIfNeeded();await foto(page,'originale-azioni',info);});
test('MEM-RAM-DISCO: distinguo memoria libera spazio su disco e modello caricato',async({page},info)=>{await dati(page);const p=await apri(page);const m=p.locator('[data-c=MemoryMeter]');await expect(m).toBeVisible();await expect(m.locator('#machineFreeMemoryMetric')).toHaveText('12 GiB');await expect(m.locator('#machineAllocatableMetric')).toHaveText('99 GiB');await expect(m).toContainText('Riserva sul disco');await expect(m.locator('#memoriaScarica')).toBeEnabled();await expect(m).not.toContainText('8,1 GB');await m.scrollIntoViewIfNeeded();await foto(page,'app-misure',info);await page.reload();await page.getByRole('button',{name:/^Impostazioni/}).click();await page.getByRole('tab',{name:'Laboratorio modelli',exact:true}).click();await expect(page.locator('#machineFreeMemoryMetric')).toHaveText('12 GiB');});
test('MEM-ERRORE-MISURA e MEM-ERRORE-RUNTIME: il vecchio stato non sembra ancora valido',async({page},info)=>{await dati(page);const p=await apri(page);await page.route('**/api/v1/model-lab/capacity',r=>r.fulfill({status:503,json:{ok:false,error:{message:'Misura temporaneamente non disponibile'}}}));await p.locator('#memoriaRimisura').click();await expect(p.locator('#machineFreeMemoryMetric')).toHaveText('Non misurata');await expect(p.getByRole('alert')).toContainText('non disponibile');await expect(p.locator('#memoriaScarica')).toBeDisabled();await foto(page,'app-errore-misura',info);await page.unroute('**/api/v1/model-lab/capacity');await page.route('**/api/v1/model-lab/capacity',r=>r.fulfill({json:{ok:true,data:C}}));await page.route('**/api/v1/runtime',r=>r.fulfill({status:503,json:{ok:false,error:{message:'Motore non raggiungibile'}}}));await p.locator('#memoriaRimisura').click();await expect(p.locator('#memoriaTenuta')).toContainText('non verificato');await expect(p.locator('#memoriaScarica')).toBeDisabled();await foto(page,'app-errore-runtime',info);});
test('MEM-SCARICA-CORPO: libero soltanto il modello di TALOS e vedo il nuovo stato',async({page},info)=>{await dati(page);let calls=[];await page.route('**/api/v1/runtime/unload',async r=>{calls.push(r.request().postDataJSON());await page.route('**/api/v1/runtime',q=>q.fulfill({json:{ok:true,data:{items:[]}}}));await r.fulfill({json:{ok:true,data:{state:'stopped'}}});});const p=await apri(page);await p.locator('#memoriaScarica').click();await expect.poll(()=>calls).toEqual([{runtimeId:'llama.cpp'}]);await expect(p.locator('#memoriaScarica')).toBeDisabled();await expect(p.locator('#memoriaTenuta')).toContainText('Nessun modello caricato da TALOS');await foto(page,'app-scaricato',info);});

test('MEM-INIZIALE: attendo la verifica senza dichiarare che il modello sia assente',async({page})=>{await dati(page);let risposta;await page.route('**/api/v1/runtime',r=>new Promise(resolve=>{risposta=async()=>{await r.fulfill({json:{ok:true,data:{items:R}}});resolve();};}));try{const p=await apri(page);await expect(p.locator('#memoriaTenuta')).toContainText('Verifica del modello in corso');await expect(p.locator('#memoriaScarica')).toBeDisabled();}finally{await risposta?.();}});
test('MEM-SCARICA-CONCORRENZA: durante la liberazione non invio una seconda operazione',async({page})=>{await dati(page);let risposta,calls=0;await page.route('**/api/v1/runtime/unload',r=>new Promise(resolve=>{calls++;risposta=async()=>{await r.fulfill({json:{ok:true,data:{state:'stopped'}}});resolve();};}));try{const p=await apri(page);await p.locator('#memoriaScarica').click();await expect.poll(()=>calls).toBe(1);await expect(p.locator('#memoriaRimisura')).toBeDisabled();await expect(p.locator('#memoriaScarica')).toBeDisabled();}finally{await risposta?.();}});

test('MEM-ERRORE-SCARICA: il motore non risponde, vedo il problema e riprovo',async({page},info)=>{await dati(page);let fallisce=true,calls=0;await page.route('**/api/v1/runtime/unload',async r=>{calls++;if(fallisce)return r.fulfill({status:503,json:{ok:false,error:{message:'Il motore non risponde. Riprova.'}}});await page.route('**/api/v1/runtime',q=>q.fulfill({json:{ok:true,data:{items:[]}}}));await r.fulfill({json:{ok:true,data:{state:'stopped'}}});});const p=await apri(page);await p.locator('#memoriaScarica').click();await expect(page.getByText('Memoria non liberata',{exact:true})).toBeVisible();await expect(p.locator('#memoriaScarica')).toBeEnabled();await expect(p.locator('#memoriaTenuta')).toContainText('ha un modello caricato');await foto(page,'app-errore-scarica',info);fallisce=false;await p.locator('#memoriaScarica').click();await expect(p.locator('#memoriaTenuta')).toContainText('Nessun modello');await expect.poll(()=>calls).toBe(2);});
test('MEM-SERVER-REALE: leggo la capacità effettiva e rimisuro',async({page},info)=>{const p=await apri(page);await expect(p.locator('#machineMemoryMetric')).toContainText('GiB');await expect(p.getByRole('alert')).toBeHidden();await p.locator('#memoriaRimisura').click();await expect(p.locator('#machineFreeMemoryMetric')).toContainText('GiB');await expect(p.locator('[data-memory-meter]')).toHaveAttribute('aria-busy','false');await p.locator('[data-memory-meter]').scrollIntoViewIfNeeded();await foto(page,'app-server-reale',info);});

test('MEM-PRESSIONE-RAM: memoria piena non appare normale e la rimisura aggiorna l’avviso',async({page},info)=>{await dati(page);let capacita={...C,memory:{...C.memory,freeBytes:0}};await page.route('**/api/v1/model-lab/capacity',r=>r.fulfill({json:{ok:true,data:capacita}}));const p=await apri(page);await expect(p.locator('#machineFreeMemoryMetric')).toHaveText('0 GiB');await expect(p.locator('[data-memory-label]')).toContainText('RAM quasi esaurita');await expect(p.locator('[data-memory-bar]')).toHaveAttribute('optimum','0');await p.locator('[data-memory-meter]').scrollIntoViewIfNeeded();await foto(page,'app-ram-piena',info);capacita=C;await p.locator('#memoriaRimisura').click();await expect(p.locator('[data-memory-label]')).not.toContainText('RAM quasi esaurita');await expect(p.locator('#machineFreeMemoryMetric')).toHaveText('12 GiB');});

test('MEM-ORIGINALE-PRESSIONE: confronto il segnale originale a RAM piena',async({page},info)=>{await dati(page);await page.route('**/api/v1/model-lab/capacity',r=>r.fulfill({json:{ok:true,data:{...C,memory:{...C.memory,freeBytes:0}}}}));const p=await apri(page,'http://127.0.0.1:4179');await expect(p.locator('#memoriaBarraUsata')).toHaveAttribute('data-memoria-livello','critico');await p.locator('#memoriaRimisura').scrollIntoViewIfNeeded();await foto(page,'originale-ram-piena',info);});
