import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {STRUMENTI_FORGIATI as STRUMENTI} from '../../lab/fixtures/officina.js';
import {avviaForgeDiProva} from './forge-backend-fixture.mjs';
const APP='http://127.0.0.1:4177',ORIGINALE='http://127.0.0.1:4179',ROTTE=/\/api\/v1\/sessions\/[^/]+\/tool-forge(?:\/[^/]+\/enable)?$/;
const FOTO=path.resolve('artifacts/astra-fase2/ForgeList'),VUOTO='Nessun tool forgiato (.tool-forge-store/, globale — non del progetto). Il modello ne crea uno con tool_create.';
async function pronta(page,url=APP){await page.goto(url);const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();if(url===APP)await expect(page.getByRole('button',{name:'Libreria 0',exact:true})).toBeVisible();}
async function apriOfficina(page){const voce=page.getByRole('button',{name:/^Officina attrezzi \d+$/});if(!await voce.isVisible())await page.getByRole('button',{name:'Altro',exact:true}).click();await voce.click();}
async function foto(page,nome,info){await mkdir(FOTO,{recursive:true});await page.screenshot({path:path.join(FOTO,nome+'-'+info.project.use.viewport.width+'.png')});}
async function originale(browser,info,lab){const context=await browser.newContext({...info.project.use,locale:'it-IT'}),page=await context.newPage();await pronta(page,ORIGINALE);if(lab)await page.route(ROTTE,r=>lab.inoltra(r));if(info.project.use.viewport.width<=1040)await page.locator('.desktop-context-toggle').click();await page.getByRole('button',{name:'Gestisci capability',exact:true}).click();return {context,page};}
const payload=strumenti=>({ok:true,data:{strumenti,errore:null}});
test('OFFICINA-REALE: apro lo stato vuoto, ricarico e ritrovo gli stessi dati originali',async({page,browser},info)=>{
 const errori=[];page.on('pageerror',e=>errori.push(e.message));await pronta(page);await apriOfficina(page);await expect(page.locator('[data-forge-esito]')).toHaveText('0 attrezzi · 0 abilitati');await expect(page.locator('[data-forge-list]')).toContainText('Nessun attrezzo creato dal modello');await expect(page.locator('[data-forge-dettaglio]')).toBeHidden();await foto(page,'app-vuota',info);
 await page.reload();await expect(page.getByRole('button',{name:'Libreria 0',exact:true})).toBeVisible();await apriOfficina(page);await expect(page.locator('[data-forge-esito]')).toHaveText('0 attrezzi · 0 abilitati');expect(errori).toEqual([]);
 const o=await originale(browser,info);await o.page.getByText(VUOTO,{exact:true}).click();await foto(o.page,'originale-vuota',info);await o.context.close();
});
test('OFFICINA-PERSISTENZA: scelgo, abilito e disabilito un attrezzo nello store di prova reale',async({page,browser},info)=>{
 const lab=await avviaForgeDiProva();try{
  await pronta(page);const scritture=[];page.on('request',r=>{if(r.method()==='POST')scritture.push({url:r.url(),body:r.postDataJSON()});});await page.route(ROTTE,r=>lab.inoltra(r));await apriOfficina(page);
  const righe=page.locator('[data-forge-list] [role="option"]');await expect(righe).toHaveCount(3);await foto(page,'fixture-elenco',info);
  for(const titolo of await righe.locator('.talos-list-row__title').all())expect(await titolo.evaluate(n=>n.scrollWidth<=n.clientWidth)).toBe(true);
  const o=await originale(browser,info,lab);await o.page.getByText(STRUMENTI[1].titolo,{exact:true}).click();await expect(o.page.locator('#forgeListMount .sheet-option')).toHaveCount(3);await foto(o.page,'originale-fixture',info);await o.context.close();
  await righe.first().focus();await righe.first().press('End');await expect(righe.last()).toBeFocused();await expect(page.locator('[data-forge-rischio]')).toHaveText('R3');await righe.last().press('Home');await righe.first().press('ArrowDown');await expect(righe.nth(1)).toBeFocused();await expect(page.locator('[data-forge-capacita]')).toHaveText('scrittura di una nota');expect(scritture).toEqual([]);
  await page.getByRole('button',{name:'Abilita '+STRUMENTI[1].titolo,exact:true}).click();await expect(page.locator('[data-forge-dettaglio] h3')).toHaveText(STRUMENTI[1].titolo);await expect(page.locator('[data-forge-stato-attuale]')).toHaveText('Abilitato');expect((await lab.leggi(STRUMENTI[1].id)).abilitato).toBe(true);await page.locator('[data-forge-dettaglio]').scrollIntoViewIfNeeded();await foto(page,'fixture-dettaglio',info);
  await page.reload();await expect(page.getByRole('button',{name:'Libreria 0',exact:true})).toBeVisible();await apriOfficina(page);await page.getByRole('option',{name:new RegExp(STRUMENTI[1].titolo)}).click();await expect(page.locator('[data-forge-stato-attuale]')).toHaveText('Abilitato');
  await page.getByRole('button',{name:'Disabilita '+STRUMENTI[1].titolo,exact:true}).click();await expect(page.locator('[data-forge-dettaglio] h3')).toHaveText(STRUMENTI[1].titolo);await expect(page.locator('[data-forge-stato-attuale]')).toHaveText('Disabilitato');expect((await lab.leggi(STRUMENTI[1].id)).abilitato).toBe(false);
  expect(scritture).toHaveLength(2);expect(scritture.map(r=>r.body)).toEqual([{abilitato:true},{abilitato:false}]);expect(scritture.every(r=>r.url.endsWith('/tool-forge/'+STRUMENTI[1].id+'/enable'))).toBe(true);
  await page.getByRole('tab',{name:'Disabilitati',exact:true}).click();await expect(righe).toHaveCount(2);await page.getByLabel('Cerca per nome, descrizione o capacità',{exact:true}).fill('memory.create');await expect(righe).toHaveCount(1);await expect(page.locator('[data-forge-capacita]')).toHaveText('scrittura in memoria');await page.getByLabel('Cerca per nome, descrizione o capacità',{exact:true}).fill('inesistente');await expect(page.locator('[data-forge-list]')).toContainText('Nessun attrezzo corrisponde ai filtri');
  await expect(page.locator('#schermoOfficina [data-richiede="fase3"]:visible')).toHaveCount(0);
 }finally{await page.unroute(ROTTE);await lab.chiudi();}
});
test('OFFICINA-RECUPERO: errore di lettura o salvataggio non diventa un successo',async({page},info)=>{
 await pronta(page);await page.route(ROTTE,r=>r.fulfill({status:503,json:{ok:false,error:{code:'OFFLINE',message:'Servizio non disponibile'}}}));await apriOfficina(page);await expect(page.locator('[data-forge-esito]')).toContainText('Servizio non disponibile');await foto(page,'app-errore',info);
 await page.unroute(ROTTE);await page.route(ROTTE,r=>r.fulfill({json:payload([null])}));await page.locator('[data-forge-refresh]').click();await expect(page.locator('[data-forge-esito]')).toContainText('Elenco degli attrezzi non valido');await page.unroute(ROTTE);
 const lab=await avviaForgeDiProva();let libera;try{
  let post=0;const attesa=new Promise(r=>{libera=r;});await page.route(ROTTE,async r=>{if(r.request().method()==='POST'){post++;await attesa;await r.fulfill({status:503,json:{ok:false,error:{code:'SAVE_FAILED',message:'Salvataggio non riuscito'}}});}else await lab.inoltra(r);});
  await page.locator('[data-forge-refresh]').click();await expect(page.locator('[data-forge-list] [role="option"]')).toHaveCount(3);await page.getByRole('option',{name:new RegExp(STRUMENTI[1].titolo)}).click();await page.getByRole('button',{name:'Abilita '+STRUMENTI[1].titolo,exact:true}).click();await expect(page.locator('[data-forge-abilita]')).toBeDisabled();await expect(page.locator('[data-forge-stato-attuale]')).toHaveText('Disabilitato');
  await page.getByRole('option',{name:new RegExp(STRUMENTI[2].titolo)}).click();await expect(page.locator('[data-forge-abilita]')).toBeDisabled();await expect(page.locator('[data-forge-abilita]')).toHaveText('Abilita questo attrezzo');await page.getByRole('button',{name:/^Board \d+$/}).click();await apriOfficina(page);await expect(page.locator('[data-forge-list] [role="option"]')).toHaveCount(3);await expect(page.locator('[data-forge-abilita]')).toBeDisabled();libera();await expect(page.locator('[data-forge-errore-azione]')).toContainText('Salvataggio non riuscito');await expect(page.locator('[data-forge-abilita]')).toBeEnabled();expect(post).toBe(1);expect((await lab.leggi(STRUMENTI[1].id)).abilitato).toBe(false);await page.locator('[data-forge-errore-azione]').scrollIntoViewIfNeeded();await foto(page,'errore-abilitazione',info);
  await page.unroute(ROTTE);await page.route(ROTTE,r=>lab.inoltra(r));await page.getByRole('option',{name:new RegExp(STRUMENTI[1].titolo)}).click();await page.getByRole('button',{name:'Abilita '+STRUMENTI[1].titolo,exact:true}).click();await expect(page.locator('[data-forge-stato-attuale]')).toHaveText('Abilitato');expect((await lab.leggi(STRUMENTI[1].id)).abilitato).toBe(true);
  await page.unroute(ROTTE);let sblocca;const lenta=new Promise(r=>{sblocca=r;});let letture=0;await page.route(ROTTE,async r=>{letture++;if(letture===1){await lenta;await r.fulfill({json:payload([STRUMENTI[0]])});}else await r.fulfill({json:payload([STRUMENTI[1]])});});
  try{await page.locator('[data-forge-refresh]').click();await expect(page.locator('[data-forge-esito]')).toHaveText('Caricamento Officina…');await page.getByRole('button',{name:/^Board \d+$/}).click();await apriOfficina(page);await expect(page.locator('[data-forge-list] .talos-list-row__title')).toHaveText(STRUMENTI[1].titolo);const obsoleta=page.waitForResponse(r=>r.url().endsWith('/tool-forge'));sblocca();await(await obsoleta).finished();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await expect(page.locator('[data-forge-list] .talos-list-row__title')).toHaveText(STRUMENTI[1].titolo);}finally{sblocca();}
 }finally{libera?.();await page.unrouteAll({behavior:'wait'});await lab.chiudi();}
});
