import {test,expect} from '@playwright/test';import {mkdir} from 'node:fs/promises';import path from 'node:path';
import {CAPACITA_MEMORIA as C} from '../../lab/fixtures/misura-memoria.js';import {RUNTIME_MODELLI as R} from '../../lab/fixtures/runtime-modelli.js';
const FOTO=path.resolve('artifacts/astra-fase2/RuntimeCard');
async function foto(page,n,info){await mkdir(FOTO,{recursive:true});await page.screenshot({path:path.join(FOTO,n+'-'+info.project.use.viewport.width+'.png'),animations:'disabled'});}
async function dati(page,items){await page.route('**/api/v1/model-lab/capacity',r=>r.fulfill({json:{ok:true,data:C}}));await page.route('**/api/v1/runtime',r=>r.fulfill({json:{ok:true,data:{items}}}));}
async function apri(page,url='http://127.0.0.1:4177'){await page.goto(url);const salta=page.getByRole('button',{name:'Salta per ora',exact:true});if(await salta.isVisible())await salta.click();await page.getByRole('button',{name:/^Impostazioni(?: \(Ctrl ,\))?$/}).click();await page.getByRole('tab',{name:'Laboratorio modelli',exact:true}).click();await page.locator('[data-model-lab-tab=overview]').click();await expect(page.locator('#modelLabRuntimeStatus')).not.toContainText('Verifica');await page.locator('#modelLabRuntimeList').scrollIntoViewIfNeeded();return page.locator('#modelLabRuntimeGate');}
const vuoto={runtimeId:'ollama',state:'observed',baseUrl:'http://127.0.0.1:11434',observedAt:R[0].observedAt,models:[]};
test('RUN-ORIGINALE: guardo motori raggiunti vuoti ed errore lista',async({page},info)=>{await dati(page,[...R,vuoto,{...vuoto,runtimeId:'lmstudio',modelsError:'RUNTIME_FAILED'}]);await apri(page,'http://127.0.0.1:4179');await foto(page,'originale-stati',info);});
test('RUN-OSSERVATO-VUOTO: un motore senza modelli resta raggiunto',async({page},info)=>{await dati(page,[vuoto]);const p=await apri(page);await expect(p.locator('#modelLabRuntimeList')).toContainText('Raggiunto');await expect(p.locator('#modelLabRuntimeList')).toContainText('Nessun modello disponibile');await expect(p.locator('#modelLabRunButton')).toBeDisabled();await foto(page,'app-vuoto',info);});
test('RUN-ELENCO-ERRORE: distinguo connessione e lettura dei modelli',async({page},info)=>{await dati(page,[{...vuoto,modelsError:'RUNTIME_FAILED'}]);const p=await apri(page);await expect(p.locator('#modelLabRuntimeList')).toContainText('Raggiunto');await expect(p.locator('#modelLabRuntimeList')).toContainText('Lettura dei modelli non riuscita');await expect(p.locator('#modelLabRunButton')).toBeDisabled();await foto(page,'app-errore-lista',info);});
test('RUN-SELEZIONE: scelgo motore e modello e li ritrovo dopo Aggiorna',async({page},info)=>{await dati(page,[...R,{...vuoto,models:[{id:'uno',name:'Uno'},{id:'due',name:'Due'}]}]);const p=await apri(page);await p.locator('#modelLabRuntimeSelect').selectOption('ollama');await p.locator('#modelLabModelSelect').selectOption('due');await p.locator('#modelLabRuntimeRefresh').click();await expect(p.locator('#modelLabRuntimeSelect')).toHaveValue('ollama');await expect(p.locator('#modelLabModelSelect')).toHaveValue('due');const o=p.locator('[data-runtime-id=ollama]');await expect(o).toContainText('2 modelli disponibili');await expect(o).toContainText('Non rilevato');await expect(o).not.toContainText('Modello caricato da TALOS');await p.locator('#modelLabRuntimeList').scrollIntoViewIfNeeded();if(info.project.use.viewport.width>=1280){const boxes=await p.locator('[data-c=RuntimeCard]').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().top));expect(boxes[0],'RUN-DENSITA: due motori sullo stesso livello').toBe(boxes[1]);}await foto(page,'app-stati',info);});
test('RUN-RIPROVA: errore cancella i dati vecchi e posso recuperare',async({page},info)=>{await dati(page,R);const p=await apri(page);await page.route('**/api/v1/runtime',r=>r.fulfill({status:503,json:{ok:false,error:{message:'Motore temporaneamente non disponibile'}}}));await p.locator('#modelLabRuntimeRefresh').click();await expect(p.locator('#modelLabRuntimeList')).not.toContainText('Modello di prova');await expect(p.locator('#modelLabRunButton')).toBeDisabled();await expect(p.locator('#modelLabRuntimeList')).toContainText('non disponibile');await foto(page,'app-errore',info);await page.route('**/api/v1/runtime',r=>r.fulfill({json:{ok:true,data:{items:R}}}));await p.locator('#modelLabRuntimeRefresh').click();await expect(p.locator('#modelLabRuntimeList')).toContainText('Modello di prova');await expect(p.locator('#modelLabRunButton')).toBeEnabled();});
test('RUN-SERVER-REALE: rileggo i runtime osservati dal server',async({page},info)=>{const response=await page.request.get('http://127.0.0.1:4177/api/v1/runtime');const body=await response.json();const p=await apri(page);await expect(p.locator('[data-runtime-id]')).toContainText(body.data.items.map(r=>r.runtimeId==='lmstudio'?'LM Studio':r.runtimeId==='ollama'?'Ollama':r.runtimeId));await p.locator('#modelLabRuntimeRefresh').click();await expect(p.locator('#modelLabRuntimeRefresh')).toBeEnabled();await p.locator('#modelLabRuntimeList').scrollIntoViewIfNeeded();await foto(page,'app-server-reale',info);});

test('RUN-INIZIALE: aspetto la lettura senza vedere dati precedenti o avviare una prova',async({page},info)=>{await dati(page,R);const p=await apri(page);let rispondi;await page.route('**/api/v1/runtime',r=>new Promise(resolve=>{rispondi=async()=>{await r.fulfill({json:{ok:true,data:{items:[]}}});resolve();};}));try{await p.locator('#modelLabRuntimeRefresh').click();await expect(p.locator('#modelLabRuntimeList')).toHaveAttribute('aria-busy','true');await expect(p.locator('#modelLabRuntimeList')).toContainText('Verifica dei motori in corso');await expect(p.locator('#modelLabRuntimeList')).not.toContainText('Modello di prova');await expect(p.locator('#modelLabRuntimeSelect')).toBeDisabled();await expect(p.locator('#modelLabRunButton')).toBeDisabled();await expect(p.locator('#modelLabRuntimeRefresh')).toBeDisabled();await foto(page,'app-attesa',info);}finally{await rispondi?.();}await expect(p.locator('#modelLabRuntimeList')).toContainText('Nessun motore configurato');await expect(p.locator('#modelLabRuntimeRefresh')).toBeEnabled();await foto(page,'app-nessun-motore',info);});
test('RUN-TESTI-LUNGHI: tutti i nomi restano leggibili e il testo remoto non è HTML',async({page},info)=>{const nome='<img src=x onerror=alert(1)> '+ 'modello-lungo-'.repeat(20);await dati(page,[{...vuoto,models:[{id:nome,name:nome}]}]);const p=await apri(page);const card=p.locator('[data-c=RuntimeCard]');await expect(card.locator('li')).toHaveText(nome);await expect(card.locator('img')).toHaveCount(0);const dims=await card.evaluate(n=>({larghezza:n.clientWidth,contenuto:n.scrollWidth}));expect(dims.contenuto).toBeLessThanOrEqual(dims.larghezza+1);await foto(page,'app-nome-lungo',info);});
test('RUN-SUPERVISORE: un motore in arresto non diventa pronto',async({page},info)=>{await dati(page,[{...R[0],runtimeState:'stopping'}]);const p=await apri(page);await expect(p.locator('[data-c=RuntimeCard]')).toContainText('Arresto in corso');await expect(p.locator('[data-c=RuntimeCard] .talos-badge')).not.toHaveText('Raggiunto');await expect(p.locator('#modelLabRunButton')).toBeDisabled();await foto(page,'app-arresto',info);});
